//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef _DVTFilterSession_h
#define _DVTFilterSession_h
#import <Foundation/Foundation.h>

#include "DVTFilterExpressionController.h"

@class DVTCompoundFilterExpression;
@protocol DVTFilterSession;

@class DVTFilterExpressionController;

@interface _DVTFilterSession : NSObject<DVTFilterSession>

@property BOOL isCancelled;
@property long long filterProgress;
@property (readonly) DVTFilterExpressionController *filterExpressionController;
@property (retain) DVTCompoundFilterExpression *filterExpression;

/* instance methods */
- (id)initWithFilterExpressionController:(id)controller filterExpression:(id)expression;
- (void)setMatches:(id)matches;
@end

#endif /* _DVTFilterSession_h */
