//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
//

@class NSSplitViewController, NSSplitViewItem;

@protocol _IDEEditorContextSplitViewControllerDelegate
- (void)splitViewController:(NSSplitViewController *)arg1 auxiliarySplitViewItemWasResized:(NSSplitViewItem *)arg2;
- (void)splitViewController:(NSSplitViewController *)arg1 auxiliarySplitViewItemDidCollapse:(NSSplitViewItem *)arg2;
@end

