//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef _IDENavigableItemFilterMatcher_h
#define _IDENavigableItemFilterMatcher_h
#import <Foundation/Foundation.h>

@interface _IDENavigableItemFilterMatcher : NSObject
/* instance methods */
- (BOOL)_matchesNavigableItem:(id)item;
- (BOOL)_matchesRepresentedObject:(id)object;
@end

#endif /* _IDENavigableItemFilterMatcher_h */
