//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef _IDENavigatorOutlineViewDataSource_h
#define _IDENavigatorOutlineViewDataSource_h
#import <Foundation/Foundation.h>

#include "DVTInvalidation-Protocol.h"
#include "IDENICFilterProxy.h"
#include "IDENavigableItemFilter.h"
#include "IDENavigatorOutlineView.h"

@class DVTNotificationToken, DVTStackBacktrace, NSArray, NSHashTable, NSMapTable, NSString, IDENavigatorOutlineView;

@interface _IDENavigatorOutlineViewDataSource : NSObject<NSOutlineViewDataSource, NSOutlineViewDelegate, DVTInvalidation> {
  /* instance variables */
  DVTNotificationToken *_navigableItemGraphObserver;
  DVTNotificationToken *_navigableItemPropertyObserver;
  DVTNotificationToken *_forgottenNavigableItemsObserver;
  NSMapTable *_navItemChangeCountByItem;
  IDENICFilterProxy *_coordinatorFilteredItems;
  unsigned long long _numberOfRowsBeforeExpandOrCollapse;
  double _currentModifiedExpansionTimestamp;
  IDENavigableItemFilter *_lastFilter;
  struct { unsigned int realDataSourceRespondsTo_child_ofItem :1 ; unsigned int realDataSourceRespondsTo_childItemsForItem :1 ; unsigned int realDataSourceRespondsTo_isItemExpandable :1 ; unsigned int realDataSourceRespondsTo_numberOfChildrenOfItem :1 ; unsigned int realDataSourceRespondsTo_objectValueForTableColumn_byItem :1 ; unsigned int realDataSourceRespondsTo_setObjectValue_forTableColumn_byItem :1 ; unsigned int realDelegateRespondsTo_willDisplayCell_forTableColumn_item :1 ; unsigned int realDelegateRespondsTo_selectionIndexesForProposedSelection :1 ; unsigned int realDelegateRespondsTo_dataCell_forTableColumn_item :1 ; unsigned int realDelegateRespondsTo_ItemDidExpand :1 ; unsigned int realDelegateRespondsTo_ItemDidCollapse :1 ; unsigned int realDelegateRespondsTo_heightOfRowByItem :1 ; unsigned int realDelegateRespondsTo_shouldShowOutlineCellForItem :1 ; unsigned int realDelegateRespondsTo_shouldExpandItem :1 ; unsigned int realDelegateRespondsTo_shouldCollapseItem :1 ; unsigned int realDelegateRespondsTo_outlineViewSelectionDidChange :1 ; unsigned int realDelegateRespondsTo_toolTipForCell :1 ; unsigned int realDelegateRespondsTo_isGroupHeaderItem :1 ; unsigned int realDelegateRespondsTo_shouldShowCellExpansion :1 ; unsigned int notifyingDelegateOfExpandOrCollapse :1 ; unsigned int clearingExpandedItems :1 ; unsigned int accessingChildItemsForItem :1 ; unsigned int _pad :8 ; } _idenovdsFlags;
}

@property (retain) IDENavigatorOutlineView *outlineView;
@property (copy) NSArray *rootItems;
@property (retain) id realObject;
@property (readonly) NSHashTable *expandedItems;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) BOOL valid;
@property (readonly) DVTStackBacktrace *invalidationBacktrace;
@property (retain) DVTStackBacktrace *creationBacktrace;

/* class methods */
+ (void)initialize;

/* instance methods */
- (id)initWithOutlineView:(id)view realObject:(id)object;
- (void)primitiveInvalidate;
- (long long)countOfOutlineViewDataSourceRootItems;
- (id)objectInOutlineViewDataSourceRootItemsAtIndex:(long long)index;
- (BOOL)_notifyingRealDelegateOfExpandOrCollapse;
- (void)_clearExpandedItems;
- (void)_processNavigableItemGraphChangeNotification:(id)notification;
- (void)_processNavigableItemDidForgetNotification:(id)notification;
- (void)_refreshFilter;
- (id)childItemsForItem:(id)item;
- (BOOL)respondsToSelector:(SEL)selector;
- (id)forwardingTargetForSelector:(SEL)selector;
- (id)outlineView:(id)view child:(long long)child ofItem:(id)item;
- (BOOL)outlineView:(id)view isItemExpandable:(id)expandable;
- (long long)outlineView:(id)view numberOfChildrenOfItem:(id)item;
- (id)outlineView:(id)view objectValueForTableColumn:(id)column byItem:(id)item;
- (void)outlineView:(id)view setObjectValue:(id)value forTableColumn:(id)column byItem:(id)item;
- (id)outlineView:(id)view selectionIndexesForProposedSelection:(id)selection;
- (BOOL)outlineView:(id)view shouldEditTableColumn:(id)column item:(id)item;
- (id)outlineView:(id)view dataCellForTableColumn:(id)column item:(id)item;
- (BOOL)outlineView:(id)view shouldShowCellExpansionForTableColumn:(id)column item:(id)item;
- (id)outlineView:(id)view toolTipForCell:(id)cell rect:(struct CGRect *)rect tableColumn:(id)column item:(id)item mouseLocation:(struct CGPoint)location;
- (void)outlineView:(id)view willDisplayCell:(id)cell forTableColumn:(id)column item:(id)item;
- (void)outlineViewSelectionDidChange:(id)change;
- (BOOL)outlineView:(id)view shouldShowOutlineCellForItem:(id)item;
- (BOOL)outlineView:(id)view shouldExpandItem:(id)item;
- (BOOL)_shouldExpandCollapseSiblingsOfItem:(id)item;
- (void)outlineViewItemDidExpand:(id)expand;
- (BOOL)outlineView:(id)view shouldCollapseItem:(id)item;
- (void)outlineViewItemDidCollapse:(id)collapse;
- (BOOL)outlineView:(id)view isGroupHeaderItem:(id)item;
- (double)_outlineView:(id)view heightOfRowByItem:(id)item;
- (double)outlineView:(id)view heightOfRowByItem:(id)item;
@end

#endif /* _IDENavigatorOutlineViewDataSource_h */
