//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef _IDEGeniusResultsContext_h
#define _IDEGeniusResultsContext_h
#import <Foundation/Foundation.h>

#include "DVTInvalidation-Protocol.h"
#include "IDEGeniusResultsGraphNode.h"
#include "IDENavigableItem.h"

@class DVTStackBacktrace, NSString;

@interface _IDEGeniusResultsContext : NSObject<DVTInvalidation> {
  /* instance variables */
  IDEGeniusResultsGraphNode *_geniusResultsGraphNode;
}

@property (copy) NSString *geniusCategory;
@property (retain, nonatomic) IDENavigableItem *geniusRootNavigableItem;
@property (readonly, nonatomic) BOOL valid;
@property (readonly) DVTStackBacktrace *invalidationBacktrace;
@property (retain) DVTStackBacktrace *creationBacktrace;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)initialize;

/* instance methods */
- (void)primitiveInvalidate;
@end

#endif /* _IDEGeniusResultsContext_h */
