//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef _IDEWorkspaceBaseNoticeSubsystem_h
#define _IDEWorkspaceBaseNoticeSubsystem_h
#import <Foundation/Foundation.h>

#include "DVTInvalidation_NSObject.h"

@class DVTStackBacktrace;

@interface _IDEWorkspaceBaseNoticeSubsystem : DVTInvalidation_NSObject

@property (nonatomic, retain) DVTStackBacktrace *creationBacktrace;

/* instance methods */
- (id)createDocumentNoticeProviderManagerWith:(id)with;
- (id)init;
- (void)primitiveInvalidate;
@end

#endif /* _IDEWorkspaceBaseNoticeSubsystem_h */
