//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef _TtC13IDEFoundation28IDELocationScenarioReference_h
#define _TtC13IDEFoundation28IDELocationScenarioReference_h
#import <Foundation/Foundation.h>

#include "_TtC13IDEFoundation24IDESchemeOptionReference.h"
#include "DVTXMLUnarchiving-Protocol.h"

@class NSString;

@interface IDEFoundation_IDELocationScenarioReference : IDEFoundation_IDESchemeOptionReference<DVTXMLUnarchiving> // (Swift)

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) long long referenceType;

/* instance methods */
- (id)initFromXMLUnarchiver:(id)xmlunarchiver archiveVersion:(float)version;
- (void)setReferenceTypeFromUTF8String:(char *)string fromXMLUnarchiver:(id)xmlunarchiver;
- (void)dvt_encodeAttributesWithXMLArchiver:(id)xmlarchiver version:(id)version;
- (void)dvt_encodeRelationshipsWithXMLArchiver:(id)xmlarchiver version:(id)version;
- (id)initWithIdentifier:(id)identifier referenceType:(long long)type;
- (id)initWithLocationScenario:(id)scenario;
- (id)init;
- (BOOL)isEqual:(id)equal;
- (id)initWithIdentifier:(id)identifier;
@end

#endif /* _TtC13IDEFoundation28IDELocationScenarioReference_h */
