//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef _TtC13IDEFoundation18IDEResultReference_h
#define _TtC13IDEFoundation18IDEResultReference_h
#import <Foundation/Foundation.h>

@class NSString;

@interface IDEFoundation_IDEResultReference : NSObject<NSCopying> // (Swift)

@property (nonatomic, readonly) NSString *id;
@property (nonatomic, readonly) long long hash;

/* class methods */
+ (BOOL)clearCacheAndReturnError:(id *)error;

/* instance methods */
- (id)initWithId:(id)id;
- (id)copyWithZone:(void *)zone;
- (BOOL)isEqual:(id)equal;
- (id)init;
@end

#endif /* _TtC13IDEFoundation18IDEResultReference_h */
