//
//     Generated by class-dump 3.5-0.1.1 (64 bit) (forked by @manicmaniac).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
//

@protocol DVTInvalidation;

@protocol _TtP6IDEKit39IDETestReportCallStackCodeRoll_Document_
- (id <DVTInvalidation>)observeCloseWithHandler:(BOOL (^)(id <_TtP6IDEKit39IDETestReportCallStackCodeRoll_Document_>))arg1;
@property(nonatomic, readonly) BOOL isClosed;
@end

