//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22522.0.0.0.0
//
#ifndef DBGLLDBLauncher_h
#define DBGLLDBLauncher_h
#import <Foundation/Foundation.h>

#include "IDERunOperationPathWorker.h"
#include "DBGLLDBSession.h"
#include "DBGSBDebugger-Protocol.h"
#include "IDEConsoleAdaptorDelegateProtocol-Protocol.h"

@class DVTDispatchLock, NSString;
@protocol OS_dispatch_queue;

@interface DBGLLDBLauncher : IDERunOperationPathWorker<IDEConsoleAdaptorDelegateProtocol> {
  /* instance variables */
  NSObject<DBGSBDebugger> *_lldbDebugger;
  NSString *_lastKnownDebuggerPrompt;
  BOOL _ignorePromptOnce;
  NSObject<OS_dispatch_queue> *_executeLLDBCommandQueue;
  BOOL _hasFinishedRunning;
  BOOL _shouldProceedToAttach;
  DVTDispatchLock *_lifeCycleLock;
  NSString *_deviceSupportSymbolsPath;
  NSString *_remoteInstallPath;
  BOOL _lldbTargetFromLocalPath;
  BOOL _useOnlyStandardLLDBFramework;
  BOOL _hasQueriedLLDBRPCUserDefaults;
}

@property (retain) DBGLLDBSession *debugSession;
@property BOOL forceKillingLLDBRPCServer;
@property (readonly) BOOL terminateCalled;
@property (readonly) int lldbRPCServerPID;

/* class methods */
+ (void)initialize;
+ (unsigned long long)assertionBehaviorAfterEndOfEventForSelector:(SEL)selector;

/* instance methods */
- (id)initWithExtensionIdentifier:(id)identifier launchSession:(id)session;
- (BOOL)useOnyStandardLLDBFramework;
- (void)forceKillLLDBRPCServer;
- (void)_logDebugStringFromLLDB:(const char *)lldb;
- (void)_logToConsoleForUserActions:(id)actions;
- (void)setFinishedRunning:(id)running;
- (id)lldbDebugger;
- (void)_sourceLLDBInitFile:(id)file;
- (BOOL)_createDebuggerConsoleAdaptor:(id *)adaptor launchParameters:(id)parameters;
- (BOOL)_createBasicDebuggerObjects:(id)objects outError:(id *)error;
- (void)_executeLLDBCommands:(id)lldbcommands;
- (id)parseConsoleInputFromOriginalInput:(id)input;
- (id)parseConsoleOutputFromOriginalOutput:(id)output;
- (id)_launchErrorForDescription:(id)description message:(id)message rawErrorMessage:(id)message;
- (id)_modifyMessageForDisplay:(id)display suggestedErrorCode:(int *)code;
- (void)_logSetUID:(unsigned int)uid;
- (id)_errorStringFromLLDBError:(id)lldberror;
- (id)_errorMessageForAttachingToName:(id)name;
- (id)_errorMessageForAttachingToPID:(unsigned long long)pid;
- (void)_setErrorDueToDebugMoreThanOnce:(id)once code:(int)code;
- (BOOL)_shouldProceedAttachToName:(id)name;
- (BOOL)_shouldProceedAttachToPID:(unsigned long long)pid;
- (id)_doAttachWithTarget:(id)target outError:(id *)error;
- (id)errorForLLDBLaunchError:(id)error messageForLogging:(id)logging;
- (id)_createTargetConsoleAdaptor;
- (const char *)UTF8StringFromPotentialString:(id)string;
- (BOOL)_configureConsoleMode:(id)mode forLaunchInfo:(id)info;
- (id)_doRegularDebugWithTarget:(id)target useConnectRemote:(BOOL)remote outError:(id *)error messageForLogging:(id)logging;
- (id)_tryWithAnotherArchitectureOnBinaryPath:(id)path;
- (id)_devicePathSubstitutionPairsString;
- (void)_setPlatformForStart:(id)start;
- (void)_setMiscHandleCommands:(id)commands;
- (void)_setupSearchPaths:(id)paths;
- (void)_warnSlowLaunchDSYMForUUIDEnabled;
- (void)_warnSlowLaunchReadFromMemory:(unsigned long long)memory;
- (void)_warnSlowLaunch;
- (void)removeTrackedPID:(unsigned long long)pid forDeviceIdentifier:(id)identifier;
- (void)removeTrackedName:(id)name addTrackedPID:(unsigned long long)pid forDeviceIdentifier:(id)identifier;
- (id)_createLLDBTarget:(id)lldbtarget creationMode:(unsigned long long *)mode messageForLogging:(id *)logging outEror:(id *)eror;
- (id)_checkConnectRemote:(id)remote lldbTarget:(id)target creationMode:(unsigned long long)mode messageForLogging:(id)logging outError:(id *)error;
- (id)_launchLLDBProcess:(id)lldbprocess creationMode:(unsigned long long *)mode outError:(id *)error;
- (void)start;
- (void)terminate;
- (void)_logDebugOptions:(id)options;
- (id)logSectionTitle;
- (id)logSectionDetails;
- (id)_storeKitConfigurationFileSync;
- (void)primitiveInvalidate;
@end

#endif /* DBGLLDBLauncher_h */
