//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22526.0.0.0.0
//
#ifndef DTFileSystemEventStreamDelegate_Protocol_h
#define DTFileSystemEventStreamDelegate_Protocol_h
#import <Foundation/Foundation.h>

@protocol DTFileSystemEventStreamDelegate <NSObject>
/* instance methods */
- (void)fileSystemEventStream:(id)stream notedChangeAtPath:(id)path scanRecursively:(BOOL)recursively;
@optional
/* instance methods */
- (void)fileSystemEventStream:(id)stream notedChangeOfRootPath:(id)path;
- (void)fileSystemEventStream:(id)stream notedVolumeMount:(id)mount;
- (void)fileSystemEventStream:(id)stream notedVolumeUnmount:(id)unmount;
- (void)historyCompleteForFileSystemEventStream:(id)stream;
- (void)historyWrappedForFileSystemEventStream:(id)stream;
@end

#endif /* DTFileSystemEventStreamDelegate_Protocol_h */
