//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTBuildVersion_h
#define DVTBuildVersion_h
#import <Foundation/Foundation.h>

@class NSString;

@interface DVTBuildVersion : NSObject

@property (readonly, copy) NSString *stringValue;
@property (readonly) unsigned long long buildVersionMajorNumber;
@property (readonly, copy) NSString *buildVersionMajorLetter;
@property (readonly) unsigned long long buildVersionMinorNumber;
@property (readonly, copy) NSString *buildVersionMinorLetter;

/* class methods */
+ (id)currentSystemVersion;
+ (id)buildVersionWithString:(id)string;
+ (id)validatedBuildVersionWithString:(id)string;
+ (id)buildVersionRegex;
+ (BOOL)isValid:(id)valid;

/* instance methods */
- (id)initWithString:(id)string;
- (id)name;
- (long long)compare:(id)compare;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
@end

#endif /* DVTBuildVersion_h */
