//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTConditionInducer_h
#define DVTConditionInducer_h
#import <Foundation/Foundation.h>

#include "DVTConditionInducerProfile.h"

@class NSArray, NSString;

@interface DVTConditionInducer : NSObject

@property (copy) NSString *identifier;
@property (copy) NSString *name;
@property BOOL destructive;
@property BOOL internal;
@property (retain) NSArray *profiles;
@property unsigned long long state;
@property (weak) DVTConditionInducerProfile *activeProfile;

/* instance methods */
- (id)initWithIdentifier:(id)identifier name:(id)name isDestructive:(BOOL)destructive isInternal:(BOOL)internal profiles:(id)profiles;
- (id)debugDescription;
- (BOOL)isDestructive;
- (BOOL)isInternal;
@end

#endif /* DVTConditionInducer_h */
