//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTConditionInducerProfile_h
#define DVTConditionInducerProfile_h
#import <Foundation/Foundation.h>

@class NSString;

@interface DVTConditionInducerProfile : NSObject

@property (readonly, copy) NSString *identifier;
@property (readonly, copy) NSString *name;
@property (readonly, copy) NSString *profileDescription;

/* instance methods */
- (id)initWithIdentifier:(id)identifier name:(id)name description:(id)description;
- (id)debugDescription;
@end

#endif /* DVTConditionInducerProfile_h */
