//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTConditionInducerSession_h
#define DVTConditionInducerSession_h
#import <Foundation/Foundation.h>

#include "DVTBasicDevice-Protocol.h"
#include "DVTConditionInducer.h"
#include "DVTDevice.h"
#include "DVTObservingToken.h"

@class DTXChannel, NSArray, NSMapTable;
@protocol OS_dispatch_queue, OS_os_log;

@interface DVTConditionInducerSession : NSObject

@property (retain) NSObject<DVTBasicDevice> *basicDevice;
@property (retain) DVTDevice *connectedDevice;
@property unsigned long long serviceState;
@property (retain) NSObject<OS_dispatch_queue> *channelQueue;
@property (retain) DTXChannel *channel;
@property BOOL channelResetQueued;
@property BOOL deviceIsAvailable;
@property (retain) NSMapTable *registeredCallbackBlocks;
@property (retain) DVTObservingToken *deviceAvailabilityObservingToken;
@property (retain) NSObject<OS_os_log> *log;
@property (retain) NSArray *availableConditions;
@property (retain) DVTConditionInducer *activeCondition;

/* instance methods */
- (id)initWithDevice:(id)device;
- (void)dealloc;
- (void)_resetChannel;
- (void)_cancelChannel;
- (BOOL)_connectChannelWithDevice:(id)device;
- (void)_handleMessage:(id)message;
- (BOOL)_preflightServiceRequestWithCompletion:(id /* block */)completion;
- (void)fetchAvailableConditionInducersWithCompletion:(id /* block */)completion;
- (void)enableConditionInducer:(id)inducer profile:(id)profile completion:(id /* block */)completion;
- (void)disableConditionInducer:(id)inducer completion:(id /* block */)completion;
- (void)_updateAvailableConditionInducersWithDictionary:(id)dictionary;
- (void)_activeConditionTearingDown;
- (void)_clearActiveCondition;
- (void)registerStateChangedCallbackWithOwner:(id)owner block:(id /* block */)block;
- (void)unRegisterStateChangedCallbackWithOwner:(id)owner;
- (void)_conditionInducerStateDidChange;
@end

#endif /* DVTConditionInducerSession_h */
