//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22522.0.0.0.0
//
#ifndef DVTDiffSessionTextEditBuffer_Protocol_h
#define DVTDiffSessionTextEditBuffer_Protocol_h
#import <Foundation/Foundation.h>

@protocol DVTDiffSessionTextEditBuffer <NSObject>

@property (nonatomic, readonly) NSString *string;

/* instance methods */
- (void)beginEditing;
- (void)endEditing;
- (void)replaceCharactersInRange:(struct _NSRange)range withString:(id)string;
- (void)replaceCharactersInRange:(struct _NSRange)range withString:(id)string withUndoManager:(id)manager;
- (void)setAttributedString:(id)string;
@end

#endif /* DVTDiffSessionTextEditBuffer_Protocol_h */
