//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
//

#include "Shared.h"

#import "DVTOutlineView.h"

@interface DVTExplorerOutlineViewBase : DVTOutlineView
{
    BOOL _processingAccessibilityRowSelection;
}

@property BOOL processingAccessibilityRowSelection; // @synthesize processingAccessibilityRowSelection=_processingAccessibilityRowSelection;
- (void)accessibilitySetSelectedRowsAttribute:(id)arg1;
- (double)_indentationForRow:(long long)arg1 withLevel:(long long)arg2 isSourceListGroupRow:(BOOL)arg3;
- (BOOL)shouldIncreaseIndentationLevelAtRow:(long long)arg1;

@end

