//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTFindBar_h
#define DVTFindBar_h
#import <Foundation/Foundation.h>

#include ".h"
#include "DVTFindBarOptionsCtrl.h"
#include "DVTFindPatternManager-Protocol.h"
#include "DVTScopeBarContentController-Protocol.h"

@class DVTBorderedView, DVTFindPatternComponents, DVTLogAspect, DVTObservingToken, DVTSharedFindState, DVTStackView_AppKitAutolayout, NSAttributedString, NSLayoutConstraint, NSMutableArray, NSPopUpButton, NSSegmentedControl, NSString, NSTextField, NSTimer, NSView;
@protocol DVTFindBarHostable, DVTFindPatternTextField<DVTFindPatternField, DVTSearchField<DVTFindPatternField;

@interface DVTFindBar : <DVTFindPatternManager, DVTScopeBarContentController> {
  /* instance variables */
  NSPopUpButton *_finderModePopUpButton;
  DVTSearchField<DVTFindPatternField> *_findStringField;
  DVTFindPatternTextField<DVTFindPatternField> *_replaceStringField;
  NSSegmentedControl *_segmentedControl;
  DVTStackView_AppKitAutolayout *_stackView;
  DVTBorderedView *_replaceModeView;
  NSTextField *_replaceTextField;
  NSTimer *_editedTimer;
  DVTSharedFindState *_findState;
  NSMutableArray *_recents;
  struct _DVTFindBarFlags { unsigned int x :1 findResultsValid; unsigned int x :1 userIsChangingFindString; unsigned int x :1 userIsChangingReplaceString; unsigned int x :1 userIsRestoringHistory; unsigned int x :1 dismissRestoresSelection; unsigned int x :1 ignoreNextInvalidate; unsigned int x :1 viewIsInstalled; unsigned int x :29 _reserved; } _fbflags;
  DVTObservingToken *_findTypeObserver;
  DVTObservingToken *_findStateFindStringObsT;
  DVTObservingToken *_findStateReplaceStringObsT;
}

@property double preferredViewHeight;
@property BOOL recentsNeedUpdate;
@property (weak) NSView *findBarView;
@property (weak) NSSegmentedControl *replaceSegmentedControl;
@property (weak) NSSegmentedControl *doneSegmentedButtom;
@property (weak) NSLayoutConstraint *findSearchFieldLeadingConstraint;
@property (weak) NSLayoutConstraint *replaceSegmentControlWidth;
@property (weak) NSLayoutConstraint *findSearchFieldHeightConstraint;
@property (weak) NSLayoutConstraint *replaceSearchFieldHeightConstraint;
@property (copy, nonatomic) DVTFindPatternComponents *findPatternComponents;
@property (copy, nonatomic) NSAttributedString *findAttributedString;
@property (copy, nonatomic) NSString *findString;
@property (readonly, copy, nonatomic) NSString *findRegularExpression;
@property (copy, nonatomic) DVTFindPatternComponents *replacePatternComponents;
@property (copy, nonatomic) NSAttributedString *replaceAttributedString;
@property (copy) NSString *replaceString;
@property (readonly, copy, nonatomic) NSString *replaceExpression;
@property BOOL canReplace;
@property (nonatomic) BOOL hasResults;
@property (nonatomic) long long numberOfMatches;
@property BOOL findResultsValid;
@property BOOL ignoreNextInvalidate;
@property (readonly) BOOL viewIsInstalled;
@property (readonly) DVTLogAspect *logAspect;
@property (readonly) DVTFindBarOptionsCtrl *optionsCtrl;
@property (retain) NSObject<DVTFindBarHostable> *delegate;
@property (retain, nonatomic) id findObject;
@property (readonly) BOOL supportsReplace;
@property (nonatomic) unsigned long long finderMode;
@property (readonly) BOOL findFieldHasFocus;
@property (readonly) BOOL replaceFieldHasFocus;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)initialize;
+ (id)keyPathsForValuesAffectingFindString;
+ (id)keyPathsForValuesAffectingReplaceString;
+ (id)keyPathsForValuesAffectingFindRegularExpression;
+ (id)keyPathsForValuesAffectingFindAttributedString;
+ (id)keyPathsForValuesAffectingReplaceAttributedString;
+ (id)keyPathsForValuesAffectingReplaceExpression;
+ (id)keyPathsForValuesAffectingHasFindPattern;

/* instance methods */
- (id)initWithNibName:(id)name bundle:(id)bundle;
- (void)loadView;
- (void)viewDidInstall;
- (void)viewWillUninstall;
- (void)windowDidUpdate:(id)update;
- (void)_pushSharedFindPatternComponents;
- (void)_pushSharedReplacePatternComponents;
- (BOOL)validateUserInterfaceItem:(id)item;
- (void)sanitizeStrings;
- (void)updateRecentsMenu;
- (void)setFindPatternComponents:(id)components andUpdate:(BOOL)update;
- (void)setFindPatternComponentsAndUpdate:(id)update;
- (void)wasAssociatedWithScopeBarController:(id)controller;
- (void)setFindAttributedString:(id)string andUpdate:(BOOL)update;
- (void)setFindAttributedStringAndUpdate:(id)update;
- (void)selectFindField:(id)field;
- (void)selectReplaceField:(id)field;
- (void)findNext:(id)next;
- (void)findPrevious:(id)previous;
- (void)replace:(id)replace;
- (void)replaceAndFindNext:(id)next;
- (void)replaceAndFindPrevious:(id)previous;
- (void)replaceAll:(id)all;
- (void)replaceAllInSelection:(id)selection;
- (void)changeFinderMode:(id)mode;
- (void)_updateAfterInvalidate:(id)invalidate;
- (double)invalidationDelayInterval;
- (void)invalidateResultsAndUpdate:(BOOL)update;
- (void)invalidateResults;
- (void)updateStatusInformingDelegate:(BOOL)delegate;
- (void)clearResults;
- (void)performFindHighlightingFirstResult:(BOOL)result informDelegate:(BOOL)delegate;
- (BOOL)supportsFindBarType:(unsigned long long)type;
- (BOOL)supportsFindBarMode:(unsigned long long)mode;
- (BOOL)supportsTextMatchStyle:(unsigned long long)style;
- (BOOL)supportsCaseInsensitiveMatch;
- (void)_optionsChanged:(id)changed;
- (void)_insertFindPattern:(id)pattern;
- (void)cancel:(id)cancel;
- (void)_findStringFieldAction:(id)action;
- (void)_replaceStringFieldAction:(id)action;
- (void)_segmentedControlAction:(id)action;
- (void)_replaceAllInSelectionButtonAction:(id)action;
- (void)_dismiss:(id)_dismiss;
- (void)_replaceSegmentedControlClicked:(id)clicked;
- (void)_restoreFindHistory:(id)history;
- (void)_clearRecents;
- (void)_showFindOptionsPopover:(id)popover;
- (id)_recentsMenu;
- (BOOL)supportsPatterns;
- (id)_findField;
- (id)_replaceField;
- (id)findFieldForField:(id)field;
- (id)replaceFieldForField:(id)field;
- (BOOL)hasFindPattern;
- (void)controlTextDidChange:(id)change;
- (void)findBarLostFocus;
- (void)_endedEditing:(id)editing;
- (void)controlTextDidEndEditing:(id)editing;
- (void)didPressDismissOnScopeBar:(id)bar;
- (BOOL)control:(id)control textView:(id)view doCommandBySelector:(SEL)selector;
- (void)primitiveInvalidate;
@end

#endif /* DVTFindBar_h */
