//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
//


@class DVTFoldingManager, NSArray;
@protocol DVTObjectLiteralMediaResourceProvider;

@protocol DVTFoldingManagerDelegate <NSObject>
- (void)foldingManager:(DVTFoldingManager *)arg1 didUnfoldRange:(struct _NSRange)arg2;
- (void)foldingManager:(DVTFoldingManager *)arg1 didFoldRange:(struct _NSRange)arg2;

@optional
- (id <DVTObjectLiteralMediaResourceProvider>)mediaResourceProviderForLiteralInFoldingManager:(DVTFoldingManager *)arg1;
- (NSArray *)directoriesForLiteralInFoldingManager:(DVTFoldingManager *)arg1;
@end

