//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTFilterExpressionController_h
#define DVTFilterExpressionController_h
#import <Foundation/Foundation.h>

#include "DVTFilterExpressionHighlightFragmentProvider-Protocol.h"
#include "DVTFilteredDataSource-Protocol.h"
#include "DVTFilteredDataViewingContext-Protocol.h"
#include "DVTInvalidation-Protocol.h"
#include "_DVTFilterSession.h"

@class DVTStackBacktrace, NSSet, NSString;

@interface DVTFilterExpressionController : NSObject<DVTInvalidation> {
  /* instance variables */
  NSSet *_matches;
}

@property (retain) _DVTFilterSession *currentFilterSession;
@property (retain) NSObject<DVTFilteredDataViewingContext> *viewingContext;
@property (retain) NSObject<DVTFilterExpressionHighlightFragmentProvider> *presentationDelegate;
@property (readonly) NSObject<DVTFilteredDataSource> *filteredDataSource;
@property (readonly) long long filterProgress;
@property (readonly, nonatomic) BOOL valid;
@property (readonly) DVTStackBacktrace *invalidationBacktrace;
@property (retain) DVTStackBacktrace *creationBacktrace;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)initialize;
+ (id)filterExpressionControlllerWithDataSource:(id)source presentationDelegate:(id)delegate viewingContext:(id)context;
+ (id)keyPathsForValuesAffectingFilterProgress;

/* instance methods */
- (id)initWithFilteredDataSource:(id)source presentationDelegate:(id)delegate viewingContext:(id)context;
- (void)primitiveInvalidate;
- (void)_endCurrentFilterSession;
- (void)filterExpressionDidUpdate:(id)update;
- (void)_setMatches:(id)matches forFilterSession:(id)session;
- (void)_clearFilter;
- (void)setHighlightFragmentsForExpression:(id)expression;
@end

#endif /* DVTFilterExpressionController_h */
