//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTFoldingManagerDelegate_Protocol_h
#define DVTFoldingManagerDelegate_Protocol_h
#import <Foundation/Foundation.h>

@protocol DVTFoldingManagerDelegate <NSObject>
/* instance methods */
- (void)foldingManager:(id)manager didFoldRange:(struct _NSRange)range;
- (void)foldingManager:(id)manager didUnfoldRange:(struct _NSRange)range;
@optional
/* instance methods */
- (id)directoriesForLiteralInFoldingManager:(id)manager;
- (id)mediaResourceProviderForLiteralInFoldingManager:(id)manager;
@end

#endif /* DVTFoldingManagerDelegate_Protocol_h */
