//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22506.0.0.0.0
//
#ifndef DVTFilteredDataViewingContext_Protocol_h
#define DVTFilteredDataViewingContext_Protocol_h
#import <Foundation/Foundation.h>

@protocol DVTFilteredDataViewingContext <NSObject>

@property (nonatomic, readonly) long long filterProgress;
@property (nonatomic, copy) NSArray *highlightFragments;

/* instance methods */
- (void)showMatches:(id)matches added:(id)added removed:(id)removed;
- (void)filteringEnded;
@end

#endif /* DVTFilteredDataViewingContext_Protocol_h */
