//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTFindBarOptionsCtrl_h
#define DVTFindBarOptionsCtrl_h
#import <Foundation/Foundation.h>

@class DVTStackView_AppKitAutolayout, NSPopover, NSString, NSView;

@interface DVTFindBarOptionsCtrl : NSObject<NSPopoverDelegate> {
  /* instance variables */
  BOOL _supportsRegex;
  BOOL _supportsWordMatching;
  BOOL _supportsCaseInsensitiveMatching;
  BOOL _invalidateAfterClose;
}

@property (weak) DVTStackView_AppKitAutolayout *stackView;
@property (weak) NSView *matchingStyleView;
@property (weak) NSView *hitsMustContainView;
@property (weak) NSView *matchCaseView;
@property (weak) NSView *wrapView;
@property (nonatomic) unsigned long long findType;
@property (nonatomic) BOOL findIgnoresCase;
@property (nonatomic) BOOL findWraps;
@property (nonatomic) unsigned long long matchStyle;
@property (weak) NSPopover *popover;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)safeCharacterSet;

/* instance methods */
- (id)initWithSupportForRegex:(BOOL)regex andSupportForWordMatching:(BOOL)matching supportsCaseInsensitiveMatching:(BOOL)matching;
- (void)loadView;
- (id)findDescriptorForFindPatternComponents:(id)components;
- (id)descriptionForDescriptor:(id)descriptor;
- (void)setOptionsFromFindDescriptor:(id)descriptor;
- (void)closePopoverAndInvalidate;
- (void)_removeFromSuperviewAndInvalidate;
- (void)popoverDidClose:(id)close;
@end

#endif /* DVTFindBarOptionsCtrl_h */
