//
//     Generated by class-dump 3.5-0.1.1 (64 bit) (forked by @manicmaniac).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
//


@class NSDictionary, NSMutableDictionary;

@protocol DVTPropertyListEncoding <NSObject>
- (void)encodeIntoPropertyList:(NSMutableDictionary *)arg1;
- (void)awakeFromPropertyList;
- (id)initWithPropertyList:(NSDictionary *)arg1 owner:(id)arg2;
@end

