//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTStringBuffer_h
#define DVTStringBuffer_h
#import <Foundation/Foundation.h>

@class NSString;

@interface DVTStringBuffer : NSObject {
  /* instance variables */
  unsigned long long bufferLen;
  unsigned long long bufferLoc;
  NSString *string;
  unsigned long long stringLen;
  unsigned long long stringLoc;
  unsigned short buffer[32];
  unsigned short curChar;
  unsigned short _unused;
}

/* instance methods */
@end

#endif /* DVTStringBuffer_h */
