//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTSDK_h
#define DVTSDK_h
#import <Foundation/Foundation.h>

#include "DVTBuildVersion.h"
#include "DVTFilePath.h"
#include "DVTPlatform.h"
#include "DVTSDKVariant.h"
#include "DVTSearchPath.h"

@class NSArray, NSDictionary, NSNumber, NSSet, NSString;

@interface DVTSDK : NSObject {
  /* instance variables */
  NSNumber *_isInternal;
  NSNumber *_isBaseSDK;
  DVTSearchPath *_commandLineToolSearchPath;
  NSArray *_headerSearchPaths;
  NSArray *_frameworkSearchPaths;
}

@property (retain) DVTPlatform *platform;
@property (retain) NSSet *aliases;
@property (readonly, copy) NSString *alternateSDKName;
@property (readonly, copy) NSArray *supportedBuildToolComponents;
@property (readonly, copy) NSArray *librarySearchPaths;
@property (readonly, copy) NSArray *libraryFilenameExtensions;
@property (readonly, copy) NSDictionary *infoDictionary;
@property (readonly, copy) NSString *propertyConditionName;
@property (readonly, copy) NSArray *propertyConditionFallbackNames;
@property (readonly, copy) NSString *minimalDisplayName;
@property (readonly, copy) NSString *canonicalName;
@property (readonly, copy) NSString *canonicalNameForBuildSettings;
@property (readonly, copy) NSString *displayName;
@property (readonly, copy) NSString *operatingSystemVersion;
@property (readonly) BOOL versionInfoIsRequired;
@property (readonly) NSDictionary *versionInfo;
@property (readonly) DVTBuildVersion *productBuildVersion;
@property (readonly) BOOL internal;
@property (readonly) BOOL baseSDK;
@property (readonly) BOOL isLatestCanonicalSDKForPlatform;
@property (readonly) NSString *canonicalNameForLookup;
@property (readonly, copy) DVTFilePath *sdkPath;
@property (readonly, copy) NSArray *toolchainNames;
@property (readonly, copy) NSArray *toolchains;
@property (readonly, copy) NSDictionary *defaultProperties;
@property (readonly, copy) NSDictionary *debuggerOptions;
@property (readonly) BOOL supportsDeveloperFrameworks;
@property (readonly) NSDictionary *variants;
@property (readonly) DVTSDKVariant *defaultVariant;
@property (readonly) NSDictionary *versionMap;
@property (readonly) NSDictionary *iOSToMacOSVersionMap;
@property (readonly) NSDictionary *macOSToiOSVersionMap;
@property (readonly) NSArray *cohortPlatformNames;

/* class methods */
+ (void)initialize;
+ (id)knownSDKs;
+ (void)_setSDK:(id)sdk forResolvedAbsolutePath:(id)path;
+ (id)_sdkForResolvedAbsolutePath:(id)path;
+ (void)_setSDK:(id)sdk forCanonicalName:(id)name;
+ (id)sdkForCanonicalName:(id)name;
+ (id)sdksForFamily:(id)family;
+ (id)_absolutePathForSDKPathString:(id)string;
+ (id)sdkForNameOrPath:(id)path withBasePath:(id)path forceCreate:(BOOL)create;
+ (id)sdkForUnsetSDKROOT;
+ (id)sdkForUnsetSDKROOTOrNil;
+ (id)sdkForPath:(id)path;
+ (id)sdkForPath:(id)path forceCreate:(BOOL)create;
+ (id)sdkInDirectory:(id)directory forPlatform:(id)platform;
+ (id)sdksInDirectory:(id)directory forPlatform:(id)platform;

/* instance methods */
- (id)initWithFilePath:(id)path infoDictionary:(id)dictionary;
- (id)initWithFilePath:(id)path;
- (BOOL)isEmbedded;
- (BOOL)isInternal;
- (BOOL)isBaseSDK;
- (id)additionalRuntimeEnvironmentVariablesPathForPlatform:(id)platform;
- (id)additionalRuntimeEnvironmentVariablesForPlatform:(id)platform;
- (id)_canonicalNameForLookupIncludingCohortInfix:(BOOL)infix;
- (id)commandLineToolSearchPath;
- (id)additionalHeaderSearchPaths;
- (id)additionalFrameworkSearchPaths;
- (id)additionalLibrarySearchPaths;
- (id)description;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
@end

#endif /* DVTSDK_h */
