//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef DVTSourceControlFingerprintManager_Protocol_h
#define DVTSourceControlFingerprintManager_Protocol_h
#import <Foundation/Foundation.h>

@protocol DVTSourceControlFingerprintManager <NSObject>
/* instance methods */
- (id)existingFingerprintForHost:(id)host;
- (id)existingFingerprintForHost:(id)host;
- (void)loadKnownHostsFromDictionary:(id)dictionary;
- (void)loadKnownHostsFromDictionary:(id)dictionary;
- (void)addKnownHost:(id)host fingerprint:(id)fingerprint;
- (id)existingFingerprintForRepository:(id)repository;
- (id)existingFingerprintForRepository:(id)repository;
@end

#endif /* DVTSourceControlFingerprintManager_Protocol_h */
