//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22020.0.0.0.0
//
#ifndef DVTSplitViewDelegate_Protocol_h
#define DVTSplitViewDelegate_Protocol_h
#import <Foundation/Foundation.h>

@protocol DVTSplitViewDelegate <NSSplitViewDelegate>
@optional
/* instance methods */
- (void)splitViewItemDidExpandOrCollapseBecauseUserDraggedDivider:(id)divider;
- (id)splitView:(id)view needsRectanglesForViewsWithState:(id)state forSize:(struct CGSize)size;
- (void)splitViewWillStartLiveResize:(id)resize;
- (void)splitViewDidEndLiveResize:(id)resize;
- (id)splitView:(id)view additionalEffectiveRectsOfDividerAtIndex:(long long)index;
@end

#endif /* DVTSplitViewDelegate_Protocol_h */
