//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22522.0.0.0.0
//
#ifndef DVTSourceExpressionSource_Protocol_h
#define DVTSourceExpressionSource_Protocol_h
#import <Foundation/Foundation.h>

@protocol DVTSourceExpressionSource <NSObject, DVTInvalidation>

@property (readonly, nonatomic) DVTSourceExpression *selectedExpression;
@property (readonly) DVTSourceExpression *contextMenuExpression;
@property (readonly, nonatomic) struct CGRect currentSelectionFrame;
@property (readonly, nonatomic) DVTSourceExpression *mouseOverExpression;
@property (readonly) DVTSourceExpression *quickHelpExpression;
@property (readonly) NSView *quickHelpTargetView;
@property (readonly, nonatomic) NSString *selectedText;
@property (readonly, nonatomic) DVTSourceLanguageService *languageService;
@property (readonly) DVTSDK *sdk;

/* instance methods */
- (struct CGRect)expressionFrameForExpression:(id)expression;
@end

#endif /* DVTSourceExpressionSource_Protocol_h */
