//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTSearchPath_h
#define DVTSearchPath_h
#import <Foundation/Foundation.h>

#include "DVTFilePath.h"

@class NSArray, NSString;

@interface DVTSearchPath : NSObject<NSCopying>

@property (readonly) NSString *unixShellSearchPathRepresentation;
@property (readonly) DVTFilePath *preferredDirectoryPath;
@property (readonly) NSArray *searchDirectoryFilePaths;

/* class methods */
+ (id)searchPathWithSearchDirectoryFilePaths:(id)paths;
+ (id)searchPathWithUnixShellSearchPathRepresentation:(id)representation;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)initWithSearchDirectoryFilePaths:(id)paths;
- (id)searchPathByAppendingSearchDirectoryFilePaths:(id)paths;
- (id)searchPathByAppendingSearchPath:(id)path;
- (id)pathForFileWithRelativePathString:(id)string matchingPredicate:(id /* block */)predicate;
- (id)pathForFileWithRelativePathString:(id)string;
- (id)description;
@end

#endif /* DVTSearchPath_h */
