//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTSourceTextViewDelegate_Protocol_h
#define DVTSourceTextViewDelegate_Protocol_h
#import <Foundation/Foundation.h>

@protocol DVTSourceTextViewDelegate <DVTCompletingTextViewDelegate>
@optional
/* instance methods */
- (void)textView:(id)view handleMouseDownInSidebar:(id)sidebar atLineNumber:(unsigned long long)number;
- (void)textView:(id)view handleMouseDidMoveOverSidebar:(id)sidebar atLineNumber:(unsigned long long)number;
- (void)textView:(id)view handleMouseDidExitSidebar:(id)sidebar;
- (BOOL)textView:(id)view shouldShowTemporaryLinkForCharacterAtIndex:(unsigned long long)index proposedRange:(struct _NSRange)range effectiveRanges:(id *)ranges;
- (void)textView:(id)view didClickOnTemporaryLinkAtCharacterIndex:(unsigned long long)index event:(id)event isAltEvent:(BOOL)event;
- (void)textViewWillChangeFolding:(id)folding;
- (void)textViewDidChangeFolding:(id)folding;
- (id)annotationContextForTextView:(id)view;
- (void)textView:(id)view didAddAnnotations:(id)annotations;
- (void)textView:(id)view didRemoveAnnotations:(id)annotations;
- (void)textViewDidLoadAnnotationProviders:(id)providers;
- (void)textViewDidFinishAnimatingScroll:(id)scroll;
- (void)tokenizableRangesWithRange:(struct _NSRange)range completionBlock:(id /* block */)block;
- (void)willStartTokenizedEditingWithRanges:(id)ranges;
- (void)didEndTokenizedEditingWithRanges:(id)ranges;
- (void)setupGutterContextMenuWithMenu:(id)menu;
- (void)textViewDidScroll:(id)scroll;
- (id)textViewWillReturnPrintJobTitle:(id)title;
- (void)textView:(id)view objectLiteralStringsForObjects:(id)objects completionBlock:(id /* block */)block;
- (BOOL)textView:(id)view shouldReadObjectLiteralFromPasteboard:(id)pasteboard type:(id)type;
- (id)directoriesForLiteralsInTextView:(id)view;
- (id)mediaResourceProviderInTextView:(id)view;
- (double)textView:(id)view constrainMinAccessoryAnnotationWidth:(double)width;
- (double)textView:(id)view constrainMaxAccessoryAnnotationWidth:(double)width;
- (double)textView:(id)view constrainAccessoryAnnotationWidth:(double)width;
@end

#endif /* DVTSourceTextViewDelegate_Protocol_h */
