//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTSearchFieldFlatCell_h
#define DVTSearchFieldFlatCell_h
#import <Foundation/Foundation.h>

@interface DVTSearchFieldFlatCell : NSSearchFieldCell
/* class methods */
+ (void)_drawBackgroundWithFrame:(struct CGRect)frame inView:(id)view;
+ (BOOL)_isKeyOrMainWindow:(id)window;
+ (id)_backgroundColor:(id)color;
+ (id)_innerShadowColor:(id)color forLineWidth:(double)width;
+ (double)_cornerRadius;
+ (id)_borderColor:(id)color;

/* instance methods */
- (void)drawWithFrame:(struct CGRect)frame inView:(id)view;
@end

#endif /* DVTSearchFieldFlatCell_h */
