//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22522.0.0.0.0
//
#ifndef DVTStatefulObject_Protocol_h
#define DVTStatefulObject_Protocol_h
#import <Foundation/Foundation.h>

@protocol DVTStatefulObject <NSObject>

@property (readonly) BOOL canRevertWithEmptyStateDictionary;
@property (readonly) BOOL canRevertStateBeforeLayout;

/* class methods */
+ (void)configureStateSavingObjectPersistenceByName:(id)name;
+ (long long)version;
/* instance methods */
- (id)stateToken;
- (void)setStateToken:(id)token;
- (void)revertStateWithDictionary:(id)dictionary;
- (void)commitStateToDictionary:(id)dictionary;
@end

#endif /* DVTStatefulObject_Protocol_h */
