//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTStructuredLayoutView_h
#define DVTStructuredLayoutView_h
#import <Foundation/Foundation.h>

#include "DVTStructuredLayoutView-Protocol.h"
#include "DVTStructuredLayoutViewState.h"

@interface DVTStructuredLayoutView : NSView<DVTStructuredLayoutView>

@property (readonly) DVTStructuredLayoutViewState *dvt_layoutState;

/* class methods */
+ (void)initialize;

/* instance methods */
- (void)DVTStructuredLayoutView_commonInit;
- (id)initWithFrame:(struct CGRect)frame;
- (id)initWithCoder:(id)coder;
@end

#endif /* DVTStructuredLayoutView_h */
