//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTSourceModelItem_h
#define DVTSourceModelItem_h
#import <Foundation/Foundation.h>

#include "DVTSourceModelItem.h"

@class NSMutableArray;

@interface DVTSourceModelItem : NSObject {
  /* instance variables */
  int _rc;
  unsigned int _nodeType :15 ;
  unsigned int _isOpaque :1 ;
  unsigned int _dirty :1 ;
  unsigned int _isBlock :1 ;
  unsigned int _ignoreToken :1 ;
  unsigned int _inheritsNodeType :1 ;
  unsigned int _isIdentifier :1 ;
  unsigned int _isSimpleToken :1 ;
  unsigned int _isVolatile :1 ;
  unsigned int _needToDirtyRightEdges :1 ;
}

@property long long langId;
@property long long token;
@property (retain, nonatomic) NSMutableArray *children;
@property struct _NSRange relativeLocation;
@property (nonatomic) DVTSourceModelItem *parent;
@property BOOL needsAdjustNodeType;

/* class methods */
+ (id)sourceModelItemWithRange:(struct _NSRange)range language:(long long)language token:(long long)token nodeType:(short)type;

/* instance methods */
- (id)initWithRange:(struct _NSRange)range language:(long long)language token:(long long)token nodeType:(short)type;
- (id)innerDescription:(id)description showSelf:(BOOL)self;
- (id)description;
- (id)diffableDescription;
- (id)simpleDescription;
- (id)contextArray;
- (id)dumpContext;
- (void)validate;
- (void)dirtyRelativeRange:(struct _NSRange)range changeInLength:(long long)length;
- (void)dirtyRange:(struct _NSRange)range changeInLength:(long long)length;
- (BOOL)isBlock;
- (void)setIsBlock:(BOOL)block;
- (long long)blockDepth;
- (id)enclosingBlock;
- (struct _NSRange)range;
- (void)setRange:(struct _NSRange)range;
- (void)offsetBy:(long long)by;
- (struct _NSRange)innerRange;
- (void)setNodeType:(short)type;
- (short)nodeType;
- (void)setIsOpaque:(BOOL)opaque;
- (BOOL)isOpaque;
- (short)rawNodeType;
- (BOOL)isIdentifier;
- (void)setDirty:(BOOL)dirty;
- (BOOL)dirty;
- (void)setIgnoreToken:(BOOL)token;
- (BOOL)ignoreToken;
- (void)setInheritsNodeType:(BOOL)type;
- (BOOL)inheritsNodeType;
- (void)setIsSimpleToken:(BOOL)token;
- (BOOL)isSimpleToken;
- (void)setNeedToDirtyRightEdges:(BOOL)edges;
- (BOOL)needToDirtyRightEdges;
- (void)setVolatile:(BOOL)volatileNot;
- (BOOL)isVolatile;
- (void)assignParents:(id)parents;
- (void)assignAllParents:(id)parents;
- (void)addChild:(id)child;
- (void)addChildren:(id)children;
- (void)addChildrenFromArray:(id)array inRange:(struct _NSRange)range;
- (unsigned long long)numberOfChildren;
- (unsigned long long)indexOfChildBeforeLocation:(unsigned long long)location;
- (unsigned long long)indexOfChildAfterLocation:(unsigned long long)location;
- (unsigned long long)indexOfChildAtLocation:(unsigned long long)location;
- (id)_childEnclosingLocation:(unsigned long long)location;
- (id)childEnclosingLocation:(unsigned long long)location;
- (id)childAdjoiningLocation:(unsigned long long)location;
- (BOOL)isAncestorOf:(id)of;
- (id)previousItem;
- (id)nextItem;
- (id)_firstLeafItem;
- (id)_lastLeafItem;
- (id)precedingItem;
- (id)followingItem;
- (long long)compare:(id)compare;
- (void)clearAdjustedNodeTypes;
- (void)enumerateIdentifierItemsInRelativeRange:(struct _NSRange)range usingBlock:(id /* block */)block;
@end

#endif /* DVTSourceModelItem_h */
