//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTSourceLanguageService_h
#define DVTSourceLanguageService_h
#import <Foundation/Foundation.h>

#include "DVTInvalidation-Protocol.h"
#include "DVTSourceLanguageServiceDelegate-Protocol.h"

@class DVTSourceCodeLanguage, DVTStackBacktrace, NSCharacterSet, NSString;

@interface DVTSourceLanguageService : NSObject<DVTInvalidation>

@property BOOL semanticsDisabled;
@property (readonly) DVTSourceCodeLanguage *language;
@property (nonatomic) NSObject<DVTSourceLanguageServiceDelegate> *delegate;
@property (copy) id /* block */ contentGenerationWaitingBlock;
@property (copy) id /* block */ contentGenerationCompletionBlock;
@property (readonly, copy) NSCharacterSet *autoCompleteChars;
@property long long status;
@property (readonly, nonatomic) BOOL valid;
@property (readonly) DVTStackBacktrace *invalidationBacktrace;
@property (retain) DVTStackBacktrace *creationBacktrace;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)sourceLanguageServiceForLanguage:(id)language withDelegate:(id)delegate;
+ (Class)sourceLanguageServiceClassForLanguage:(id)language;
+ (void)initialize;
+ (BOOL)supportsInvalidationPrevention;
+ (BOOL)canGenerateContentsForURL:(id)url;
+ (void)enumerateSupportedContextScopesForLanguage:(id)language block:(id /* block */)block;
+ (id)generatedURLForOriginalURL:(id)url;
+ (id)originalURLForGeneratedURL:(id)url;
+ (id)methodOrFunctionSourceLandmarkItemForSourceLandmarkItem:(id)item;

/* instance methods */
- (id)initWithLanguage:(id)language delegate:(id)delegate;
- (void)primitiveInvalidate;
- (void)observeValueForKeyPath:(id)path ofObject:(id)object change:(id)change context:(void *)context;
- (void)replaceCharactersInRange:(struct _NSRange)range withString:(id)string replacedString:(id)string affectedRange:(struct _NSRange *)range;
- (void)updateLineRange:(struct _NSRange)range changeInLength:(long long)length;
- (struct _NSRange)characterRangeForUSR:(id)usr;
- (id)symbolNameAtCharacterIndex:(unsigned long long)index nameRanges:(id *)ranges;
- (BOOL)shouldShowTemporaryLinkForCharacterAtIndex:(unsigned long long)index proposedRange:(struct _NSRange)range effectiveRanges:(id *)ranges;
- (BOOL)shouldAutoCompleteAtLocation:(unsigned long long)location autoCompleteCharacterSet:(id)set proposedAutoComplete:(BOOL)complete;
- (void)contextDidChange:(id)change;
- (struct _NSRange)rangeForInvalidateAttributesInRange:(struct _NSRange)range;
- (struct _NSRange)rangeOfWordAtIndex:(unsigned long long)index allowNonWords:(BOOL)words;
- (struct _NSRange)tokenizableRangeWithRange:(struct _NSRange)range;
- (struct _NSRange)methodOrFunctionRangeAtIndex:(unsigned long long)index;
- (struct _NSRange)methodCallRangeAtIndex:(unsigned long long)index;
- (struct _NSRange)methodDefinitionRangeAtIndex:(unsigned long long)index;
- (struct _NSRange)functionRangeAtIndex:(unsigned long long)index isDefinitionOrCall:(BOOL *)call;
- (struct _NSRange)functionOrMethodBodyRangeAtIndex:(unsigned long long)index;
- (void)doingBatchEdit:(BOOL)edit;
- (unsigned long long)locationOfPreviousMatchedDelimiterAtLocation:(unsigned long long)location;
- (unsigned long long)locationOfNextMatchedDelimiterAtLocation:(unsigned long long)location;
- (unsigned long long)indentOfBlockAtLocation:(unsigned long long)location;
- (struct _NSRange)foldableBlockRangeAtLocation:(unsigned long long)location;
- (id)foldableBlockRangesAtLocation:(unsigned long long)location;
- (id)foldableBlockInnerRangesInRange:(struct _NSRange)range;
- (struct _NSRange)foldableBlockRangeForLineAtLocation:(unsigned long long)location;
- (struct _NSRange)foldableBlockInnerRangeForLineAtLocation:(unsigned long long)location;
- (long long)foldableBlockDepthForLineAtLocation:(unsigned long long)location;
- (id)indentLineRange:(struct _NSRange)range effectiveLineRange:(struct _NSRange *)range;
- (id)lineCommentPrefixes;
- (id)blockCommentCircumfixes;
- (long long)commentCoverageInLineRange:(struct _NSRange)range;
- (id)stringByCommentingString:(id)string;
- (id)stringByUncommentingString:(id)string;
- (id)stringByTogglingCommentsInLineRange:(struct _NSRange)range;
- (void)contextJumpForTypeOverCompletionAtLocation:(unsigned long long)location withInsertionText:(id)text typeOverCompletions:(id)completions pendingTypeOverCompletion:(id)completion completionBlock:(id /* block */)block;
- (id)postProcessAutoInsertClosingBraceAtLocation:(unsigned long long)location;
- (struct _NSRange)suggestedExpressionSelectionRangeFromRange:(struct _NSRange)range;
- (id)expandPlaceholderInRange:(struct _NSRange)range suggestedText:(id)text effectiveRange:(struct _NSRange *)range;
- (long long)contextScopeAtLocation:(unsigned long long)location;
- (BOOL)isSemanticsDisabled;
@end

#endif /* DVTSourceLanguageService_h */
