//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTStructuredLayoutView_Protocol_h
#define DVTStructuredLayoutView_Protocol_h
#import <Foundation/Foundation.h>

#include "DVTStructuredLayoutViewState.h"

@protocol DVTStructuredLayoutView 

@property (readonly) DVTStructuredLayoutViewState *dvt_layoutState;

@optional
/* instance methods */
- (void)dvt_configureSubviewsBeforeSubviewLayout;
- (void)dvt_positionSubviewsAndSizeSelfAfterSubviewLayout;
- (void)dvt_willLayoutSubview:(id)subview atIndex:(long long)index;
- (void)dvt_didLayoutSubview:(id)subview atIndex:(long long)index;
- (void)dvt_didCompleteLayout;
- (void)dvt_invalidateLayout;
@end

#endif /* DVTStructuredLayoutView_Protocol_h */
