//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTScopeBarView_h
#define DVTScopeBarView_h
#import <Foundation/Foundation.h>

#include "DVTBorderedView.h"

@class NSMapTable, NSMutableArray, NSView;

@interface DVTScopeBarView : DVTBorderedView {
  /* instance variables */
  NSMapTable *_viewsToLeftSpacing;
  NSMutableArray *_viewsStuckToLeft;
  NSMutableArray *_viewsStuckToRight;
  NSView *_centeredView;
}

@property (nonatomic) BOOL usesAutoLayout;

/* class methods */
+ (id)createButton;
+ (id)createToggleButtonWithImage:(id)image alternateImage:(id)image;
+ (id)_createButtonOfType:(unsigned long long)type gradientStyle:(int)style;
+ (id)createButtonSeparator;

/* instance methods */
- (id)initWithFrame:(struct CGRect)frame;
- (id)initWithCoder:(id)coder;
- (void)_commonInit;
- (void)addSubview:(id)subview;
- (void)addViewOnLeft:(id)left;
- (void)addViewOnLeft:(id)left verticalAlignment:(int)alignment;
- (void)addViewOnLeft:(id)left verticalAlignment:(int)alignment withLeftPadding:(double)padding;
- (void)addViewOnRight:(id)right;
- (void)addViewOnRight:(id)right verticalAlignment:(int)alignment;
- (void)addViewOnRight:(id)right verticalAlignment:(int)alignment withLeftPadding:(double)padding;
- (void)addViewInCenter:(id)center;
- (id)viewsOnLeft;
- (id)viewsOnRight;
- (id)viewsInCenter;
- (void)removeView:(id)view;
- (void)willRemoveSubview:(id)subview;
- (void)_invalidateCenteredViewConstraints;
- (void)_addCenteredViewConstraints;
- (void)verticallyCenterView:(id)view;
@end

#endif /* DVTScopeBarView_h */
