//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTTextCompletionIssue_h
#define DVTTextCompletionIssue_h
#import <Foundation/Foundation.h>

@class NSString;

@interface DVTTextCompletionIssue : NSObject

@property (readonly) unsigned long long severity;
@property (readonly) NSString *text;
@property (readonly) BOOL shownInTableCell;

/* class methods */
+ (id)iconForSeverity:(unsigned long long)severity withWhiteBorder:(BOOL)border isEnabled:(BOOL)enabled;

/* instance methods */
- (id)initWithSeverity:(unsigned long long)severity text:(id)text;
- (id)initWithSeverity:(unsigned long long)severity text:(id)text shownInTableCell:(BOOL)cell;
- (unsigned long long)hash;
- (BOOL)isEqualToTextCompletionIssue:(id)issue;
- (BOOL)isEqual:(id)equal;
- (id)iconWithWhiteBorder:(BOOL)border isEnabled:(BOOL)enabled;
@end

#endif /* DVTTextCompletionIssue_h */
