//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTTextCompletionDataSource_h
#define DVTTextCompletionDataSource_h
#import <Foundation/Foundation.h>

#include "DVTInvalidation-Protocol.h"
#include "DVTTextCompletionDataSourceDelegate-Protocol.h"
#include "DVTTextCompletionStrategy.h"

@class DVTSourceCodeLanguage, DVTStackBacktrace, NSArray, NSMutableArray, NSMutableSet, NSObject, NSOperationQueue, NSString;

@interface DVTTextCompletionDataSource : NSObject<DVTInvalidation> {
  /* instance variables */
  NSMutableSet *_strategyObservers;
  NSOperationQueue *_completionsGeneratorQueue;
}

@property (retain, nonatomic) DVTSourceCodeLanguage *language;
@property (weak) NSObject<DVTTextCompletionDataSourceDelegate> *delegate;
@property (copy) NSArray *strategies;
@property (readonly, weak) DVTTextCompletionStrategy *lastDefinitiveStrategy;
@property (readonly) NSObject *lastCompletionsBackingStore;
@property (readonly, nonatomic) BOOL valid;
@property (readonly) DVTStackBacktrace *invalidationBacktrace;
@property (retain) DVTStackBacktrace *creationBacktrace;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)initialize;

/* instance methods */
- (id)init;
- (id)initWithLanguage:(id)language;
- (void)primitiveInvalidate;
- (void)generateCompletionsForDocumentLocation:(id)location context:(id)context completionBlock:(id /* block */)block;
- (id)cancellableCompletionResultsForDocumentLocation:(id)location filterText:(id)text expandedCompletionItems:(id)items context:(id)context priorityCoefficients:(id)coefficients completionBlock:(id /* block */)block;
@end

#endif /* DVTTextCompletionDataSource_h */
