//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTTextCompletionController_h
#define DVTTextCompletionController_h
#import <Foundation/Foundation.h>

#include "DVTCancellable-Protocol.h"
#include "DVTTextCompletionSession.h"
#include "DVTTextCompletionSupportingTextView-Protocol.h"

@class NSString;

@interface DVTTextCompletionController : NSObject {
  /* instance variables */
  NSString *_lastDismissingTextViewAction;
  NSString *_lastDismissingAppAction;
  NSObject<DVTCancellable> *_appActionsMonitor;
  id _eventMonitor;
  BOOL _registeredScrollListener;
}

@property (retain) DVTTextCompletionSession *currentSession;
@property (readonly) NSView<DVTTextCompletionSupportingTextView> *textView;
@property BOOL autoCompletionEnabled;
@property (readonly) BOOL sessionInProgress;
@property (readonly) BOOL showingCompletions;

/* class methods */
+ (id)completionUILogAspect;
+ (id)performanceLogAspect;

/* instance methods */
- (id)init;
- (id)initWithTextView:(id)view;
- (void)dealloc;
- (BOOL)isShowingCompletions;
- (BOOL)showCompletionsAtCursorLocation;
- (BOOL)_showCompletionsAtCursorLocationExplicitly:(BOOL)explicitly;
- (BOOL)acceptCurrentCompletion;
- (void)hideCompletions;
- (void)_hideCompletionsWithoutInvalidatingWithReason:(int)reason;
- (void)_dismissAndInvalidateCurrentSession;
- (void)textViewSelectionChanging;
- (void)_textViewTextDidChange:(id)change;
- (BOOL)textViewShouldInsertText:(id)text;
- (void)textViewDidInsertText;
- (void)_textViewWillUndoRedo:(id)redo;
- (void)_textViewDidScroll:(id)scroll;
- (BOOL)_dvtTextCompletionDebugContinueAfterLosingFocus;
- (BOOL)textViewShouldPerformAction:(SEL)action;
- (BOOL)textViewShouldChangeTextInRange:(struct _NSRange)range replacementString:(id)string;
- (BOOL)textViewShouldSetMarkedText:(id)text selectedRange:(struct _NSRange)range;
- (void)_applicationWillDispatchAction:(SEL)action;
- (BOOL)_textViewShouldHandleNextCompletion;
- (BOOL)_textViewShouldHandlePreviousCompletion;
- (BOOL)_textViewShouldHandleComplete;
- (BOOL)_textViewShouldHandleCancel;
- (BOOL)_textViewShouldInsertTab;
- (BOOL)showInfoPanelForSelectedCompletion;
- (id)debugStateString;
- (BOOL)isAutoCompletionEnabled;
@end

#endif /* DVTTextCompletionController_h */
