//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTTextPageGuideVisualization_h
#define DVTTextPageGuideVisualization_h
#import <Foundation/Foundation.h>

#include "DVTTextVisualization.h"

@class NSColor, DVTTextVisualization;

@interface DVTTextPageGuideVisualization : DVTTextVisualization {
  /* instance variables */
  double _pageGuideX;
  NSColor *_verticalLineColor;
  NSColor *_outOfBoundsColor;
}

@property (nonatomic) unsigned long long columnNumber;

/* class methods */
+ (unsigned long long)defaultDrawOrdering;

/* instance methods */
- (void)_updatePageGuideXCoordinate;
- (void)fontAndColorThemeChanged;
- (id)_pageGuideColor;
- (void)drawUnderCurrentLineHighlightInRect:(struct CGRect)rect;
- (void)drawUnderTextInRect:(struct CGRect)rect;
@end

#endif /* DVTTextPageGuideVisualization_h */
