//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
//


@class NSColor;

@protocol DVTTextFieldFocusable <NSObject>
@property(readonly) BOOL hasActiveFilter;
@property(readonly) BOOL hasKeyboardFocus;

@optional
@property(readonly) NSColor *explicitBackgroundColor;
@end

