//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTTextAnnotationTheme_h
#define DVTTextAnnotationTheme_h
#import <Foundation/Foundation.h>

#include "DVTTextAnnotationTheme.h"

@class NSColor, NSGradient;

@interface DVTTextAnnotationTheme : NSObject

@property (retain, nonatomic) DVTTextAnnotationTheme *darkVariant;
@property (retain) NSColor *highlightedRangeBorderColor;
@property (readonly) NSColor *borderTopColor;
@property (readonly) NSColor *borderBottomColor;
@property (readonly) NSColor *highlightColor;
@property (readonly) NSGradient *overlayGradient;
@property (readonly) NSGradient *overlayTintedGradient;
@property (readonly) NSColor *messageBubbleBorderColor;
@property (readonly) NSGradient *messageBubbleGradient;
@property (readonly) NSColor *messageBubbleFillColor;
@property (readonly) NSColor *caretColor;
@property (readonly) NSColor *textColor;

/* class methods */
+ (BOOL)hasDarkBackground;
+ (id)redTextAnnotationBaseHighlightColor;
+ (id)greenTextAnnotationBaseHighlightColor;
+ (id)_caretColor;
+ (id)defaultTheme;
+ (id)yellowGlassTextAnnotationThemeForVariant:(long long)variant;
+ (id)redGlassTextAnnotationThemeForVariant:(long long)variant;
+ (id)greenGlassTextAnnotationThemeForVariant:(long long)variant;
+ (id)blueGlassTextAnnotationThemeForVariant:(long long)variant;
+ (id)purpleGlassTextAnnotationThemeForVariant:(long long)variant;
+ (id)burgundyGlassTextAnnotationThemeForVariant:(long long)variant;
+ (id)grayGlassTextAnnotationThemeForVariant:(long long)variant;
+ (void)_createThemeVariants:(id *)variants faded:(id *)faded dimmed:(id *)dimmed highlightColor:(id)color bubbleColor:(id)color darkBubbleColor:(id)color;
+ (id)_themeForVariant:(long long)variant normal:(id)normal faded:(id)faded dimmed:(id)dimmed;
+ (id)defaultOverlayGlassGradient;
+ (id)defaultOverlayTintedGlassGradient;

/* instance methods */
- (id)_nonRecursiveCopyWithLineHighlightColorAlphaMultipliedBy:(double)by;
- (id)copyWithLineHighlightColorAlphaMultipliedBy:(double)by;
- (id)initWithHighlightColor:(id)color borderTopColor:(id)color borderBottomColor:(id)color overlayGradient:(id)gradient overlayTintedGradient:(id)gradient messageBubbleBorderColor:(id)color messageBubbleGradient:(id)gradient caretColor:(id)color highlightedRangeBorderColor:(id)color;
- (id)initWithHighlightColor:(id)color messageBubbleColor:(id)color caretColor:(id)color;
- (id)_calculateTextColor;
@end

#endif /* DVTTextAnnotationTheme_h */
