//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTTextView_h
#define DVTTextView_h
#import <Foundation/Foundation.h>

@interface DVTTextView : NSTextView {
  /* instance variables */
  BOOL _settingMinSizeForClipView;
}

@property BOOL minWidthTracksClipView;
@property BOOL minHeightTracksClipView;

/* instance methods */
- (id)initWithFrame:(struct CGRect)frame textContainer:(id)container;
- (id)initWithCoder:(id)coder;
- (void)_superviewClipViewFrameChanged:(id)changed;
- (void)setMinSize:(struct CGSize)size;
@end

#endif /* DVTTextView_h */
