//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22540.0.0.0.0
//
#ifndef DVTWrapperView_h
#define DVTWrapperView_h
#import <Foundation/Foundation.h>

#include "DVTLayoutView_ML.h"
#include "DVTInvalidation-Protocol.h"

@class DVTStackBacktrace, NSArray, NSString, NSView;

@interface DVTWrapperView : DVTLayoutView_ML<DVTInvalidation> {
  /* instance variables */
  struct CGSize _minContentFrameSize;
  struct CGSize _maxContentFrameSize;
  BOOL _isPadding;
  BOOL _allowAddSubview;
  BOOL _readyToObserveSubviewFrameChanges;
  NSArray *_currentContentViewConstraints;
  DVTStackBacktrace *_setFrameSizeBacktrace;
  NSString *_frameSizeDimentionIsNaN;
  BOOL _constraintsCameFromNib;
  NSString *_viewControllerClassName;
}

@property (retain) NSView *contentView;
@property (nonatomic) struct CGSize maximumContentViewFrameSize;
@property (nonatomic) struct CGSize minimumContentViewFrameSize;
@property (nonatomic) long long horizontalAlignmentWhenClipping;
@property (nonatomic) long long horizontalAlignmentWhenPadding;
@property (nonatomic) long long verticalAlignmentWhenClipping;
@property (nonatomic) long long verticalAlignmentWhenPadding;
@property (nonatomic) unsigned long long verticalContentViewResizingMode;
@property (nonatomic) unsigned long long horizontalContentViewResizingMode;
@property BOOL disablePaddingWarning;
@property long long visibility;
@property (readonly, nonatomic) BOOL valid;
@property (readonly) DVTStackBacktrace *invalidationBacktrace;
@property (retain) DVTStackBacktrace *creationBacktrace;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)initialize;
+ (BOOL)requiresConstraintBasedLayout;

/* instance methods */
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)frame;
- (void)invalidate;
- (void)primitiveInvalidate;
- (void)_setConstraintsIfNecessary;
- (void)updateConstraints;
- (BOOL)_requiresConstraintBasedLayout;
- (void)_syncContentViewTranslatesAutoresizingMaskIntoConstraintsValue;
- (void)setTranslatesAutoresizingMaskIntoConstraints:(BOOL)constraints;
- (void)setFrameSize:(struct CGSize)size;
- (void)layoutTopDown;
- (void)layoutBottomUp;
- (void)addSubview:(id)subview;
- (void)setSubviews:(id)subviews;
- (void)replaceSubview:(id)subview with:(id)with;
- (void)dvt_insertBackgroundVisualEffectView:(id)view;
- (struct CGSize)dvt_minimumSize;
- (void)didAddSubview:(id)subview;
- (void)willRemoveSubview:(id)subview;
- (BOOL)isAccessibilityElement;
- (id)accessibilityRole;
@end

#endif /* DVTWrapperView_h */
