//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEAssistantWindowController_h
#define IDEAssistantWindowController_h
#import <Foundation/Foundation.h>

#include "DVTCancellable-Protocol.h"
#include "IDEAssistant.h"
#include "IDEAssistantContext.h"

@class DVTBorderedView, DVTFilterControlBar, NSBox, NSButton, NSImageView, NSMutableArray, NSString, NSTextField, NSTouchBar, NSView, IDEAssistantContext;

@interface IDEAssistantWindowController : NSWindowController<NSTouchBarProvider, NSTouchBarDelegate> {
  /* instance variables */
  NSBox *_box;
  DVTBorderedView *_outerBorderedView;
  DVTBorderedView *_borderedView;
  DVTBorderedView *_sourceListBorderedView;
  NSButton *_nextButton;
  NSButton *_backButton;
  NSTextField *_titleField;
  DVTFilterControlBar *_filterControlBar;
  NSButton *_helpButton;
  NSImageView *_warningIconImageView;
  NSView *_warningContainerView;
  NSTextField *_warningLabel;
  IDEAssistant *_installedAssistant;
  id /* block */ _currentCompletionBlock;
  NSMutableArray *_assistantHistory;
  NSMutableArray *_allAnimations;
  NSView *_nextKeyView;
  NSObject<DVTCancellable> *_nextButtonKeyEquivalentObserver;
  double _lastAnimationDirection;
  BOOL _backtrackingFromOverlayAssistant;
  BOOL _closing;
}

@property (readonly) NSTouchBar *touchBar;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) IDEAssistant *currentAssistant;
@property (readonly, nonatomic) IDEAssistantContext *assistantContext;
@property (retain, nonatomic) NSString *nextButtonTitle;
@property (retain, nonatomic) NSString *finishButtonTitle;
@property (retain, nonatomic) NSMutableArray *completionPreprocessors;
@property (retain, nonatomic) NSMutableArray *completionPreprocessorExecutionStack;
@property (readonly) NSString *warningString;
@property (readonly) BOOL shouldHideWarningView;
@property (readonly) NSButton *cancelButton;
@property (readonly) NSButton *checkboxButton;

/* class methods */
+ (id)keyPathsForValuesAffectingOnFirstAssistant;
+ (id)keyPathsForValuesAffectingCanGoForwardOrFinish;
+ (id)keyPathsForValuesAffectingCanCancel;
+ (id)keyPathsForValuesAffectingForwardOrFinishButtonTitle;
+ (id)keyPathsForValuesAffectingAssistantTitle;
+ (id)keyPathsForValuesAffectingWarningString;
+ (id)keyPathsForValuesAffectingShouldHideWarningView;

/* instance methods */
- (id)makeTouchBar;
- (id)touchBar:(id)bar makeItemForIdentifier:(id)identifier;
- (id)_nextPreviousGroupItem;
- (id)_constraintForAlertTypeButton:(id)button;
- (id)_cancelItem;
- (id)_previousItem;
- (id)_nextItem;
- (void)setCurrentAssistant:(id)assistant andInstallView:(BOOL)view;
- (id)init;
- (void)windowDidLoad;
- (void)close;
- (id)assistantWithIdentifier:(id)identifier;
- (void)beginSessionWithAssistantIdentifier:(id)identifier context:(id)context completionBlock:(id /* block */)block;
- (void)beginSessionForWorkspaceWindow:(id)window;
- (void)endAssistantSessionWithResult:(int)result error:(id)error;
- (void)addGoForwardPreprocessor:(id /* block */)preprocessor;
- (void)drainPreprocessorOrContinueWithSender:(id)sender;
- (void)_clearAssistantHistoryStack;
- (void)_pushAssistantOntoHistoryStack:(id)stack;
- (id)_popAssistantHistoryStack;
- (id)_popAssistantHistoryStackToIdentifier:(id)identifier;
- (BOOL)onFirstAssistant;
- (BOOL)canGoBack;
- (BOOL)canGoForwardOrFinish;
- (BOOL)canCancel;
- (id)forwardOrFinishButtonTitle;
- (id)assistantTitle;
- (void)willInstallViewController:(id)controller;
- (void)didInstallViewController:(id)controller;
- (id)skipAheadIfPossibleAndReturnAssistantIdentifier;
- (void)addAnimationForKey:(id)key toView:(id)view;
- (void)goNextOrFinish:(id)finish;
- (void)_finishWithAction:(id)action;
- (void)goBack:(id)back;
- (void)cancelSession;
- (void)windowWillClose:(id)close;
- (void)helpAction:(id)action;
- (void)setupAccessoriesForAssistant:(id)assistant animated:(BOOL)animated;
- (void)configureAnimationImageViewWithDirection:(double)direction actionBlock:(id /* block */)block;
@end

#endif /* IDEAssistantWindowController_h */
