//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEAnalyzerResultsExplorer_h
#define IDEAnalyzerResultsExplorer_h
#import <Foundation/Foundation.h>

#include "DVTViewController.h"
#include "DVTMessageBubbleAnnotationDelegate-Protocol.h"
#include "DVTScopeBarContentController-Protocol.h"
#include "IDEAnalyzerResultsVisualization.h"

@class DVTNotificationToken, IDEActivityLogAnalyzerResultMessage, NSArray, NSArrayController, NSImageView, NSLayoutConstraint, NSMutableArray, NSPopUpButton, NSSegmentedControl, NSString, NSView, IDEEditor, IDEAnalyzerResultsVisualization;
@protocol IDEAnalyzerResultsHostingEditor;

@interface IDEAnalyzerResultsExplorer : DVTViewController<DVTScopeBarContentController, DVTMessageBubbleAnnotationDelegate> {
  /* instance variables */
  NSImageView *_iconImageView;
  NSPopUpButton *_stepsPopupButton;
  NSSegmentedControl *_navSegmentedControl;
  NSArrayController *_stepMessagesController;
  DVTNotificationToken *_stepsPoupButtonWillPopUpNotificationToken;
  NSMutableArray *_stepAnnotations;
}

@property (retain) IDEEditor<IDEAnalyzerResultsHostingEditor> *editor;
@property (retain) NSArray *eventStepMessages;
@property double preferredViewHeight;
@property (weak) NSView *containerView;
@property (weak) NSLayoutConstraint *containerViewHeight;
@property (weak) NSLayoutConstraint *forwardBackButtonHeight;
@property (weak) NSLayoutConstraint *doneButtonHeight;
@property (retain, nonatomic) IDEActivityLogAnalyzerResultMessage *analyzerMessage;
@property (retain) IDEAnalyzerResultsVisualization *stepsVisualization;
@property (nonatomic) long long currentStepIndex;
@property (readonly) BOOL canShowNextStep;
@property (readonly) BOOL canShowPreviousStep;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)initialize;
+ (id)keyPathsForValuesAffectingCanShowNextStep;
+ (id)keyPathsForValuesAffectingCanShowPreviousStep;

/* instance methods */
- (id)initWithEditor:(id)editor;
- (id)initUsingDefaultNib;
- (void)primitiveInvalidate;
- (void)loadView;
- (void)setCurrentStepWithStepConfiguration:(id)configuration;
- (void)wasAssociatedWithScopeBarController:(id)controller;
- (void)_clearAnnotations;
- (void)willBeDismissedAnimate:(BOOL)animate completionBlock:(id /* block */)block;
- (void)didPressDismissOnScopeBar:(id)bar;
- (void)cancelOperation:(id)operation;
- (void)showNextStep:(id)step;
- (void)showPreviousStep:(id)step;
- (void)segmentedNavButtonAction:(id)action;
- (BOOL)shouldMoveCursorForAnnotation:(id)annotation;
@end

#endif /* IDEAnalyzerResultsExplorer_h */
