//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEAbstractEditorBar_h
#define IDEAbstractEditorBar_h
#import <Foundation/Foundation.h>

#include "DVTStructuredLayoutView.h"
#include "DVTInvalidation-Protocol.h"
#include "IDEControlGroup.h"
#include "IDEEditorContext.h"

@class DVTBorderedView, DVTStackBacktrace, NSString, NSVisualEffectView;

@interface IDEAbstractEditorBar : DVTStructuredLayoutView<DVTInvalidation> {
  /* instance variables */
  BOOL _controlGroupExplicitlyInvalidated;
  unsigned long long _leftControlGroupVisibilityState;
  unsigned long long _rightControlGroupVisibilityState;
}

@property (retain) IDEEditorContext *editorContext;
@property (retain) IDEControlGroup *leftControlGroup;
@property (retain) IDEControlGroup *rightControlGroup;
@property (retain) DVTBorderedView *centerContentView;
@property (retain) NSVisualEffectView *backgroundView;
@property (nonatomic) BOOL drawsTopBorder;
@property (nonatomic) BOOL drawsBottomBorder;
@property (nonatomic) BOOL drawsLeftBorder;
@property (readonly, nonatomic) BOOL valid;
@property (readonly) DVTStackBacktrace *invalidationBacktrace;
@property (retain) DVTStackBacktrace *creationBacktrace;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)initialize;
+ (id)_createSeparator;
+ (id)_createSpacerViewWithWidth:(double)width;

/* instance methods */
- (void)_IDEAbstractEditorBarSharedInit;
- (id)initWithFrame:(struct CGRect)frame;
- (id)initWithCoder:(id)coder;
- (void)primitiveInvalidate;
- (void)viewWillDraw;
- (BOOL)wantsUpdateLayer;
- (id)_debugLeftControlGroupVisibilityString:(unsigned long long)string;
- (id)_debugRightControlGroupVisibilityString:(unsigned long long)string;
- (void)_rebuildLeftControlGroupWithVisibility:(unsigned long long)visibility;
- (void)_rebuildRightControlGroupWithVisibility:(unsigned long long)visibility;
- (void)invalidateControlGroups;
- (unsigned long long)rightControlGroupVisibility;
- (unsigned long long)leftControlGroupVisibility;
- (void)dvt_configureSubviewsBeforeSubviewLayout;
- (void)dvt_willLayoutSubview:(id)subview atIndex:(long long)index;
- (void)dvt_positionSubviewsAndSizeSelfAfterSubviewLayout;
- (id)dvt_subviewsOrderedForLayout;
- (BOOL)isAccessibilityElement;
- (id)accessibilityRole;
@end

#endif /* IDEAbstractEditorBar_h */
