//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEAssistant_h
#define IDEAssistant_h
#import <Foundation/Foundation.h>

#include "DVTViewController.h"
#include "IDEAssistantContext.h"

@class DVTFilterControlBar, NSString, NSView, IDEAssistantContext;

@interface IDEAssistant : DVTViewController

@property (retain) IDEAssistantContext *assistantContext;
@property (readonly) BOOL canGoForward;
@property (readonly) BOOL canGoBack;
@property (readonly) BOOL canFinish;
@property (readonly) BOOL canCancel;
@property (readonly) BOOL askAreYouSureBeforeCancel;
@property (readonly) BOOL alwaysShowFinish;
@property (readonly) BOOL showHelpButton;
@property (readonly) NSString *warningString;
@property (copy) NSString *nextAssistantIdentifier;
@property (copy) NSString *previousAssistantIdentifier;
@property (readonly, copy) NSString *assistantTitle;
@property (readonly) NSView *sourceListView;
@property (readonly) DVTFilterControlBar *filterControlBar;
@property (nonatomic) BOOL expandsAssistantView;
@property (nonatomic) BOOL widthResizable;
@property (nonatomic) BOOL preventGoNextOrFinish;

/* class methods */
+ (BOOL)wantsTransparentBackground;
+ (BOOL)wantsOverlayEffect;

/* instance methods */
- (id)initWithNibName:(id)name bundle:(id)bundle;
- (BOOL)canBecomeMainViewController;
- (void)finishWithCompletionBlock:(id /* block */)block;
- (id)finishButtonTitle;
- (void)willResignCurrentAssistantInAssistantWindowController:(id)controller;
- (void)willGoNextOrFinish;
- (void)helpAction;
- (void)primitiveInvalidate;
@end

#endif /* IDEAssistant_h */
