//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEArchiveSchemeAction_h
#define IDEArchiveSchemeAction_h
#import <Foundation/Foundation.h>

#include "IDESchemeAction.h"

@class NSString;

@interface IDEArchiveSchemeAction : IDESchemeAction {
  /* instance variables */
  NSString *_buildConfiguration;
}

@property BOOL revealArchiveInOrganizer;
@property (retain, nonatomic) NSString *exportOptionsPlistPath;
@property (retain, nonatomic) NSString *exportDestinationPath;
@property (copy) NSString *customArchiveName;
@property (readonly) NSString *defaultArchiveName;
@property (copy) NSString *packagerIdentifier;

/* class methods */
+ (id)keyPathsForValuesAffectingSubtitle;
+ (id)keyPathsForValuesAffectingDefaultArchiveName;

/* instance methods */
- (id)init;
- (void)_commonInit;
- (id)name;
- (id)subtitle;
- (BOOL)doesNonActionWork;
- (id)overridingMacrosForArchiveBuildWithSchemeName:(id)name workspaceArena:(id)arena;
- (id)archivingOperationGroupForExecutionEnvironment:(id)environment buildParameters:(id)parameters schemeActionRecord:(id)record buildOperationGroup:(id)group error:(id *)error actionCallbackBlock:(id /* block */)block;
- (id)initFromXMLUnarchiver:(id)xmlunarchiver archiveVersion:(float)version;
- (void)dvt_awakeFromXMLUnarchiver:(id)xmlunarchiver;
- (void)dvt_encodeAttributesWithXMLArchiver:(id)xmlarchiver version:(id)version;
- (void)dvt_encodeRelationshipsWithXMLArchiver:(id)xmlarchiver version:(id)version;
- (void)setBuildConfigurationFromUTF8String:(char *)string fromXMLUnarchiver:(id)xmlunarchiver;
- (void)setCustomArchiveNameFromUTF8String:(char *)string fromXMLUnarchiver:(id)xmlunarchiver;
- (void)setPackagerIdentifierFromUTF8String:(char *)string fromXMLUnarchiver:(id)xmlunarchiver;
- (void)setRevealArchiveInOrganizerFromUTF8String:(char *)string fromXMLUnarchiver:(id)xmlunarchiver;
- (void)setExportOptionsPlistPathUTF8String:(char *)string fromXMLUnarchiver:(id)xmlunarchiver;
- (void)setExportDestinationPathUTF8String:(char *)string fromXMLUnarchiver:(id)xmlunarchiver;
- (void)addArchivingStrategy:(id)strategy fromXMLUnarchiver:(id)xmlunarchiver;
- (id)buildConfiguration;
- (void)setBuildConfiguration:(id)configuration;
@end

#endif /* IDEArchiveSchemeAction_h */
