//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEAppChooserWindowController_h
#define IDEAppChooserWindowController_h
#import <Foundation/Foundation.h>

#include "DVTInvalidation-Protocol.h"
#include "IDEAppChooserModelObject.h"
#include "IDEAppChooserTableView.h"

@class DVTMutableOrderedDictionary, DVTSearchField, DVTStackBacktrace, IDERunDestination, IDEScheme, IDESchemeCommand, NSArray, NSArrayController, NSButton, NSIndexSet, NSLock, NSMutableArray, NSMutableSet, NSOrderedSet, NSProgressIndicator, NSString, NSWindow;
@protocol OS_dispatch_queue;

@interface IDEAppChooserWindowController : NSWindowController<DVTInvalidation, NSSearchFieldDelegate> {
  /* instance variables */
  NSLock *_foundAppsLock;
  id /* block */ _completionHandler;
  NSMutableArray *_sortedFoundApplications;
  NSMutableSet *_foundApplicationURLs;
  NSWindow *_parentWindow;
  NSWindow *_sheet;
  NSObject<OS_dispatch_queue> *_appChooserQueue;
  BOOL _haveFoundAtLeastOneUserAppOnDevice;
  BOOL _isBrowsingWithOpenPanel;
  BOOL _runDestinationIsMac;
}

@property (retain) NSArrayController *applicationsArrayController;
@property (retain, nonatomic) NSIndexSet *applicationsSelectionIndexes;
@property (weak) DVTSearchField *filterField;
@property (weak) IDEAppChooserTableView *tableView;
@property (weak) NSButton *runLaunchButton;
@property (weak) NSButton *cancelButton;
@property (weak) NSButton *browseButton;
@property (weak) NSProgressIndicator *progressIndicator;
@property (retain) IDEAppChooserModelObject *selectedApplicationModelObject;
@property (weak) IDERunDestination *runDestination;
@property (weak) IDEScheme *scheme;
@property (retain) IDESchemeCommand *schemeCommand;
@property (copy) NSArray *suggestedApps;
@property (retain, nonatomic) NSArray *installedApplications;
@property (retain, nonatomic) DVTMutableOrderedDictionary *orderedRecentsByURL;
@property (readonly) NSOrderedSet *recentApplicationItems;
@property (readonly) unsigned long long type;
@property (retain) NSArray *orderedChooserApplications;
@property (retain, nonatomic) NSString *filterString;
@property (readonly, nonatomic) BOOL valid;
@property (readonly) DVTStackBacktrace *invalidationBacktrace;
@property (retain) DVTStackBacktrace *creationBacktrace;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)initialize;

/* instance methods */
- (id)initWithChooserType:(unsigned long long)type;
- (void)beginSheetOnWindow:(id)window runDestination:(id)destination scheme:(id)scheme command:(id)command completion:(id /* block */)completion;
- (void)_updateOrderedChooserApplications;
- (void)_updateRecentApplicationsWithApp:(id)app;
- (void)_updateSuggestedAppsForTargetExtensionIfAppropriateForSchemeCommand:(id)command;
- (id)_getRecentApplicationsFromUserDefaults;
- (void)_findInstalledApplications;
- (void)_findUserApplicationsForDevice:(id)device;
- (void)_findSystemApplicationsForDevice:(id)device;
- (void)_findLaunchersForDevice:(id)device;
- (id)_sentinelApplicationsForDebuggingAppExtensionsOnDevice:(id)device;
- (id)_addApplicationsAndReturnUniqueURLs:(id)urls;
- (void)_findRecentAppsFromRecentItems:(id)items;
- (id)_attachToExistingBundleIDPathExtension;
- (id)_realBundleIDForModelObject:(id)object;
- (void)_applyFilesystemPropertiesIfPossibleToModelObject:(id)object;
- (id)_modelObjectFromApplication:(id)application;
- (id)_displayNameFromURL:(id)url;
- (id)_imageFromURL:(id)url;
- (id)_modelObjectFromURL:(id)url displayName:(id)name bundleID:(id)id;
- (id)_recentAppsKey;
- (id)_predicateFromFilterString:(id)string;
- (id)selectedRunnable;
- (BOOL)control:(id)control textView:(id)view doCommandBySelector:(SEL)selector;
- (void)runOrLaunch:(id)launch;
- (void)cancelAction:(id)action;
- (void)browseAction:(id)action;
- (void)windowDidLoad;
- (void)awakeFromNib;
- (void)primitiveInvalidate;
- (BOOL)tableView:(id)view isGroupRow:(long long)row;
- (id)tableView:(id)view viewForTableColumn:(id)column row:(long long)row;
- (BOOL)tableView:(id)view shouldSelectRow:(long long)row;
- (id)_localExecutableURLsFromDraggingInfo:(id)info;
- (unsigned long long)tableView:(id)view validateDrop:(id)drop proposedRow:(long long)row proposedDropOperation:(unsigned long long)operation;
- (BOOL)tableView:(id)view acceptDrop:(id)drop row:(long long)row dropOperation:(unsigned long long)operation;
@end

#endif /* IDEAppChooserWindowController_h */
