//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEAnalyzerResultsVisualization_h
#define IDEAnalyzerResultsVisualization_h
#import <Foundation/Foundation.h>

#include "DVTTextVisualization.h"
#include "IDEAnalyzerResultsExplorer.h"

@class NSArray, NSMapTable, NSView;

@interface IDEAnalyzerResultsVisualization : DVTTextVisualization {
  /* instance variables */
  NSMapTable *_controlFlowPathsByStep;
  struct CGRect _cachedBounds;
}

@property (weak) IDEAnalyzerResultsExplorer *explorer;
@property (weak) NSView *hostingView;
@property (readonly) NSArray *allControlFlowPaths;

/* instance methods */
- (id)initWithExplorer:(id)explorer;
- (void)refresh;
- (void)setOpacity:(double)opacity;
- (struct CGRect)bounds;
- (void)drawOverTextInRect:(struct CGRect)rect;
- (id)drawablesInRect:(struct CGRect)rect;
@end

#endif /* IDEAnalyzerResultsVisualization_h */
