//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEActivityReport_h
#define IDEActivityReport_h
#import <Foundation/Foundation.h>

#include "DVTInvalidation-Protocol.h"
#include "DVTProgressReporting-Protocol.h"

@class DVTStackBacktrace, DVTSystemActivityToken, NSArray, NSDictionary, NSString;

@interface IDEActivityReport : NSObject<DVTProgressReporting> {
  /* instance variables */
  DVTSystemActivityToken *_systemActivityToken;
}

@property (readonly) BOOL valid;
@property (readonly) NSDictionary *dictionaryRepresentation;
@property (retain) NSObject<DVTInvalidation> *observerOwner;
@property BOOL unfinished;
@property (retain) DVTStackBacktrace *creationBacktrace;
@property (copy, nonatomic) NSString *title;
@property (copy, nonatomic) NSArray *titleSegments;
@property (copy) NSString *completionSummaryString;
@property (copy) NSArray *completionSummaryStringSegments;
@property long long progress;
@property (copy) NSDictionary *completionNotificationUserInfo;
@property (readonly) double timestamp;
@property double displayPriority;
@property (readonly) BOOL completed;
@property (readonly) NSString *stringValue;
@property (readonly) NSArray *stringSegments;
@property unsigned long long fileIOPriority;
@property (readonly, copy) id /* block */ fileIOCoordinatorBlock;
@property (readonly) double fileIOThrottleFactor;
@property (readonly) BOOL paused;
@property (readonly) NSString *version;
@property (readonly) unsigned int options;
@property (readonly) BOOL cancelable;
@property (readonly) BOOL userRequested;
@property (readonly) BOOL schemeBased;
@property (readonly) BOOL hidesProgress;
@property (readonly) BOOL shouldDisplayImmediately;
@property (readonly) BOOL disableTitleAnimation;
@property (readonly) BOOL persistent;
@property (readonly) BOOL fileIOIntensive;
@property (readonly) BOOL userVisible;
@property (copy) id /* block */ userDidRequestCancellationHandlerBlock;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)keyPathsForValuesAffectingValid;
+ (id)_currentVersion;
+ (id)keyPathsForValuesAffectingCompleted;
+ (BOOL)automaticallyNotifiesObserversOfFileIOThrottleFactor;
+ (id)keyPathsForValuesAffectingPaused;

/* instance methods */
- (void)setTitle:(id)title subtitle:(id)subtitle titlePriority:(double)priority subtitlePriority:(double)priority;
- (void)invalidate;
- (BOOL)isValid;
- (void)setProgressAsNSNumber:(id)nsnumber;
- (id)_initWithTitle:(id)title titleSegments:(id)segments options:(unsigned int)options fileIOPriority:(unsigned long long)iopriority fileIOCoordinatorBlock:(id /* block */)block unarchived:(BOOL)unarchived version:(id)version;
- (id)initWithTitle:(id)title titleSegments:(id)segments options:(unsigned int)options fileIOPriority:(unsigned long long)iopriority fileIOCoordinatorBlock:(id /* block */)block;
- (id)initWithDictionaryRepresentation:(id)representation;
- (id)init;
- (void)dealloc;
- (BOOL)isCurrentVersion;
- (BOOL)isCompleted;
- (BOOL)isCancelable;
- (BOOL)isUserRequested;
- (BOOL)isSchemeBased;
- (BOOL)isPersistent;
- (BOOL)isFileIOIntensive;
- (BOOL)isUserVisible;
- (void)_setFileIOThrottleFactor:(double)factor;
- (void)finishReport;
- (BOOL)isUnfinished;
@end

#endif /* IDEActivityReport_h */
