//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEActivityLogObservableRecord_h
#define IDEActivityLogObservableRecord_h
#import <Foundation/Foundation.h>

#include "IDELogStoreObservable-Protocol.h"

@class DVTObservingToken, NSNumber, NSString;

@interface IDEActivityLogObservableRecord : NSObject

@property (retain) DVTObservingToken *recorderLogObservingToken;
@property (nonatomic) unsigned long long totalNumberOfTestFailures;
@property (nonatomic) unsigned long long totalNumberOfErrors;
@property (nonatomic) unsigned long long totalNumberOfWarnings;
@property (nonatomic) unsigned long long totalNumberOfAnalyzerResults;
@property (retain, nonatomic) NSNumber *totalCodeCoveragePercentage;
@property (retain) NSString *highLevelStatus;
@property (readonly) NSObject<IDELogStoreObservable> *observable;
@property (readonly) BOOL isRecording;

/* class methods */
+ (id)highLevelStatusForLogStoreObservable:(id)observable;
+ (id)keyPathsForValuesAffectingIsRecording;

/* instance methods */
- (id)initWithObservable:(id)observable;
- (void)tearDown;
- (id)description;
@end

#endif /* IDEActivityLogObservableRecord_h */
