//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22028.0.0.0.0
//
#ifndef IDEBoltIndexImportSession_h
#define IDEBoltIndexImportSession_h
#import <Foundation/Foundation.h>

#include "IDEBoltIndexDatabase.h"

@class IDEBoltIndexDatabase;

@interface IDEBoltIndexImportSession : NSObject<NSCopying>

@property (readonly, nonatomic) BOOL hasEnded;
@property (readonly, nonatomic) IDEBoltIndexDatabase *database;

/* instance methods */
- (id)initWithDatabase:(id)database;
- (BOOL)shouldIndexJob:(id)job;
- (void)addPendingIndexJob:(id)job;
- (void)removePendingIndexJob:(id)job;
- (void)endSession;
- (void)didEnd;
- (id)copyWithZone:(struct _NSZone *)zone;
@end

#endif /* IDEBoltIndexImportSession_h */
