//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEBuildIssueErrorAnnotation_h
#define IDEBuildIssueErrorAnnotation_h
#import <Foundation/Foundation.h>

#include "IDEBuildIssueAnnotation.h"

@interface IDEBuildIssueErrorAnnotation : IDEBuildIssueAnnotation
/* class methods */
+ (double)precedence;
+ (unsigned long long)severity;
+ (id)sidebarIcon;
+ (id)normalTheme;
+ (id)focusedTheme;
+ (id)editedTheme;
+ (unsigned long long)scrollbarMarkerType;

/* instance methods */
- (id)annotationDisplayName;
@end

#endif /* IDEBuildIssueErrorAnnotation_h */
