//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEBatchFindAbstractMatchResult_h
#define IDEBatchFindAbstractMatchResult_h
#import <Foundation/Foundation.h>

#include "IDEBatchFindAbstractResult.h"

@class NSString;

@interface IDEBatchFindAbstractMatchResult : IDEBatchFindAbstractResult

@property (readonly) NSString *contextText;
@property (readonly) struct _NSRange contextTextMatchingRange;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithDocumentLocation:(id)location contextText:(id)text contextTextMatchingRange:(struct _NSRange)range initialNumberOfLinesCalculator:(id /* block */)calculator parent:(id)parent queryIdentifier:(id)identifier resultIdentifier:(long long)identifier;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (BOOL)contributesToFileResultCount;
- (BOOL)contributesToResultCount;
- (BOOL)allowsSummarization;
- (BOOL)canHaveChildren;
- (id)textRepresentationForPasteboard;
- (BOOL)textIsFileName;
@end

#endif /* IDEBatchFindAbstractMatchResult_h */
