//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
//

#include "Shared.h"

#import "IDEBatchFindAbstractResult.h"

@interface IDEBatchFindRootResult : IDEBatchFindAbstractResult
{
}

- (BOOL)canHaveChildren;
- (id)initWithChildOrderingSelector:(SEL)arg1 queryIdentifier:(long long)arg2 resultIdentifier:(long long)arg3;

@end

