//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEBatchFindRootResult_h
#define IDEBatchFindRootResult_h
#import <Foundation/Foundation.h>

#include "IDEBatchFindAbstractResult.h"

@interface IDEBatchFindRootResult : IDEBatchFindAbstractResult
/* instance methods */
- (id)initWithChildOrderingSelector:(SEL)selector queryIdentifier:(id)identifier resultIdentifier:(long long)identifier;
- (BOOL)canHaveChildren;
@end

#endif /* IDEBatchFindRootResult_h */
