//
//     Generated by class-dump 3.5-0.1.1 (64 bit) (forked by @manicmaniac).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
//

#import "DVTInvalidation-Protocol.h"
#import "IDEIssueLogDataSource-Protocol.h"

@class DVTFilePath, IDESourcePackageReference, IDEWorkspace, NSArray, NSString;
@protocol IDEBlueprint, IDETestableProvider;

@protocol IDEBlueprintProvider <DVTInvalidation, NSObject, IDEIssueLogDataSource>
+ (NSArray *)availableSwiftVersions;
@property(readonly) IDEWorkspace *workspace;
@property(readonly) DVTFilePath *filePath;
@property(readonly) id <IDETestableProvider> testableProvider;
@property(readonly, copy) NSString *classPrefix;
@property(readonly, copy) NSString *organizationName;
@property(readonly, copy) NSString *name;
@property(readonly, copy) NSArray *blueprints;
- (id <IDEBlueprint>)blueprintForName:(NSString *)arg1;
- (id <IDEBlueprint>)blueprintForIdentifier:(NSString *)arg1;

@optional
@property(readonly) BOOL supportsSourceFolders;
@property(readonly) NSArray *sourcePackageReferences;
@property int buildSystemType;
@property(readonly) NSString *uniqueIdentifier;
- (void)addSourcePackageReference:(IDESourcePackageReference *)arg1;
@end

