//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEBatchFindQueryDelegate_Protocol_h
#define IDEBatchFindQueryDelegate_Protocol_h
#import <Foundation/Foundation.h>

@protocol IDEBatchFindQueryDelegate <NSObject>
/* instance methods */
- (void)findNavigatorQuery:(id)query progressUpdate:(long long)update;
- (void)findNavigatorQuery:(id)query isStalledOnFilePaths:(id)paths;
- (void)findNavigatorQueryDidComplete:(id)complete totalWork:(struct { long long x0; long long x1; })work duration:(double)duration;
- (void)findNavigatorQuery:(id)query didGenerateResults:(id)results;
- (void)findNavigatorQuery:(id)query didFinishGeneratingLazyChildrenOfResult:(id)result;
@end

#endif /* IDEBatchFindQueryDelegate_Protocol_h */
