//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEBatchFindAbstractResult_h
#define IDEBatchFindAbstractResult_h
#import <Foundation/Foundation.h>

#include "IDEBatchFindAbstractResult.h"

@class DVTDocumentLocation, NSNumber, NSString, NSUUID;

@interface IDEBatchFindAbstractResult : NSObject<NSSecureCoding> {
  /* instance variables */
  id _cachedIcon;
}

@property (readonly) DVTDocumentLocation *location;
@property (readonly) SEL childOrderingSelector;
@property (readonly) IDEBatchFindAbstractResult *parent;
@property (readonly) long long depth;
@property (readonly) NSUUID *queryIdentifier;
@property (readonly) long long resultIdentifier;
@property (readonly) BOOL isRoot;
@property (readonly) BOOL isTopLevel;
@property (readonly) NSString *text;
@property (readonly) NSString *contextualSuffix;
@property (readonly) struct _NSRange highlightedTextRange;
@property (readonly) NSNumber *initialSuggestedNumberOfLines;
@property (readonly) BOOL contributesToFileResultCount;
@property (readonly) BOOL contributesToResultCount;
@property (readonly) BOOL allowsSummarization;
@property (readonly) BOOL emphasizesTitle;
@property (readonly) BOOL canHaveChildren;
@property (readonly) BOOL textIsFileName;
@property (readonly) long long suggestedOrder;

/* class methods */
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (void)setHasDescendentQueryAttachedMembers:(BOOL)members;
- (BOOL)hasDescendentQueryAttachedMembers;
- (id)initWithDocumentLocation:(id)location text:(id)text highlightedTextRange:(struct _NSRange)range initialNumberOfLinesCalculator:(id /* block */)calculator parent:(id)parent suggestedOrder:(long long)order childOrderingSelector:(SEL)selector queryIdentifier:(id)identifier resultIdentifier:(long long)identifier;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)copyWithZone:(struct _NSZone *)zone;
- (long long)compareText:(id)text;
- (long long)compareDocumentLocations:(id)locations;
- (id)generateFindResult;
- (id)textRepresentationForPasteboard;
- (long long)compareSuggestedOrder:(id)order;
- (id)description;
@end

#endif /* IDEBatchFindAbstractResult_h */
