//
//     Generated by class-dump 3.5-0.1.1 (64 bit) (forked by @manicmaniac).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
//


@class IDEBreakpoint, NSArray;

@protocol IDEBreakpointDelegate <NSObject>

@optional
- (void)breakpointLocationsAdded:(NSArray *)arg1 removed:(NSArray *)arg2;
- (void)breakpointTextFilterablePropertyChanged:(IDEBreakpoint *)arg1;
- (void)breakpointNameChanged:(IDEBreakpoint *)arg1;
- (void)breakpointModificationChanged:(IDEBreakpoint *)arg1;
- (void)breakpointResolutionChanged:(IDEBreakpoint *)arg1;
- (BOOL)breakpointShouldBeActivated:(IDEBreakpoint *)arg1;
- (void)breakpointEnablementChanged:(IDEBreakpoint *)arg1;
@end

