//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEBatchFindFilePathPredicate_h
#define IDEBatchFindFilePathPredicate_h
#import <Foundation/Foundation.h>

#include "IDEBatchFindPlistCodable-Protocol.h"

@interface IDEBatchFindFilePathPredicate : NSObject<NSCopying, IDEBatchFindPlistCodable>
/* class methods */
+ (id)decodeFromPropertyListRepresentation:(id)representation;
+ (id)propertyListIdentifier;
+ (id)plistDecoder;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id /* block */)filterBoundToWorkspace:(id)workspace;
- (id)propertyListRepresentation;
- (id)description;
- (BOOL)isWorkspaceSpecific;
- (unsigned long long)hash;
- (BOOL)isEqualToFilePathPredicateWithIdenticalClass:(id)class;
- (BOOL)isEqualToFilePathPredicate:(id)predicate;
- (BOOL)isEqual:(id)equal;
@end

#endif /* IDEBatchFindFilePathPredicate_h */
