//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEBuildNoticeProviderBlueprintVariant_h
#define IDEBuildNoticeProviderBlueprintVariant_h
#import <Foundation/Foundation.h>

@class NSData, NSString;

@interface IDEBuildNoticeProviderBlueprintVariant : NSObject<NSCopying>

@property (readonly, copy) NSString *category;
@property (readonly, copy) NSData *identifier;

/* instance methods */
- (id)initWithCategory:(id)category identifier:(id)identifier;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)zone;
@end

#endif /* IDEBuildNoticeProviderBlueprintVariant_h */
