//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEBuildNoticeLogSection_Protocol_h
#define IDEBuildNoticeLogSection_Protocol_h
#import <Foundation/Foundation.h>

@class IDEBuildNoticeProviderBlueprintVariant, DVTDocumentLocation;

@protocol IDEBuildNoticeLogSection

@property (nonatomic, readonly) BOOL isRecording;
@property (nonatomic, readonly) BOOL isSealed;
@property (nonatomic, readonly) long long result;
@property (nonatomic, readonly) NSArray *subsections;
@property (nonatomic, readonly) NSArray *messages;
@property (nonatomic, readonly) DVTDocumentLocation *location;
@property (nonatomic, readonly) NSString *signature;
@property (nonatomic, readonly) IDEBuildNoticeProviderBlueprintVariant *blueprintVariant;
@property (nonatomic, readonly) NSString *uniqueIdentifier;

/* instance methods */
- (id)observeAddedSections:(id /* block */)sections;
- (id)observeSealedSections:(id /* block */)sections;
@end

#endif /* IDEBuildNoticeLogSection_Protocol_h */
