//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEControlGroup_h
#define IDEControlGroup_h
#import <Foundation/Foundation.h>

#include "DVTBorderedView.h"

@class NSArray, NSColor, NSMapTable;

@interface IDEControlGroup : DVTBorderedView {
  /* instance variables */
  NSMapTable *_controlViewToBorderSidesTable;
}

@property (copy) NSColor *innerInactiveBorderColor;
@property (readonly) NSArray *controlViews;
@property unsigned long long solidBorderSides;

/* instance methods */
- (unsigned long long)borderSidesForControlView:(id)view;
- (void)setBorderSides:(unsigned long long)sides forControlView:(id)view;
- (void)_propagateDrawingPropertiesToSubview:(id)subview;
- (void)layoutTopDown;
- (void)layoutBottomUp;
- (id)_borderedViewForControlView:(id)view;
- (void)_addControlView:(id)view isFirst:(BOOL)first;
- (void)addControlViewFirst:(id)first;
- (void)addControlViewLast:(id)last;
- (void)removeControlView:(id)view;
- (void)removeAllControlViews;
- (unsigned long long)numberOfControlViews;
- (void)controlViewDidResize:(id)resize;
- (void)drawRect:(struct CGRect)rect;
- (void)setAllInactiveBordersToColor:(id)color;
- (void)setBorderSides:(unsigned long long)sides;
- (void)setBackgroundColor:(id)color;
- (void)setBackgroundGradient:(id)gradient;
- (void)setInactiveBackgroundColor:(id)color;
- (void)setInactiveBackgroundGradient:(id)gradient;
@end

#endif /* IDEControlGroup_h */
