//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEConsoleItem_h
#define IDEConsoleItem_h
#import <Foundation/Foundation.h>

#include "DVTSimpleSerialization-Protocol.h"
#include "IDEConsoleItemLogData.h"

@class NSString;

@interface IDEConsoleItem : NSObject<DVTSimpleSerialization, NSSecureCoding>

@property int kind;
@property (readonly) unsigned long long adaptorType;
@property (readonly) NSString *content;
@property (readonly) BOOL input;
@property (readonly) BOOL output;
@property (readonly) BOOL log;
@property (readonly) BOOL prompt;
@property (readonly) BOOL outputRequestedByUser;
@property (readonly) BOOL error;
@property (readonly) double timestamp;
@property (readonly) IDEConsoleItemLogData *logData;

/* class methods */
+ (void)initialize;
+ (id)keyPathsForValuesAffectingInput;
+ (id)keyPathsForValuesAffectingOutput;
+ (id)keyPathsForValuesAffectingError;
+ (id)keyPathsForValuesAffectingOSLog;
+ (id)keyPathsForValuesAffectingPrompt;
+ (id)keyPathsForValuesAffectingRequestedByUser;
+ (BOOL)supportsSecureCoding;

/* instance methods */
- (id)initWithAdaptorType:(unsigned long long)type content:(id)content kind:(int)kind;
- (id)initWithAdaptorType:(unsigned long long)type content:(id)content kind:(int)kind timestamp:(double)timestamp logData:(id)data;
- (id)initWithAdaptorType:(unsigned long long)type message:(id)message timestamp:(double)timestamp metadata:(id)metadata launchParameters:(id)parameters deviceSupportPath:(id)path;
- (id)initWithAdaptorType:(unsigned long long)type osLogMessage:(id)message timestamp:(double)timestamp launchParameters:(id)parameters deviceSupportPath:(id)path;
- (id)_canonicalizeString:(id)string;
- (id)_filterConsoleOutputForRuntimeIssueData:(id)data forMessageType:(unsigned char)type andSubsystem:(id)subsystem;
- (id)_filterConsoleOutputForRuntimeIssueData:(id)data;
- (id)description;
- (BOOL)isInput;
- (BOOL)isOutput;
- (BOOL)isError;
- (BOOL)isLog;
- (BOOL)isPrompt;
- (BOOL)isOutputRequestedByUser;
- (id)itemAsSubitems;
- (id)dvt_initFromDeserializer:(id)deserializer;
- (void)dvt_writeToSerializer:(id)serializer;
- (id)initWithCoder:(id)coder;
- (void)encodeWithCoder:(id)coder;
@end

#endif /* IDEConsoleItem_h */
