//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22526.0.0.0.0
//
#ifndef IDECodeConvertableBlueprint_Protocol_h
#define IDECodeConvertableBlueprint_Protocol_h
#import <Foundation/Foundation.h>

@protocol IDECodeConvertableBlueprint <IDEBlueprint>
/* instance methods */
- (void)convertToUseClang;
- (void)convertToBuild64bitOnly;
- (void)convertToStandardArchitectures;
- (BOOL)canConvertToUseARC;
- (void)convertToUseARC;
- (void)convertToUseModernObjCSyntax;
- (BOOL)lastSwiftMigrationIsCurrent;
- (void)updateLastSwiftMigrationToCurrent;
- (void)resetLastSwiftMigration;
- (void)updateSwiftCompilerTo:(id)to;
@end

#endif /* IDECodeConvertableBlueprint_Protocol_h */
