//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDECodeModule_h
#define IDECodeModule_h
#import <Foundation/Foundation.h>

@class DVTFilePath, NSNumber, NSString;

@interface IDECodeModule : NSObject

@property (copy, nonatomic) DVTFilePath *filePath;
@property (readonly, nonatomic) NSString *name;
@property (readonly, nonatomic) NSString *frameworkNameIncludingExtension;
@property (copy, nonatomic) NSString *identifier;
@property (nonatomic) unsigned long long address;
@property (nonatomic) unsigned long long size;
@property (readonly, nonatomic) NSString *displayAddress;
@property (readonly, nonatomic) NSString *path;
@property (readonly, nonatomic) NSNumber *timestamp;
@property (nonatomic) BOOL isInBuiltProductDirectories;
@property (nonatomic) int debugSymbolsLoadState;
@property (readonly, nonatomic) BOOL readFromMemory;

/* class methods */
+ (id)logAspect;
+ (id)frameworkNameIncludingExtensionFromPath:(id)path;
+ (id)keyPathsForValuesAffectingName;
+ (id)keyPathsForValuesAffectingTimestamp;
+ (id)keyPathsForValuesAffectingPath;

/* instance methods */
- (id)init;
- (id)initWithIdentifier:(id)identifier pathString:(id)string;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
@end

#endif /* IDECodeModule_h */
