//
//     Generated by class-dump 3.5-0.1.1 (64 bit) (forked by @manicmaniac).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
//

@class IDEContainer, IDEWorkspace, NSOperationQueue, NSSet;

@protocol IDEContainerUnlockingDelegate
- (void)container:(IDEContainer *)arg1 attemptToUnlockItems:(NSSet *)arg2 workspace:(IDEWorkspace *)arg3 completionQueue:(NSOperationQueue *)arg4 completionBlock:(void (^)(BOOL, NSError *))arg5;
@end

