//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEContainerUnlockingDelegate_Protocol_h
#define IDEContainerUnlockingDelegate_Protocol_h
#import <Foundation/Foundation.h>

@protocol IDEContainerUnlockingDelegate 
/* instance methods */
- (void)container:(id)container attemptToUnlockItems:(id)items workspace:(id)workspace completionQueue:(id)queue completionBlock:(id /* block */)block;
@end

#endif /* IDEContainerUnlockingDelegate_Protocol_h */
