//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22522.0.0.0.0
//
#ifndef IDECodeCoverageMutating_Protocol_h
#define IDECodeCoverageMutating_Protocol_h
#import <Foundation/Foundation.h>

@protocol IDECodeCoverageProviding;

@protocol IDECodeCoverageMutating <IDECodeCoverageProviding>

@property (nonatomic) BOOL codeCoverageEnabled;
@property (nonatomic) BOOL onlyGenerateCoverageForSpecifiedTargets;
@property (nonatomic, readonly) NSArray *codeCoverageTargets;

/* instance methods */
- (BOOL)isCodeCoverageEnabled;
- (void)addCodeCoverageTarget:(id)target;
- (void)removeCodeCoverageTarget:(id)target;
@end

#endif /* IDECodeCoverageMutating_Protocol_h */
