//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEDebugSession_h
#define IDEDebugSession_h
#import <Foundation/Foundation.h>

#include "DVTInvalidation-Protocol.h"
#include "IDEBreakpointManager.h"
#include "IDEConsoleAdaptor.h"
#include "IDEDebugProcess.h"
#include "IDEDebugTopNavigableModel-Protocol.h"
#include "IDELaunchSession.h"
#include "IDERunOperationWorker.h"
#include "IDERuntimeIssueRecordProcessInfo.h"
#include "IDESchemeActionAnalytics-Protocol.h"
#include "XCTHDebugSession-Protocol.h"

@class DVTDispatchLock, DVTMutableOrderedDictionary, DVTObservingToken, DVTStackBacktrace, DVTTextDocumentLocation, DVTTimeSlicedMainThreadWorkQueue, NSArray, NSDate, NSDictionary, NSMapTable, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString;
@protocol DBGDebugSessionBreakpointLifeCycleDelegate;

@interface IDEDebugSession : NSObject<XCTHDebugSession, DVTInvalidation, IDESchemeActionAnalytics> {
  /* instance variables */
  NSMapTable *_breakpointsToTokenSets;
  NSMapTable *_locationsToTokenSets;
  NSMapTable *_watchpointsToTokenSets;
  NSMapTable *_breakpointsToIdentifiers;
  NSMapTable *_locationsToIdentifiers;
  NSMapTable *_watchpointsToIdentifiers;
  DVTDispatchLock *_breakpointsAndWatchpointsToIdentifiersLock;
  DVTTimeSlicedMainThreadWorkQueue *_breakpointIdentifierChangedQueue;
  NSMutableSet *_profileDataObservers;
  BOOL _touchedProfileDataObserversRegistration;
  struct __CFSet * _stackFramesForDisassembly;
  NSMutableDictionary *_threadNameForThreadIDDictionary;
  NSMutableDictionary *_qosValueForThreadIDDictionary;
  int _logFD;
  DVTObservingToken *_targetControlStateObservingToken;
  DVTObservingToken *_breakpontsActivationObservingToken;
  DVTObservingToken *_breakpointListObserverToken;
}

@property (readonly) long long state;
@property (retain) IDERunOperationWorker *debugLauncher;
@property int coalescedState;
@property unsigned long long CPUFirstIndicatorHigh;
@property unsigned long long CPUFirstIndicatorLow;
@property unsigned long long memoryAnonymousHigh;
@property unsigned long long memoryAnonymousLow;
@property unsigned long long memoryPhysicalFootprintHigh;
@property unsigned long long memoryPhysicalFootprintLow;
@property BOOL shouldPostStateChangedDistributedNotifications;
@property (retain) IDELaunchSession *launchSession;
@property BOOL syntheticDebugSession;
@property (readonly) BOOL hitFirstStop;
@property (retain, nonatomic) NSObject<IDEDebugTopNavigableModel> *topNavigableModel;
@property (retain, nonatomic) IDEDebugProcess *process;
@property (readonly, nonatomic) DVTTextDocumentLocation *instructionPointerLocation;
@property (copy) NSArray *instructionPointerLocations;
@property (copy, nonatomic) DVTTextDocumentLocation *instructionPointerLocationForDisassembly;
@property BOOL profilingSupported;
@property (readonly) IDEBreakpointManager *breakpointManager;
@property (retain, nonatomic) NSObject<DBGDebugSessionBreakpointLifeCycleDelegate> *breakpointLifeCycleDelegate;
@property BOOL shouldDetachForRequestStop;
@property BOOL shouldIgnoreKillSignals;
@property int lastObserversForGaugesState;
@property int memoryDebuggingState;
@property (retain) IDEConsoleAdaptor *debuggerConsoleAdaptor;
@property (retain) IDEConsoleAdaptor *targetConsoleAdaptor;
@property (retain) NSArray *activityStrings;
@property (copy) NSDictionary *slowLaunchInfo;
@property (readonly) NSArray *CPUFirstIndicators;
@property (copy) NSDictionary *CPUDistribution;
@property (readonly) DVTMutableOrderedDictionary *CPUUsagesForThreadDictionary;
@property (readonly) NSArray *prunedThreadIDsForCPUUsages;
@property (readonly) NSArray *memoryFirstIndicators;
@property (copy) NSDictionary *memoryDistribution;
@property (readonly) NSArray *memoryMeasurements;
@property (readonly) NSString *memoryProfilingDisabledMessage;
@property (readonly) NSArray *energyMeasurements;
@property (readonly) NSArray *CPUCapMeasurements;
@property (readonly) NSArray *CPUCapAverageMeasurements;
@property unsigned long long totalRunningTimeMicroSeconds;
@property (readonly) NSString *totalRunningTime;
@property (readonly) NSDate *loggingInitializedDate;
@property (readonly) BOOL isLoggingEnabled;
@property (readonly) NSString *noticeSourceID;
@property (readonly, nonatomic) IDERuntimeIssueRecordProcessInfo *runtimeIssueRecordProcessInfo;
@property (readonly, nonatomic) BOOL valid;
@property (readonly) DVTStackBacktrace *invalidationBacktrace;
@property (retain) DVTStackBacktrace *creationBacktrace;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) NSDictionary *analyticsDictionary;

/* class methods */
+ (void)initialize;
+ (id)keyPathsForValuesAffectingInstructionPointerLocation;
+ (id)keyPathsForValuesAffectingTotalRunningTime;
+ (unsigned long long)assertionBehaviorForKeyValueObservationsAtEndOfEvent;

/* instance methods */
- (void)processRuntimeIssueRecords:(id)records category:(long long)category;
- (void)_dvt_commonInit;
- (id)init;
- (id)initWithDebugLauncher:(id)launcher;
- (void)_handleProcessStateChanged;
- (void)_delayedSetState;
- (id)_descriptionStringForState:(int)state;
- (unsigned long long)identifierForWatchpoint:(id)watchpoint;
- (void)_addBreakpointObservers:(id)observers;
- (void)_removeBreakpointObservers:(id)observers;
- (void)_addLocationObservers:(id)observers;
- (void)_removeBreakpointLocationObservers:(id)observers;
- (void)_addWatchpointObservers:(id)observers;
- (void)_removeWatchpointObservers:(id)observers;
- (void)_handleBreakpointsListChanged:(id)changed;
- (void)_handleBreakpointsCreated:(id)created;
- (void)_handleBreakpointsDeleted:(id)deleted;
- (void)_handleBreakpointLocationChanges:(id)changes;
- (void)_handleBreakpointLocationsAdded:(id)added;
- (void)_handleBreakpointLocationsRemoved:(id)removed;
- (void)_handleBreakpointActivationChanged;
- (void)_handleBreakpointEnablementChanged:(id)changed;
- (void)_handleBreakpointNameChanged:(id)changed;
- (void)_handleBreakpointConditionChanged:(id)changed;
- (void)_handleBreakpointIgnoreCountChanged:(id)changed;
- (void)_handleBreakpointModificationDone:(id)done change:(id)change;
- (BOOL)_shouldCreateBreakpoint:(id)breakpoint;
- (void)_createBreakpointIfNeccessary:(id)neccessary;
- (void)_deletePreviousAndCreateBreakpointIfNeccessary:(id)neccessary;
- (BOOL)_isWatchpointValid:(id)valid;
- (BOOL)_isBreakpointValid:(id)valid;
- (void)_delayedDetermineResolvability:(id)resolvability;
- (void)_determineResolvability:(id)resolvability;
- (id)_breakpointFromContainer:(id)container forIdentifier:(unsigned long long)identifier;
- (id)breakpointForIdentifier:(unsigned long long)identifier;
- (unsigned long long)identifierForBreakpoint:(id)breakpoint;
- (void)setIdentifier:(unsigned long long)identifier forBreakpoint:(id)breakpoint;
- (id)breakpointLocationForIdentifier:(unsigned long long)identifier parentBreakpoint:(id)breakpoint;
- (unsigned long long)identifierForBreakpointLocation:(id)location;
- (void)setIdentifier:(unsigned long long)identifier forBreakpointLocation:(id)location parentBreakpoint:(id)breakpoint;
- (id)watchpointForIdentifier:(unsigned long long)identifier;
- (void)setIdentifier:(unsigned long long)identifier forWatchpoint:(id)watchpoint;
- (id)logFilename;
- (void)_initializeLogging;
- (void)logDebugString:(id)string;
- (void)logDebugStringWithTimestamp:(id)timestamp;
- (void)logDebugStringWithFormat:(id)format;
- (void)logDebugStringWithTimestampUsingFormat:(id)format;
- (void)requestStepIn;
- (void)requestStepOverLine;
- (void)requestStepOut;
- (void)requestStepIntoInstruction;
- (void)requestStepOverInstruction;
- (void)requestStepInSuspendOtherThreads;
- (void)requestStepOverSuspendOtherThreads;
- (void)requestPause;
- (void)requestContinue;
- (void)requestContinueToLocation:(id)location;
- (void)requestStop;
- (void)requestDetach;
- (void)requestFetchEvent;
- (void)requestUISnapshotRefresh;
- (void)simulateMetricPayloads;
- (BOOL)supportsUISnapshot;
- (void)simulateVehicularCrash;
- (void)requestStepIntoCallSymbol:(id)symbol atLocation:(id)location;
- (void)requestMovePCInStackFrame:(id)frame toLineNumber:(unsigned long long)number;
- (void)requestLoadSymbolsForStackFrameUUID:(id)uuid;
- (void)loadSymbolAtPath:(id)path;
- (BOOL)shouldRelinquishToDebugSession:(id)session error:(id *)error;
- (BOOL)shouldAcceptFromDebugSession:(id)session error:(id *)error;
- (void)executeDebuggerCommand:(id)command threadID:(unsigned long long)id stackFrameID:(unsigned long long)id;
- (void)evaluateExpression:(id)expression threadID:(unsigned long long)id stackFrameID:(unsigned long long)id queue:(id)queue completionHandler:(id /* block */)handler;
- (void)evaluateExpression:(id)expression threadID:(unsigned long long)id stackFrameID:(unsigned long long)id queue:(id)queue resultBlock:(id /* block */)block;
- (void)evaluateExpression:(id)expression threadID:(unsigned long long)id stackFrameID:(unsigned long long)id queue:(id)queue options:(id)options completionHandler:(id /* block */)handler;
- (void)evaluateExpression:(id)expression threadID:(unsigned long long)id stackFrameID:(unsigned long long)id queue:(id)queue options:(id)options resultBlock:(id /* block */)block;
- (BOOL)consoleShouldTrackInputHistory;
- (BOOL)canContinueToLocation:(id)location withinBlockAtRange:(struct _NSRange)range;
- (id)commandsExpectingExpressions;
- (void)requestLoadDylibAtPath:(id)path completionBlock:(id /* block */)block;
- (void)registerProfileDataObserver:(id)observer;
- (void)deregisterProfileDataObserver:(id)observer;
- (void)determineProfileDataObserversState;
- (BOOL)addStackFrameForDisassembly:(id)disassembly;
- (void)removeToBeInvalidatedStackFramesForDisassembly:(id)disassembly;
- (id)verifyStackFrameForDisassembly:(id)disassembly;
- (id)qualityOfServiceValueForThreadID:(id)id;
- (void)completeString:(id)string resultHandler:(id /* block */)handler;
- (void)printDescriptionOfDataValueToConsole:(id)console runAllThreads:(BOOL)threads completionHandler:(id /* block */)handler;
- (id)supportedDataValueFormatsForDataValue:(id)value;
- (void)forceRefreshPausedStates;
- (id)symbolicatedFramesFromUUIDsAndOffsets:(id)offsets markRecorded:(BOOL)recorded;
- (void)setValue:(id)value forGlobalVariable:(id)variable ofType:(id)type completionHandler:(id /* block */)handler queue:(id)queue;
- (void)showFetchVariablesActivityString;
- (void)hideFetchVariablesActivityString;
- (unsigned long long)_indexOfVariableActivityString;
- (void)_setLastValue:(id)value inGaugeValues:(id)values;
- (void)setCurrentCPUFirstIndicator:(id)indicator;
- (void)setCPUUsageThreadName:(id)name forThreadID:(id)id;
- (id)CPUUsageThreadNameForThreadID:(id)id;
- (void)setCurrentThreadsCPUUsage:(id)cpuusage;
- (void)setCurrentMemoryFirstIndicator:(id)indicator;
- (void)_updateMemoryMeasureDictionary:(id)dictionary firstEntry:(BOOL)entry key:(id)key highValue:(unsigned long long *)value highValueKey:(id)key lowValue:(unsigned long long *)value lowValueKey:(id)key;
- (void)setCurrentMemoryMeasurement:(id)measurement;
- (void)setCurrentEnergyMeasurement:(id)measurement;
- (void)setCurrentCPUCapMeasurement:(id)measurement;
- (void)setCurrentCPUCapAverageMeasurement:(id)measurement;
- (void)primitiveInvalidate;
- (BOOL)isSyntheticDebugSession;
- (BOOL)isProfilingSupported;
@end

#endif /* IDEDebugSession_h */
