//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEDFRDebugBar_h
#define IDEDFRDebugBar_h
#import <Foundation/Foundation.h>

#include "IDEViewController.h"

@class DVTBorderedView, NSArray, NSMapTable, NSString;

@interface IDEDFRDebugBar : IDEViewController {
  /* instance variables */
  DVTBorderedView *_containerView;
  NSString *_currentDefaultCategory;
  NSString *_currentCategory;
  NSString *_currentInstalledCategory;
  BOOL _viewIsUninstalling;
  NSMapTable *_contentProvidersToShownControlViews;
  NSMapTable *_contentProvidersToControlViewsObserverTokens;
}

@property (retain, nonatomic) NSArray *contentProviders;
@property (retain) id selectedModelObject;

/* class methods */
+ (struct CGSize)standardDebugBarButtonSize;
+ (id)standardDebugBarButtonWithImage:(id)image toolTip:(id)tip accessibilityDescription:(id)description;
+ (unsigned long long)assertionBehaviorAfterEndOfEventForSelector:(SEL)selector;

/* instance methods */
- (void)loadView;
- (void)toggleDebuggerVisibility:(id)visibility;
- (void)installContentProvidersForDefaultCategory;
- (void)installContentProvidersForCategory:(id)category;
- (void)installContentProvidersForNewDefaultCategory:(id)category;
- (void)tile;
- (void)viewDidInstall;
- (void)viewWillUninstall;
- (id)_contentProvidersForCategory:(id)category;
- (void)primitiveInvalidate;
@end

#endif /* IDEDFRDebugBar_h */
