//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEDebugAreaBorderedView_h
#define IDEDebugAreaBorderedView_h
#import <Foundation/Foundation.h>

#include "DVTBorderedView.h"

@class NSView;

@interface IDEDebugAreaBorderedView : DVTBorderedView {
  /* instance variables */
  NSView *_contentViewRef;
  BOOL _replacingContentViewDuringHiding;
}

/* instance methods */
- (void)viewDidHide;
- (void)viewDidUnhide;
- (void)_removeContentViewFromSubviews;
- (void)_restoreContentViewToSubviews;
- (void)setContentView:(id)view;
- (void)ensureContentViewIsInHierarchyDuringBlock:(id /* block */)block;
- (void)layoutTopDown;
@end

#endif /* IDEDebugAreaBorderedView_h */
