//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEDebuggerAreaContainer_h
#define IDEDebuggerAreaContainer_h
#import <Foundation/Foundation.h>

#include "DVTLayoutView_ML.h"
#include "IDEDFRDebugBar.h"
#include "IDEDebugAreaBorderedView.h"
#include "IDESafeAreaAwareContainer-Protocol.h"

@class DVTBorderedView, NSString;

@interface IDEDebuggerAreaContainer : DVTLayoutView_ML<IDESafeAreaAwareContainer>

@property (retain, nonatomic) DVTBorderedView *debuggerBarViewWhichMayOrMayNotBeASubview;
@property (retain, nonatomic) IDEDebugAreaBorderedView *debuggerAreaBorderedView;
@property (retain, nonatomic) IDEDFRDebugBar *dfrDebugBar;
@property (nonatomic) double safeAreaTopInset;
@property (nonatomic) double safeAreaBottomInset;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)awakeFromNib;
- (void)didInheritNewSafeAreaInsetsFromParent;
- (id)installedDebuggerBar;
- (void)dvt_configureSubviewsBeforeSubviewLayout;
- (void)dvt_positionSubviewsAndSizeSelfAfterSubviewLayout;
@end

#endif /* IDEDebuggerAreaContainer_h */
