//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEExecutionEnvironment_h
#define IDEExecutionEnvironment_h
#import <Foundation/Foundation.h>

#include "DVTInvalidation-Protocol.h"
#include "IDEActivityLogRecord.h"
#include "IDEActivityLogSection.h"
#include "IDEBreakpointManager.h"
#include "IDEBuildOperation.h"
#include "IDEClientTracking-Protocol.h"
#include "IDEExecutionTracker.h"
#include "IDEInMemoryLogStore.h"
#include "IDELaunchSession.h"
#include "IDELogStore.h"
#include "IDEWorkspace.h"
#include "IDEWorkspaceArena.h"

@class DVTObservingToken, DVTStackBacktrace, NSArray, NSCountedSet, NSMapTable, NSMutableArray, NSMutableOrderedSet, NSOperationQueue, NSSet, NSString;
@protocol IDEPreBuildSavingDelegate;

@interface IDEExecutionEnvironment : NSObject<DVTInvalidation> {
  /* instance variables */
  NSCountedSet *_activeBuildLogs;
  unsigned long long _disableSubmissionOfBuildOperationsCount;
  NSString *_disableBuildSubmissionsReason;
  unsigned long long _queueBuildOperationsCount;
  NSMapTable *_launchSessionStateObservationTokens;
  NSMapTable *_launchSessionRunnablePIDObservationTokens;
  IDELogStore *_logStore;
  IDEInMemoryLogStore *_interfaceBuilderLogStore;
  NSMapTable *_ibLogsByBuildable;
  BOOL _handlingLaunchSessionStateChange;
  BOOL _settingLaunchSession;
  BOOL _settingLaunchSessionForTabChange;
  DVTObservingToken *_currentDebugSessionObserverToken;
  DVTObservingToken *_currentTraceInferiorSessionObserverToken;
}

@property (nonatomic, readonly) NSArray *debugSessionsForRuntimeIssues;
@property (readonly, copy, ) NSMutableArray *mutableDebugSessions;
@property (readonly, copy, ) NSMutableArray *mutableExecutionTrackers;
@property (readonly, copy, ) NSMutableArray *mutableExecutionTrackersForDisplay;
@property (readonly, copy, ) NSMutableOrderedSet *mutableExecutedActionInvocationRecords;
@property (retain) IDEExecutionTracker *currentExecutionTracker;
@property (retain) NSMapTable *operationGroupSuboperationObserversByExecutionTracker;
@property (retain) NSOperationQueue *operationQueue;
@property (readonly) NSArray *queuedBuildOperationInfos;
@property (retain) IDEBuildOperation *currentBuildOperation;
@property (retain) IDEWorkspaceArena *workspaceArena;
@property (readonly, copy, ) NSMutableArray *mutableLaunchSessions;
@property (retain, nonatomic) IDELaunchSession *currentLaunchSession;
@property (readonly) IDEWorkspace *workspace;
@property (readonly, copy, ) NSArray *executionTrackers;
@property (readonly, copy, ) NSArray *executionTrackersForDisplay;
@property (readonly) NSArray *executionTrackersOfOperationsWithBuilds;
@property (readonly, copy, ) NSSet *executedActionInvocationRecords;
@property (retain) NSObject<IDEClientTracking> *clientTracker;
@property BOOL shouldImmediatelyCancelClientsOnClose;
@property (readonly) NSSet *queuedBuildOperations;
@property (readonly) BOOL hasQueuedBuildOperations;
@property (readonly) BOOL hasUserInitiatedBuildOperations;
@property (readonly) long long buildState;
@property (readonly) int currentBuildOperationServiceTier;
@property (readonly) BOOL canSubmitBuildOperations;
@property (readonly) long long lastBuildResult;
@property (readonly) IDEActivityLogRecord *latestBuildLogRecord;
@property (readonly) IDEActivityLogSection *latestCompleteBuildLog;
@property (readonly, copy) NSArray *logRecords;
@property (readonly) NSArray *interfaceBuilderLogs;
@property (readonly, copy, ) NSArray *launchSessions;
@property (readonly, copy, ) NSArray *debugSessions;
@property (retain, nonatomic) IDELaunchSession *selectedLaunchSession;
@property (readonly) IDEBreakpointManager *breakpointManager;
@property (copy) NSMapTable *productNamesToBuildableProductsMapping;
@property (copy) NSMapTable *productNameStemsToBuildableProductsMapping;
@property (copy) NSMapTable *productModuleNamesToBuildableProductsMapping;
@property (retain) NSObject<IDEPreBuildSavingDelegate> *preBuildSavingDelegate;
@property (readonly, nonatomic) BOOL valid;
@property (readonly) DVTStackBacktrace *invalidationBacktrace;
@property (retain) DVTStackBacktrace *creationBacktrace;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)keyPathsForValuesAffectingDebugSessionsForRuntimeIssues;
+ (void)initialize;
+ (unsigned long long)assertionBehaviorForKeyValueObservationsAtEndOfEvent;
+ (BOOL)automaticallyNotifiesObserversForCurrentExecutionTracker;
+ (id)keyPathsForValuesAffectingBreakpointManager;
+ (id)keyPathsForValuesAffectingLogRecords;
+ (id)keyPathsForValuesAffectingLatestBuildLogRecord;
+ (BOOL)automaticallyNotifiesObserversOfCurrentLaunchSession;

/* instance methods */
- (id)initWithWorkspaceArena:(id)arena;
- (void)_conditionallyLogToStdoutForSignal:(int)signal format:(id)format;
- (void)enumerateOperation:(id)operation usingBlock:(id /* block */)block;
- (void)_setupDebugSignalHandlers;
- (void)_setupDebugSessionsObservation;
- (void)primitiveInvalidate;
- (void)disableSubmissionOfBuildOperationsWithReason:(id)reason;
- (void)enableSubmissionOfBuildOperationsWithReason:(id)reason;
- (void)startQueuingBuildOperations;
- (void)stopQueuingBuildOperations;
- (void)_observeLaunchSessionForRunOperation:(id)operation;
- (void)_startOperationForTracker:(id)tracker commandName:(id)name operationIncludesBuild:(BOOL)build;
- (void)_addSuboperationObservationToken:(id)token forExecutionTracker:(id)tracker;
- (void)_startNextQueuedBuildOperationIfNecessary;
- (id)executeOperation:(id)operation withCommandName:(id)name serviceTier:(int)tier invocationRecord:(id)record terminationSignpost:(id /* block */)signpost error:(id *)error;
- (id)executeOperation:(id)operation withCommandName:(id)name serviceTier:(int)tier invocationRecord:(id)record terminationSignpost:(id /* block */)signpost suppressingErrorPresentation:(BOOL)presentation error:(id *)error;
- (void)_storeLogForOperation:(id)operation;
- (void)promoteXPCExecutionTrackerForDisplay:(id)display;
- (void)_setSelectedLaunchSessionForTabChange:(id)change;
- (void)_noteLaunchSessionOutputStateChanged:(id)changed;
- (void)_setStatusDisplayNamesForExecutionTracker;
- (void)_setStatusDisplayNameForLaunchSession:(id)session;
- (void)_removeSameLaunchSessionsFor:(id)forNot;
- (void)_handleLaunchSessionStarted:(id)started;
- (void)_handleLaunchSessionExpired:(id)expired;
- (void)_handleLaunchSession:(id)session stateChange:(id)change;
- (void)_addMissingErrorForFailedBuildToRecorder:(id)recorder buildLog:(id)log;
- (void)_completeBuildOperation:(id)operation andPostLastBuildCompleted:(BOOL)completed andPostLastUserInitiatedBuildCompleted:(BOOL)completed;
- (void)observeValueForKeyPath:(id)path ofObject:(id)object change:(id)change context:(void *)context;
- (void)_setLocalizedResultStringForBuildLog:(id)log usingBuildOperationProvider:(id)provider buildAction:(id)action;
- (id)queuedBuildOperationsDescription;
@end

#endif /* IDEExecutionEnvironment_h */
