//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEEditorBatchFindDisplayProperties_h
#define IDEEditorBatchFindDisplayProperties_h
#import <Foundation/Foundation.h>

@class IDEBatchFindQuerySpecification, NSArray;

@interface IDEEditorBatchFindDisplayProperties : NSObject

@property (copy) NSArray *matchLocations;
@property (retain) IDEBatchFindQuerySpecification *querySpecification;
@property long long selectedMatchIndex;

/* instance methods */
@end

#endif /* IDEEditorBatchFindDisplayProperties_h */
