//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
//

@class DVTIcon, IDEEditor, IDEEditorHistoryController;
@protocol IDEEditorHistoryControllerItem;

@protocol IDEEditorHistoryControllerDelegate
- (BOOL)historyControllerOpenEmptyEditor:(IDEEditorHistoryController *)arg1;
- (BOOL)historyController:(IDEEditorHistoryController *)arg1 isItemResolvable:(id <IDEEditorHistoryControllerItem>)arg2;
- (void)historyController:(IDEEditorHistoryController *)arg1 goToItem:(id <IDEEditorHistoryControllerItem>)arg2;
- (id <IDEEditorHistoryControllerItem>)currentHistoryItem;
- (DVTIcon *)historyController:(IDEEditorHistoryController *)arg1 menuIconForItem:(id <IDEEditorHistoryControllerItem>)arg2;
@property(nonatomic, readonly) IDEEditor *editor;
@end

