//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEEditorArea_h
#define IDEEditorArea_h
#import <Foundation/Foundation.h>

#include "IDEViewController.h"
#include "DVTCancellable-Protocol.h"
#include "DVTSplitViewDelegate-Protocol.h"
#include "IDEBottomBarContextProvider-Protocol.h"
#include "IDEDFRDebugBar.h"
#include "IDEDebugArea.h"
#include "IDEDebugAreaBorderedView.h"
#include "IDEDebugBar.h"
#include "IDEDebuggerAreaContainer.h"
#include "IDEEditorAreaContainer.h"
#include "IDEEditorAreaSplit.h"
#include "IDEEditorContext.h"
#include "IDEEditorDocument.h"
#include "IDEEditorModeViewController.h"
#include "IDEEditorMultipleSplit.h"
#include "IDEEditorMultipleSplitDelegate-Protocol.h"
#include "IDENavigableItemArchivableRepresentation.h"
#include "IDESafeAreaAwareContainer-Protocol.h"
#include "_TtC6IDEKit12IDEBottomBar.h"

@class DVTBorderedView, DVTNotificationToken, DVTObservingToken, DVTReplacementView, DVTSplitView, DVTSplitViewItem, DVTStateToken, NSArray, NSDictionary, NSIndexPath, NSMutableArray, NSMutableDictionary, NSPanel, NSSet, NSString, NSTouchBar, NSView;

@interface IDEEditorArea : IDEViewController<NSTouchBarProvider, NSTouchBarDelegate, IDEBottomBarContextProvider, IDEEditorMultipleSplitDelegate, NSWindowDelegate, DVTSplitViewDelegate, IDESafeAreaAwareContainer> {
  /* instance variables */
  NSView *_editorAreaSplitHostView;
  DVTObservingToken *_workspaceActivityObserver;
  DVTObservingToken *_navigationTargetedEditorContextIsValidObservingToken;
  DVTObservingToken *_finishedLoadingObservingToken;
  NSMutableDictionary *_defaultPersistentRepresentations;
  NSString *_currentDefaultDebugAreaExtensionID;
  NSMutableArray *_editorAreaSplits_propertyObservingTokens;
  DVTBorderedView *_debuggerBarBorderedView;
  IDEDebugAreaBorderedView *_debuggerAreaBorderedView;
  DVTReplacementView *_debuggerBarReplacementView;
  DVTSplitView *_debuggerSplitView;
  DVTSplitViewItem *_editorSplitViewItem;
  DVTSplitViewItem *_debugAreaSplitViewItem;
  double _heightToReturnToDebuggerArea;
  BOOL _needsToRefreshContexts;
  BOOL _didRestoreState;
  BOOL _restoringStateSelfInitiated;
  NSObject<DVTCancellable> *_setEditorModeAfterDelayToken;
  NSObject<DVTCancellable> *_invokeCompletionBlockAfterDelayToken;
  DVTObservingToken *_lastActiveEditorContextIsValidToken;
  DVTObservingToken *_contentLayoutRectToken;
  DVTNotificationToken *_didEndLiveResizeToken;
  DVTNotificationToken *_windowDidBecomeKeyObserverToken;
  DVTNotificationToken *_windowDidResignKeyObserverToken;
  DVTObservingToken *_primaryEditorDocumentToken;
  DVTObservingToken *_activeEditorDocumentToken;
  DVTObservingToken *_workspaceFinishedLoadingToken;
  NSPanel *_safeAreaHierarchyPanel;
  DVTNotificationToken *_safeAreaHierarchyUpdateToken;
  NSArray *_beforeMaximizeEditorAreaSplitStates;
  NSIndexPath *_indexPathOfMaximizedEditorAreaSplit;
  long long _beforeComparisonMode_UserVisibleEditorMode;
  NSDictionary *_unrestoredStateDictionary;
}

@property (readonly) NSTouchBar *touchBar;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) IDEEditorAreaContainer *editorAreaAutoLayoutView;
@property (retain, nonatomic) IDEDebuggerAreaContainer *debuggerAreaAutoLayoutView;
@property (retain, nonatomic) IDEEditorAreaSplit *selectedEditorAreaSplit;
@property (retain) IDEEditorMultipleSplit *editorMultipleSplit;
@property (retain) IDEDebugArea *activeDebuggerArea;
@property (retain) IDEDFRDebugBar *activeDFRDebuggerBar;
@property (retain) IDEEditorContext *navigationTargetedEditorContext;
@property (retain, ) DVTStateToken *stateToken;
@property (retain) IDEEditorDocument *primaryEditorDocument;
@property (retain) IDEEditorAreaSplit *primaryEditorAreaSplit;
@property (retain) NSArray *editorAreaSplits;
@property BOOL alwaysShowTabBar;
@property long long maximizedState;
@property (readonly) IDEEditorContext *editorContextForMenuContent;
@property (readonly) DVTReplacementView *debuggerAreaReplacementView;
@property (readonly) unsigned long long editorAreaSplitsLayout;
@property BOOL isRestoringState;
@property (readonly, nonatomic) NSArray *accessibilitySectionElements;
@property (readonly) IDEEditorContext *primaryEditorContext;
@property (retain, nonatomic) IDEEditorContext *lastActiveEditorContext;
@property (readonly) IDEEditorAreaSplit *lastActiveEditorAreaSplit;
@property (readonly) IDENavigableItemArchivableRepresentation *selectedNavigableItemArchivedRepresentation;
@property (readonly) BOOL isDebuggerAreaVisible;
@property (readonly) BOOL isEditorVisible;
@property (readonly) IDEEditorDocument *navigationTargetedEditorDocument;
@property (readonly) IDEKit_IDEBottomBar *bottomBar;
@property (nonatomic) long long editorMode;
@property (readonly) IDEEditorModeViewController *editorModeViewController;
@property (readonly) IDEDebugBar *activeDebuggerBar;
@property (readonly) NSSet *bottomBarContext;
@property (nonatomic) double safeAreaTopInset;
@property (nonatomic) double safeAreaBottomInset;

/* class methods */
+ (BOOL)_newEditorsHaveEmptyContent;
+ (id)keyPathsForValuesAffectingLastActiveEditorAreaSplit;
+ (id)stringForEditorMode:(long long)mode;
+ (BOOL)automaticallyNotifiesObserversOfLastActiveEditorContext;
+ (id)keyPathsForValuesAffectingBottomBarContext;
+ (id)keyPathsForValuesAffectingPrimaryEditorContext;
+ (id)keyPathsForValuesAffectingNavigationTargetedEditorDocument;
+ (id)keyPathsForValuesAffectingSelectedNavigableItemArchivedRepresentation;
+ (BOOL)_openEditorHistoryItem:(id)item editorContext:(id)context options:(unsigned long long)options;
+ (BOOL)_openEditorOpenSpecifier:(id)specifier editorContext:(id)context options:(unsigned long long)options;
+ (id)keyPathsForValuesAffectingIsEditorVisible;
+ (id)keyPathsForValuesAffectingIsDebuggerAreaVisible;
+ (void)configureStateSavingObjectPersistenceByName:(id)name;
+ (long long)version;
+ (id)_configurationTransactionScope;
+ (BOOL)_isRunningConfigurationTransaction;
+ (void)_performConfigurationTransaction:(id /* block */)transaction;
+ (long long)defaultEditorMode;
+ (id)_copyEditorAreaSplitToParentEditorMultipleSplit:(id)split client:(unsigned long long)client;

/* instance methods */
- (BOOL)wantsToSuppressFunctionBar;
- (void)updateTouchBar;
- (id)makeTouchBar;
- (id)_touchBarForNavigatorWidget;
- (id)touchBar:(id)bar makeItemForIdentifier:(id)identifier;
- (id)_editorAreaItem;
- (id)_segmentedControlForHistoryNavigation;
- (void)navigateHistoryWithSegmentedControl:(id)control;
- (void)validateHistoryNavigation;
- (id)_fileHistoryNavigationMode;
- (id)editorAreaDFRController;
- (void)loadView;
- (void)_didRefreshEditorContextsForEditorAreaSplit:(id)split;
- (void)_updateJumpBarConfigurations;
- (void)_updateDebugBarAfterDocumentOpened;
- (void)invalidateBottomBarItemsForEditor:(id)editor;
- (void)uninstallBottomBarItemsForEditor:(id)editor;
- (void)_updateDebugAreaAfterDocumentOpened;
- (void)documentLostFocus:(id)focus;
- (void)documentReceivedFocus:(id)focus;
- (void)primitiveInvalidate;
- (void)__staticAnalyzer_InstanceVariablePartialInvalidator;
- (void)_refreshEditorContextsAndPreserveCurrentEditorHistoryStack:(BOOL)stack;
- (void)viewDidInstall;
- (void)updateSafeAreaTopInsets;
- (void)viewWillUninstall;
- (void)didInheritNewSafeAreaInsetsFromParent;
- (id)safeAreaAwareChildren;
- (BOOL)shouldSafeAreaAwareChildInheritTopInset:(id)inset;
- (BOOL)shouldSafeAreaAwareChildInheritBottomInset:(id)inset;
- (void)showSafeAreaHierarchyPanel;
- (void)updateSafeAreaHierarchyWindow;
- (void)windowWillClose:(id)close;
- (void)editorContextDidBecomeLastActiveEditor:(id)editor;
- (void)_updateNavigationTargetedEditorContextIsValidObservingToken;
- (void)editorContextWasRemoved:(id)removed;
- (void)_resetLastActiveEditorContext;
- (void)installDefaultDebugArea;
- (void)_installDefaultDebugAreaAndRevertDebugAreaState:(BOOL)state;
- (void)installNewDefaultDebugAreaWithExtensionID:(id)id;
- (void)installDebugAreaWithExtensionID:(id)id;
- (void)_installDebugAreaWithExtensionID:(id)id revertDebugAreaState:(BOOL)state;
- (id)_editorContexts;
- (id)stateSavingDefaultPersistentRepresentations;
- (void)setStateSavingDefaultPersistentRepresentations:(id)representations;
- (void)_cacheDefaultPersistentRepresentation:(id)representation forDocumentExtensionIdentifier:(id)identifier documentURL:(id)url;
- (void)_clearDefaultPersistentRepresentationForDocumentExtensionIdentifier:(id)identifier documentURL:(id)url;
- (id)_defaultPersistentRepresentationForDocumentExtensionIdentifier:(id)identifier documentURL:(id)url;
- (void)toggleBottomBarContextDebugger;
- (void)_moveDebuggerBarToEditorArea;
- (void)_moveDebuggerBarToDebuggerArea;
- (void)_addDebuggerBarToEditorArea;
- (void)_addDebuggerBarToDebuggerArea;
- (void)_updateDebuggerBarSplitPane;
- (void)showEditor;
- (void)hideEditor;
- (void)showDebuggerArea;
- (void)hideDebuggerArea;
- (void)_setShowDebuggerArea:(BOOL)area animate:(BOOL)animate;
- (void)activateConsole:(id)console;
- (void)toggleDebuggerVisibility:(id)visibility;
- (BOOL)validateUserInterfaceItem:(id)item;
- (void)toggleEditorOrientation:(id)orientation;
- (double)splitView:(id)view constrainMinCoordinate:(double)coordinate ofSubviewAt:(long long)at;
- (double)splitView:(id)view constrainMaxCoordinate:(double)coordinate ofSubviewAt:(long long)at;
- (BOOL)splitView:(id)view canCollapseSubview:(id)subview;
- (double)splitView:(id)view constrainSplitPosition:(double)position ofSubviewAt:(long long)at;
- (id)splitView:(id)view additionalEffectiveRectsOfDividerAtIndex:(long long)index;
- (void)_resizeSubviewsForHeightDecrease:(double)decrease;
- (void)_resizeSubviewsForHeightIncrease:(double)increase;
- (void)splitView:(id)view resizeSubviewsWithOldSize:(struct CGSize)size;
- (void)splitViewDidResizeSubviews:(id)subviews;
- (void)_updateStateSavingRegistrations;
- (void)revertState;
- (id)_stringForLayout:(unsigned long long)layout;
- (unsigned long long)_layoutForString:(id)string defaultValue:(unsigned long long)value;
- (void)revertStateWithDictionary:(id)dictionary;
- (void)_primitiveRevertStateWithDictionary:(id)dictionary;
- (void)_restoreEditorSplitsWhenWorkspaceFinishesLoading:(id /* block */)loading;
- (void)commitStateToDictionary:(id)dictionary;
- (BOOL)commitEditingForAction:(int)action errors:(id)errors;
- (void)discardEditing;
- (void)showBlame;
- (void)compareRevisionChange:(id)change;
- (void)openComparisonModeWithRevision:(id)revision client:(unsigned long long)client;
- (BOOL)_canChangeEditorAreaSplitsLayout;
- (BOOL)_canAddEditorAreaSplitAfterEditorAreaSplit:(id)split layout:(unsigned long long)layout;
- (id)_addEditorAreaSplitAfterEditorAreaSplit:(id)split copyContent:(BOOL)content layout:(unsigned long long)layout client:(unsigned long long)client;
- (BOOL)_canAddNewEditorAreaSplitAtIndex:(unsigned long long)index layout:(unsigned long long)layout;
- (id)_addNewEditorAreaSplitAtIndex:(unsigned long long)index layout:(unsigned long long)layout client:(unsigned long long)client;
- (BOOL)_canRemoveEditorAreaSplit:(id)split;
- (void)_removeEditorAreaSplit:(id)split client:(unsigned long long)client;
- (BOOL)_canResetAssistantEditorSelection;
- (void)_resetAssistantEditorSelection;
- (BOOL)_canCloseOtherEditors;
- (id)_closeAllEditorAreaSplitsKeeping:(id)keeping client:(unsigned long long)client;
- (void)_closeOtherEditorsUsingClient:(unsigned long long)client;
- (BOOL)_canCloseEditorContext:(id)context;
- (void)_closeEditorContext:(id)context client:(unsigned long long)client;
- (BOOL)_canResetEditorSizes;
- (void)_resetEditorSizes;
- (void)_cancelPendingStateRestoration;
- (void)toggleComparisonModeWithEditorAreaSplit:(id)split client:(unsigned long long)client;
- (BOOL)canToggleMaximizeEditor;
- (void)toggleMaximizeWithEditorAreaSplit:(id)split client:(unsigned long long)client;
- (void)_unmaximizeAndSelectedEditorAreaSplitWithClient:(unsigned long long)client;
- (id)_indexPathForEditorAreaSplit:(id)split;
- (void)_restoreEditorSplitsWithStateDictionaries:(id)dictionaries maximizedState:(long long)state selectedEditorSplitIndexPath:(id)path primaryHistoryStackForSelectedEditor:(id)editor secondaryHistoryStackForSelectedEditor:(id)editor tabBarStateForSelectedEditor:(id)editor client:(unsigned long long)client;
- (void)_primitiveRestoreEditorSplitsWithStateDictionaries:(id)dictionaries maximizedState:(long long)state selectedEditorSplitIndexPath:(id)path primaryHistoryStackForSelectedEditor:(id)editor secondaryHistoryStackForSelectedEditor:(id)editor tabBarStateForSelectedEditor:(id)editor client:(unsigned long long)client;
- (id)_maximizeWithEditorAreaSplit:(id)split client:(unsigned long long)client;
- (void)_newEditorTab:(id)tab;
- (void)_showPreviousEditorTab:(id)tab;
- (void)_showNextEditorTab:(id)tab;
- (BOOL)_canCloseActiveTabForEditorContext:(id)context;
- (void)_closeActiveTabForEditorContext:(id)context client:(unsigned long long)client;
- (BOOL)_canCloseOtherEditorTabsForEditorContext:(id)context;
- (void)_closeOtherTabsForEditorContext:(id)context client:(unsigned long long)client;
- (BOOL)_canCloseToTheRightEditorTabsForEditorContext:(id)context;
- (void)_closeToTheRightTabsForEditorContext:(id)context client:(unsigned long long)client;
- (BOOL)_canCloseToTheLeftEditorTabsForEditorContext:(id)context;
- (void)_closeToTheLeftTabsForEditorContext:(id)context client:(unsigned long long)client;
- (void)_updateEditorAreaSplits;
- (void)_updateEditorAreaSplitsWithoutSplitItem:(id)item;
- (void)editorMultipleSplit:(id)split didCreateSplitItem:(id)item;
- (void)didResizeEditorMultipleSplit:(id)split;
- (id)editorArea;
- (void)editorMultipleSplit:(id)split willRemoveSplitItem:(id)item fromIndex:(unsigned long long)index;
- (void)editorMultipleSplit:(id)split didRemoveSplitItem:(id)item fromIndex:(unsigned long long)index;
@end

#endif /* IDEEditorArea_h */
