//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEEditorCodeReviewPreferenceController_h
#define IDEEditorCodeReviewPreferenceController_h
#import <Foundation/Foundation.h>

#include "DVTInvalidation-Protocol.h"
#include "IDEEditorContext.h"

@class DVTGradientImageButton, DVTObservingToken, DVTStackBacktrace, NSImage, NSString;

@interface IDEEditorCodeReviewPreferenceController : NSObject<DVTInvalidation> {
  /* instance variables */
  IDEEditorContext *_editorContext;
  DVTObservingToken *_sourceControlManagerObserver;
  DVTObservingToken *_codeReviewToggledObserver;
  DVTObservingToken *_documentObserver;
  DVTGradientImageButton *_codeReviewButton;
  NSImage *_codeReviewActiveImage;
  NSImage *_codeReviewInactiveImage;
}

@property (nonatomic) unsigned long long preference;
@property (nonatomic) BOOL canToggleCodeReview;
@property (readonly, nonatomic) BOOL valid;
@property (readonly) DVTStackBacktrace *invalidationBacktrace;
@property (retain) DVTStackBacktrace *creationBacktrace;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)initialize;

/* instance methods */
- (id)initWithEditorContext:(id)context;
- (id)codeReviewControl;
- (void)updateButtonEnabledState;
- (BOOL)shouldShowCodeReviewPreferenceController;
- (BOOL)editorDocumentSupportsCodeReview;
- (BOOL)currentFileStateSupportsCodeReview;
- (void)toggleCodeReviewMode:(id)mode;
- (void)ensureCodeReviewToggled;
- (void)updateButtonState;
- (BOOL)isCodeReviewToggled;
- (void)primitiveInvalidate;
@end

#endif /* IDEEditorCodeReviewPreferenceController_h */
