//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEFindNavigatorOutlineView_h
#define IDEFindNavigatorOutlineView_h
#import <Foundation/Foundation.h>

#include "IDEAbstractFindNavigatorOutlineView.h"
#include "DVTEmptyContentPlaceholderContainer-Protocol.h"
#include "_TtP19DVTUserInterfaceKit34DVTEmptyContentPlaceholderDelegate_-Protocol.h"

@class NSFont, NSString;

@interface IDEFindNavigatorOutlineView : IDEAbstractFindNavigatorOutlineView<DVTUserInterfaceKit_DVTEmptyContentPlaceholderDelegate, DVTEmptyContentPlaceholderContainer> {
  /* instance variables */
  BOOL _hasRunEmptyContentPlaceholderLayout;
}

@property (readonly) BOOL processingMouseEvent;
@property (readonly) long long mouseDownRow;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (copy, nonatomic) NSString *emptyContentString;
@property (copy, nonatomic) NSString *emptyContentSubtitle;
@property (nonatomic) long long emptyContentStringStyle;
@property (copy, nonatomic) NSFont *emptyContentFont;
@property (nonatomic) BOOL hasContent;
@property (nonatomic) BOOL isLoadingContent;
@property (copy, nonatomic) NSString *emptyContentButtonTitle;
@property (nonatomic) BOOL followsFontAndColorTheme;

/* class methods */
+ (void)loadOutlineView:(id *)view scrollView:(id *)view;

/* instance methods */
- (void)layout;
- (void)mouseDown:(id)down;
- (BOOL)dataSourceSupportsWritingToPasteboard;
- (id)pasteboardSubjects:(BOOL)subjects;
- (void)performCopyForContextMenu:(BOOL)menu;
- (void)copy:(id)copy;
- (void)contextMenu_copy:(id)menu_copy;
- (BOOL)validateUserInterfaceItem:(id)item;
- (void)_synchronizeHasContentPropertyWithRowCount;
- (void)reloadData;
- (void)noteNumberOfRowsChanged;
- (void)reloadItem:(id)item reloadChildren:(BOOL)children;
- (void)insertItemsAtIndexes:(id)indexes inParent:(id)parent withAnimation:(unsigned long long)animation;
- (void)removeItemsAtIndexes:(id)indexes inParent:(id)parent withAnimation:(unsigned long long)animation;
- (void)moveItemAtIndex:(long long)index inParent:(id)parent toIndex:(long long)index inParent:(id)parent;
- (void)hideRowsAtIndexes:(id)indexes withAnimation:(unsigned long long)animation;
- (void)unhideRowsAtIndexes:(id)indexes withAnimation:(unsigned long long)animation;
- (id)delegate;
- (void)emptyContentPlaceholderButtonWasClicked:(id)clicked;
@end

#endif /* IDEFindNavigatorOutlineView_h */
