//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEFindNavigator_h
#define IDEFindNavigator_h
#import <Foundation/Foundation.h>

#include "IDENavigator.h"
#include "IDEFindNavigatorLayoutViewDelegate-Protocol.h"
#include "IDEFindNavigatorOutlineView.h"
#include "IDEFindNavigatorQueryParametersController.h"
#include "IDEFindNavigatorQueryParametersControllerDelegate-Protocol.h"
#include "IDEFindNavigatorQueryResultsControllerDelegate-Protocol.h"

@protocol IDEFindNavigatorQueryResultsControllerDelegate, IDEFindNavigatorQueryParametersControllerDelegate, IDEFindNavigatorLayoutViewDelegate;
@class DVTBorderView, DVTDelayedInvocation, DVTScrollView, NSString, NSTextField, NSView;

@interface IDEFindNavigator : IDENavigator<IDEFindNavigatorQueryResultsControllerDelegate, IDEFindNavigatorQueryParametersControllerDelegate, IDEFindNavigatorLayoutViewDelegate, NSMenuDelegate> {
  /* instance variables */
  NSView *_summaryRow;
  NSTextField *_summaryTextField;
  IDEFindNavigatorOutlineView *_resultOutlineView;
  DVTScrollView *_resultOutlineScrollView;
  DVTBorderView *_findResultsDividerView;
  DVTDelayedInvocation *_interfaceValidator;
  BOOL _didFirstLayoutAfterInstall;
}

@property (readonly) IDEFindNavigatorQueryParametersController *queryParametersController;
@property (copy, nonatomic) NSString *filterPattern;
@property (nonatomic) BOOL enableFilter;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)configureStateSavingObjectPersistenceByName:(id)name;

/* instance methods */
- (id)initWithNibName:(id)name bundle:(id)bundle;
- (BOOL)automaticallyInvalidatesChildViewControllers;
- (void)primitiveInvalidate;
- (void)viewDidInstall;
- (void)viewWillUninstall;
- (void)prepareToFocusUI;
- (BOOL)focusFindField;
- (BOOL)focusResultOutlineView;
- (void)findNavigatorLayoutViewDidLayout:(id)layout;
- (void)revertStateWithDictionary:(id)dictionary;
- (void)commitStateToDictionary:(id)dictionary;
- (id)resultsController;
- (id)view;
- (id)domainIdentifier;
- (id)filterDefinitionIdentifier;
- (id)navigatorScrollView;
- (void)refreshUserInterface:(id)interface;
- (void)viewDidLoad;
- (void)setStateToken:(id)token;
- (void)queryParametersControllerDidChangeExportedUserInterfaceState:(id)state;
- (id)selectionForResults:(id)results;
- (void)queryResultsController:(id)controller selectResults:(id)results;
- (id)contextMenuSelection;
- (void)queryResultsController:(id)controller openResult:(id)result displayProperties:(id)properties eventType:(unsigned long long)type;
- (void)cancelQuery;
- (void)queryParametersControllerCancelQuery:(id)query;
- (id)fileLocationTrayItemPrototypesWithTrayManager:(id)manager error:(id *)error;
- (id)innerDocumentLocationTrayItemPrototypesWithTrayManager:(id)manager error:(id *)error;
- (void)queryParametersController:(id)controller initiateQueryFromSpecification:(id)specification;
- (void)queryParametersController:(id)controller replaceSelectedResultsWithText:(id)text;
- (void)queryParametersController:(id)controller replaceAllResultsWithText:(id)text;
- (void)queryResultsControllerExportedUserInterfaceStateDidChange:(id)change;
- (id)queryResultsController:(id)controller contextMenuForResultsFromQuery:(id)query;
- (void)queryResultsController:(id)controller searchAgainWithSpecification:(id)specification;
- (void)revealInProjectNavigator:(id)navigator;
- (void)contextMenu_revealInProjectNavigator:(id)navigator;
- (BOOL)validateUserInterfaceItem:(id)item;
- (BOOL)delegateFirstResponder;
- (void)menuNeedsUpdate:(id)update;
@end

#endif /* IDEFindNavigator_h */
