//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEFindNavigatorScopeEditorPredicateController_h
#define IDEFindNavigatorScopeEditorPredicateController_h
#import <Foundation/Foundation.h>

#include "IDEFindNavigatorScopeAbstractRuleEditorController.h"

@class DVTDelayedInvocation;

@interface IDEFindNavigatorScopeEditorPredicateController : IDEFindNavigatorScopeAbstractRuleEditorController {
  /* instance variables */
  DVTDelayedInvocation *_validator;
}

/* instance methods */
- (id)initWithRuleEditor:(id)editor hostWorkspace:(id)workspace;
- (void)primitiveInvalidate;
- (void)insertPredicate:(id)predicate asChildOfRow:(long long)row;
- (void)displayPredicate:(id)predicate;
- (id)choicesForRow:(long long)row;
- (id)parseRow:(long long)row;
- (id)displayedPredicate;
- (id)childrenForCriterion:(id)criterion withRowType:(unsigned long long)type;
- (long long)ruleEditor:(id)editor numberOfChildrenForCriterion:(id)criterion withRowType:(unsigned long long)type;
- (id)ruleEditor:(id)editor child:(long long)child forCriterion:(id)criterion withRowType:(unsigned long long)type;
- (id)ruleEditor:(id)editor displayValueForCriterion:(id)criterion inRow:(long long)row;
- (void)ruleEditorRowsDidChange:(id)change;
- (BOOL)isAlwaysTruePredicate:(id)predicate;
- (void)refreshNestingModeForPredicate:(id)predicate;
- (void)validatePredicate:(id)predicate;
@end

#endif /* IDEFindNavigatorScopeEditorPredicateController_h */
