//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEFindNavigatorTwoControlLeftPriorityLayout_h
#define IDEFindNavigatorTwoControlLeftPriorityLayout_h
#import <Foundation/Foundation.h>

#include "DVTLayoutView_ML.h"

@class NSControl;

@interface IDEFindNavigatorTwoControlLeftPriorityLayout : DVTLayoutView_ML {
  /* instance variables */
  struct CGPoint _leftOffset;
  struct CGPoint _rightOffset;
}

@property (retain) NSControl *leftControl;
@property (retain) NSControl *rightControl;
@property double horizontalSpacing;

/* instance methods */
- (void)awakeFromNib;
- (void)layoutTopDown;
- (void)layoutBottomUp;
@end

#endif /* IDEFindNavigatorTwoControlLeftPriorityLayout_h */
