//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEFindNavigatorPathControl_h
#define IDEFindNavigatorPathControl_h
#import <Foundation/Foundation.h>

#include "DVTStructuredLayoutView.h"
#include "DVTCancellable-Protocol.h"
#include "DVTWindowActivationStateObserver-Protocol.h"

@protocol IDEFindNavigatorPathControlDelegate;
	
@class DVTStackView_ML, NSArray, NSDictionary, NSImage, NSString;

@interface IDEFindNavigatorPathControl : DVTStructuredLayoutView<DVTWindowActivationStateObserver> {
  /* instance variables */
  DVTStackView_ML *_stackView;
  NSDictionary *_segmentComponentViews;
  NSArray *_dividerImageViews;
  NSImage *_activeDividerImage;
  NSImage *_inactiveDividerImage;
  NSObject<DVTCancellable> *_windowActivationObservation;
}

@property (retain) NSObject<IDEFindNavigatorPathControlDelegate> *delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)awakeFromNib;
- (id)componentViewForSegment:(id)segment;
- (void)scheduleRefresh;
- (id)makeComponentView;
- (void)synchronizeComponentView:(id)view forSegment:(id)segment;
- (void)refresh;
- (void)dvt_positionSubviewsAndSizeSelfAfterSubviewLayout;
- (void)window:(id)window didChangeActivationState:(long long)state;
- (void)viewWillMoveToWindow:(id)window;
- (void)userChoseSegmentValue:(id)value;
@end

#endif /* IDEFindNavigatorPathControl_h */
