//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
//

#include "Shared.h"

#import "DVTInvalidation-Protocol.h"

@class DVTStackBacktrace, NSString;

@interface IDEIndex : NSObject <DVTInvalidation>
{
    BOOL _valid;
    BOOL _isQuiescent;
}

+ (BOOL)languageSupportsSymbolColoring:(id)arg1;
@property(readonly) BOOL isQuiescent; // @synthesize isQuiescent=_isQuiescent;
@property(readonly, nonatomic, getter=isValid) BOOL valid; // @synthesize valid=_valid;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;

@end

