//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22028.0.0.0.0
//
#ifndef IDEIndexGlobalQueryProvider_Protocol_h
#define IDEIndexGlobalQueryProvider_Protocol_h
#import <Foundation/Foundation.h>

@protocol IDEIndexQueryProvider;

@protocol IDEIndexGlobalQueryProvider <IDEIndexQueryProvider>
/* instance methods */
- (id)allParentsOfSymbols:(id)symbols cancelWhen:(id /* block */)when forIndex:(id)index;
- (id)filesIncludingFile:(id)file forIndex:(id)index;
- (id)includesOfFile:(id)file forIndex:(id)index;
- (id)filesIncludedByFile:(id)file forIndex:(id)index;
- (id)filesContaining:(id)containing anchorStart:(BOOL)start anchorEnd:(BOOL)end subsequence:(BOOL)subsequence ignoreCase:(BOOL)caseNot cancelWhen:(id /* block */)when forIndex:(id)index;
- (id)topLevelSymbolsMatchingKind:(id)kind workspaceOnly:(BOOL)only cancelWhen:(id /* block */)when forIndex:(id)index;
- (id)symbolsContaining:(id)containing anchorStart:(BOOL)start anchorEnd:(BOOL)end subsequence:(BOOL)subsequence ignoreCase:(BOOL)caseNot cancelWhen:(id /* block */)when forIndex:(id)index;
- (id)allClassesMatchingName:(id)name forIndex:(id)index;
- (id)allSymbolsMatchingName:(id)name kind:(id)kind forIndex:(id)index;
- (id)allSymbolsMatchingNames:(id)names kind:(id)kind forIndex:(id)index;
- (id)allSubClassesForClasses:(id)classes forIndex:(id)index;
- (id)testMethodsForClasses:(id)classes forIndex:(id)index;
- (id)allSymbolsMatchingKind:(id)kind workspaceOnly:(BOOL)only cancelWhen:(id /* block */)when forIndex:(id)index;
- (id)allSymbolsMatchingKinds:(id)kinds inFiles:(id)files cancelWhen:(id /* block */)when;
- (unsigned long long)countOfSymbolsMatchingKind:(id)kind workspaceOnly:(BOOL)only forIndex:(id)index;
- (id)symbolsForResolutions:(id)resolutions forIndex:(id)index;
- (id)membersMatchingKinds:(id)kinds forInterfaces:(id)interfaces forIndex:(id)index;
- (id)allMethodsMatchingMethod:(id)method forReceiver:(id)receiver forIndex:(id)index;
- (void)allSymbolNames:(id /* block */)names forIndex:(id)index;
- (id)modelOccurrenceForSymbol:(id)symbol;
- (id)occurrencesForSymbol:(id)symbol;
- (id)declarationsForSymbol:(id)symbol;
- (id)definitionsForSymbol:(id)symbol;
- (id)containerSymbolsForSymbol:(id)symbol;
- (id)containerSymbolForSymbol:(id)symbol;
- (id)referencingFilesForSymbol:(id)symbol;
- (id)referencesForSymbol:(id)symbol;
- (id)overriddenSymbolsForSymbol:(id)symbol;
- (id)overridingSymbolsForSymbol:(id)symbol;
- (id)overridingSymbolsForSymbol:(id)symbol fromReceivers:(id)receivers;
- (id)overridingOccurrencesForSymbol:(id)symbol bySymbol:(id)symbol;
- (id)specializesSymbolsForSymbol:(id)symbol;
- (id)specializationsForSymbol:(id)symbol;
- (id)propertyForCallable:(id)callable;
- (id)typeOfArgument:(unsigned long long)argument forCallable:(id)callable;
- (id)callsForCallable:(id)callable cancelWhen:(id /* block */)when;
- (id)setterForProperty:(id)property;
- (id)getterForProperty:(id)property;
- (id)iVarsForProperty:(id)property;
- (id)propertyForIVar:(id)ivar;
- (id)categoriesForClass:(id)class;
- (id)superClassesForClass:(id)class;
- (id)allSuperClassesForClass:(id)class;
- (id)subClassesForClass:(id)class;
- (id)allSubClassesForClass:(id)class;
- (id)protocolsForClass:(id)class;
- (id)allProtocolsForClass:(id)class;
- (id)interfacesForClass:(id)class;
- (id)implementingClassesForProtocol:(id)protocol;
- (id)implementingSymbolsForProtocol:(id)protocol;
- (id)relatedClassForCategory:(id)category;
- (id)correspondingSymbolForOccurrence:(id)occurrence;
- (id)containingSymbolForOccurrence:(id)occurrence;
- (id)locationForSymbolOccurrence:(id)occurrence;
- (id)calleesForSymbolOccurrence:(id)occurrence;
- (id)membersMatchingKind:(id)kind forSymbol:(id)symbol;
- (id)parametersForCallable:(id)callable;
- (BOOL)isProjectSymbol:(id)symbol;
@end

#endif /* IDEIndexGlobalQueryProvider_Protocol_h */
