//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22028.0.0.0.0
//
#ifndef IDEIndex_h
#define IDEIndex_h
#import <Foundation/Foundation.h>

#include "DVTInvalidation-Protocol.h"
#include "IDEBoltIndexDatabase.h"
#include "IDEBoltIndexDatabaseProgressDelegate-Protocol.h"
#include "IDECoalescingInvocation.h"
#include "IDEIndexDatabaseDelegate-Protocol.h"
#include "IDEIndexQPManager.h"
#include "IDEIndexingEngine.h"
#include "IDEWorkspace.h"
#include "SKScanIndexDelegate-Protocol.h"
#include "SKToolchainResolver.h"
#include "SKUnitTestsIndex.h"

@class DVTDispatchLock, DVTFilePath, DVTFuture, DVTNotificationToken, DVTStackBacktrace, NSDate, NSDictionary, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, IDEWorkspace;
@protocol OS_dispatch_queue;

@interface IDEIndex : NSObject<IDEBoltIndexDatabaseProgressDelegate, IDEIndexDatabaseDelegate, SKScanIndexDelegate, DVTInvalidation> {
  /* instance variables */
  SKToolchainResolver *_toolchainResolver;
  DVTFilePath *_datastoreFolder;
  DVTFilePath *_folder;
  DVTFilePath *_pchFolder;
  DVTFilePath *_toolchainInvocationLoggingPath;
  BOOL _enableBackgroundIndexer;
  BOOL _enableExplicitOutputUnits;
  BOOL _enableFullStoreVisibility;
  BOOL _enablePCHCreation;
  BOOL _dumpIndexables;
  BOOL _sawInitialBuildDescriptionNotification;
  NSMutableDictionary *_identifiersToIndexables;
  NSMutableDictionary *_indexablesToProductHeaders;
  NSMutableDictionary *_copiedHeadersToSources;
  NSMutableDictionary *_sourceHeadersToIndexables;
  NSDictionary *_preferredTargets;
  IDEBoltIndexDatabase *_workspaceDatabase;
  DVTDispatchLock *_stateLock;
  DVTDispatchLock *_pchCreationLock;
  NSMutableDictionary *_pchFiles;
  NSDate *_lastErrorTime;
  BOOL _isCancelled;
  BOOL _isInErrorRecoveryMode;
  BOOL _isReadOnly;
  unsigned long long _initialDBSize;
  DVTDispatchLock *_findFilesLock;
  long long _nextFindFilesToken;
  NSMutableDictionary *_findFilesCallbacks;
  NSObject<OS_dispatch_queue> *_editorFileUpdateQueue;
  DVTNotificationToken *_indexableFileWasAddedNotificationObservingToken;
  DVTNotificationToken *_indexableFileWillBeRemovedNotificationObservingToken;
  DVTNotificationToken *_indexableDidRenameFileNotificationObservingToken;
  DVTNotificationToken *_buildablesDidChangeNotificationObservingToken;
  DVTNotificationToken *_buildSettingsDidChangeNotificationObservingToken;
  DVTNotificationToken *_buildOperationDidStopNotificationObservingToken;
  unsigned long long _timeSinceLastProcessingUnitsPost;
  NSMutableDictionary *_recentlyEditorSavedFiles;
  DVTFilePath *_currentEditorFocusedFile;
  DVTFuture *_editorFocusedFilePreparationFuture;
  NSMutableArray *_editorFocusedPreparingindexables;
  NSMutableSet *_editorViewableFiles;
  IDECoalescingInvocation *_didChangeStateInvocation;
  NSMutableDictionary *_buildSettingsForFile;
  NSObject<OS_dispatch_queue> *_buildSettingsForFileQueryQueue;
}

@property (readonly, nonatomic) IDEWorkspace *workspace;
@property (readonly, nonatomic) NSString *workspaceName;
@property (readonly, nonatomic) DVTFilePath *workspaceFile;
@property (readonly, nonatomic) IDEBoltIndexDatabase *database;
@property (readonly, nonatomic) DVTFilePath *databaseFile;
@property (readonly) DVTFilePath *headerMapFilePath;
@property (retain) IDEIndexingEngine *engine;
@property (retain) IDEIndexQPManager *qpManager;
@property (retain) SKUnitTestsIndex *unitTestsIndex;
@property BOOL isDatabaseInitializedFromDatastore;
@property (nonatomic) unsigned long long indexerToken;
@property (readonly) BOOL isBackgroundIndexingEnabled;
@property (readonly) BOOL isPCHCreationEnabled;
@property (readonly, nonatomic) BOOL isQuiescent;
@property (readonly, nonatomic) BOOL isPaused;
@property BOOL avoidDelaysForTesting;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) BOOL valid;
@property (readonly) DVTStackBacktrace *invalidationBacktrace;
@property (retain) DVTStackBacktrace *creationBacktrace;

/* class methods */
+ (id)logAspect;
+ (id)metricLogAspect;
+ (id)compilerInvocationLogAspect;
+ (id)schedulingLogAspect;
+ (void)initialize;
+ (id)_databaseFolderForWorkspace:(id)workspace;
+ (id)_pchFolderForWorkspace:(id)workspace;
+ (id)createIndexForWorkspace:(id)workspace toolchainResolver:(id)resolver datastoreFolder:(id)folder toolchainInvocationLoggingPath:(id)path enableBackgroundIndexer:(BOOL)indexer enableExplicitOutputUnits:(BOOL)units enableFullStoreVisibility:(BOOL)visibility enablePCHCreation:(id)pchcreation dumpIndexables:(BOOL)indexables initialDBSize:(unsigned long long)dbsize;
+ (void)dumpIndexableAsPropertyList:(id)list settings:(id)settings;
+ (BOOL)supportsInvalidationPrevention;
+ (unsigned long long)assertionBehaviorAfterEndOfEventForSelector:(SEL)selector;
+ (id)dataSourceExtensionForFile:(id)file withLanguage:(id)language;
+ (id)_dataSourceExtensionForFile:(id)file withLanguage:(id)language;
+ (void)logCompilerInvocationImpl_uncovered_:(id)impl_uncovered_ tool:(int)tool toolchain:(id)toolchain;
+ (void)logCompilerInvocationWithArguments:(id)arguments tool:(int)tool toolchain:(id)toolchain;

/* instance methods */
- (id)filesIncludingFile:(id)file;
- (id)includesOfFile:(id)file;
- (id)filesIncludedByFile:(id)file;
- (id)filesContaining:(id)containing anchorStart:(BOOL)start anchorEnd:(BOOL)end subsequence:(BOOL)subsequence ignoreCase:(BOOL)caseNot cancelWhen:(id /* block */)when;
- (id)symbolsContaining:(id)containing anchorStart:(BOOL)start anchorEnd:(BOOL)end subsequence:(BOOL)subsequence ignoreCase:(BOOL)caseNot;
- (id)symbolsContaining:(id)containing anchorStart:(BOOL)start anchorEnd:(BOOL)end subsequence:(BOOL)subsequence ignoreCase:(BOOL)caseNot cancelWhen:(id /* block */)when;
- (id)symbolsMatchingName:(id)name inContext:(id)context withCurrentFileContentDictionary:(id)dictionary;
- (id)symbolsOccurrencesInContext:(id)context withCurrentFileContentDictionary:(id)dictionary;
- (id)referencesToSymbolMatchingName:(id)name inContext:(id)context withCurrentFileContentDictionary:(id)dictionary;
- (id)messageReceiverInContext:(id)context withCurrentFileContentDictionary:(id)dictionary;
- (id)typeSymbolForSymbol:(id)symbol withCurrentFileContentDictionary:(id)dictionary;
- (id)importedFilesAtDocument:(id)document withCurrentFileContentDictionary:(id)dictionary;
- (id)importedFileAtDocumentLocation:(id)location withCurrentFileContentDictionary:(id)dictionary;
- (id)impliedHeadersForModuleImportLocation:(id)location withCurrentFileContentDictionary:(id)dictionary;
- (id)allClassesMatchingName:(id)name;
- (id)allSymbolsMatchingName:(id)name kind:(id)kind;
- (id)allSymbolsMatchingNames:(id)names kind:(id)kind;
- (id)allSubClassesForClasses:(id)classes;
- (id)testCaseBaseClasses;
- (id)testMethodsForClasses:(id)classes;
- (id)allSymbolsMatchingKind:(id)kind workspaceOnly:(BOOL)only;
- (id)allSymbolsMatchingKinds:(id)kinds inFiles:(id)files;
- (unsigned long long)countOfSymbolsMatchingKind:(id)kind workspaceOnly:(BOOL)only;
- (id)allParentsOfSymbols:(id)symbols cancelWhen:(id /* block */)when;
- (void)libclangCompletionsAtLocation:(id)location withCurrentFileContentDictionary:(id)dictionary receiver:(id /* block */)receiver;
- (id)codeDiagnosticsAtLocation:(id)location withCurrentFileContentDictionary:(id)dictionary;
- (id)parsedCodeCommentAtLocation:(id)location withCurrentFileContentDictionary:(id)dictionary;
- (id)symbolGraphAtLocation:(id)location withCurrentFileContentDictionary:(id)dictionary includeRawComment:(BOOL)comment includeParsedComment:(BOOL)comment;
- (id)skippedRangesAtDocument:(id)document withCurrentFileContentDictionary:(id)dictionary;
- (id)symbolsForResolutions:(id)resolutions;
- (id)membersMatchingKinds:(id)kinds forInterfaces:(id)interfaces;
- (id)parametersForCallable:(id)callable;
- (id)allMethodsMatchingMethod:(id)method forReceiver:(id)receiver;
- (id)overridingSymbolsForSymbol:(id)symbol fromReceivers:(id)receivers;
- (id)collectTestMethodsPerTestTargets;
- (void)allSymbolNames:(id /* block */)names;
- (id)availableRefactorings:(id)refactorings includeSymbol:(BOOL)symbol withCurrentFileContentDictionary:(id)dictionary;
- (BOOL)findRenameRangesForIndexedSymbols:(id)symbols inFile:(id)file withCurrentFileContentDictionary:(id)dictionary error:(id *)error completionHandler:(id /* block */)handler;
- (BOOL)findLocalRenameRangesAtLocation:(id)location withCurrentFileContentDictionary:(id)dictionary error:(id *)error completionHandler:(id /* block */)handler;
- (BOOL)localRefactoring:(void *)refactoring atSelection:(id)selection withCurrentFileContentDictionary:(id)dictionary error:(id *)error completionHandler:(id /* block */)handler;
- (BOOL)renameIndexedSymbols:(id)symbols inFile:(id)file withCurrentFileContentDictionary:(id)dictionary error:(id *)error completionHandler:(id /* block */)handler;
- (BOOL)renameAtLocation:(id)location toName:(id)name withCurrentFileContentDictionary:(id)dictionary error:(id *)error completionHandler:(id /* block */)handler;
- (id)translateName:(id)name ofSymbol:(id)symbol toLanguageOfRef:(id)ref withCurrentFileContentDictionary:(id)dictionary;
- (void)_setupObservers;
- (id)_databaseFileURLForFolder:(id)folder;
- (id)initWithFolder:(id)folder forWorkspace:(id)workspace toolchainResolver:(id)resolver datastoreFolder:(id)folder toolchainInvocationLoggingPath:(id)path enableBackgroundIndexer:(BOOL)indexer enableExplicitOutputUnits:(BOOL)units enableFullStoreVisibility:(BOOL)visibility enablePCHCreation:(id)pchcreation dumpIndexables:(BOOL)indexables readonly:(BOOL)readonly initialDBSize:(unsigned long long)dbsize;
- (id)initWithFolder:(id)folder datastoreFolder:(id)folder toolchainInvocationLoggingPath:(id)path enableBackgroundIndexer:(BOOL)indexer enableExplicitOutputUnits:(BOOL)units enableFullStoreVisibility:(BOOL)visibility enablePCHCreation:(id)pchcreation readonly:(BOOL)readonly initialDBSize:(unsigned long long)dbsize;
- (BOOL)openDatabase;
- (id)datastoreFolder;
- (id)pchFolder;
- (id)toolchainInvocationLoggingPath;
- (id)toolchainForSettings:(id)settings tool:(int)tool;
- (void)_didChangeState;
- (void)_onFinalDidChangeStateEvent;
- (void)postNotificationName:(id)name userInfo:(id)info;
- (void)postNotificationName:(id)name;
- (void)registerObject:(id)object;
- (void)unregisterObject:(id)object;
- (void)updatePreferredTargets:(id)targets;
- (void)addUnitOutFilePaths:(id)paths waitForProcessing:(BOOL)processing;
- (void)removeUnitOutFilePaths:(id)paths waitForProcessing:(BOOL)processing;
- (id)indexableForIdentifier:(id)identifier;
- (void)suspendIndexing;
- (void)resumeIndexing;
- (void)setThrottleFactor:(double)factor;
- (void)setDelayToBatchChanges:(BOOL)changes;
- (BOOL)delayToBatchChanges;
- (void)_stopIndexing;
- (void)editorMovedFocusToFile:(id)file;
- (void)_updateBuildDependenciesForEditorFocusedFile;
- (void)editorAssociatedWithFile:(id)file;
- (void)editorDisassociatedWithFile:(id)file;
- (void)editorWillSaveFile:(id)file;
- (void)editorDidSaveFile:(id)file completionHandler:(id /* block */)handler;
- (void)filesDidChange:(id)change;
- (void)buildSystemDidUpdateBuildDescription;
- (BOOL)needsWorkspaceHeaderMap;
- (void)registerFileForBuildSettingsNotifications:(id)notifications;
- (void)unregisterFileForBuildSettingsNotifications:(id)notifications;
- (void)_tryInferringBuildSettingsForUnresolvedFiles;
- (void)_handleBuildSettingsResult:(id)result prepareAction:(long long)action file:(id)file settingsInfo:(id)info;
- (void)_inferBuildSettingsForFileAndNotifyAsync:(id)async settingsInfo:(id)info;
- (void)updateIndexForFiles:(id)files;
- (void)primitiveInvalidate;
- (void)gatherProductHeadersForIndexable:(id)indexable;
- (void)waitForBuildSystem:(id)system prepareBuildDependencies:(BOOL)dependencies;
- (id)_waitForSettingsFromObject:(id)object file:(id)file prepareBuildDependencies:(BOOL)dependencies highPriority:(BOOL)priority;
- (id)_waitForSettingsForFile:(id)file object:(id)object prepareBuildDependencies:(BOOL)dependencies highPriority:(BOOL)priority;
- (id)settingsForFile:(id)file indexable:(id)indexable prepareBuildDependencies:(BOOL)dependencies highPriority:(BOOL)priority;
- (id)_dataSourceExtensionForFile:(id)file withSettings:(id)settings;
- (id)dataSourceExtensionForFile:(id)file settings:(id)settings;
- (void)_respondToFileChangeNotification:(id)notification;
- (void)databaseDidIndexHotFile:(id)file;
- (void)databaseDidChangeMainFiles:(id)files;
- (void)database:(id)database didEndImportSession:(id)session;
- (void)databaseDidOpen:(id)open;
- (void)databaseDidInitializeFromDatastore:(id)datastore;
- (void)startedProcessingUnits;
- (void)processingUnitsCompleted:(long long)completed remaining:(long long)remaining;
- (void)finishedProcessingUnits;
- (void)storeCompletedProcessingUnits;
- (void)storeProcessedUnitOutputPath:(id)path hasTestSymbols:(BOOL)symbols;
- (void)scanIndexStartedScanning:(id)scanning;
- (void)scanIndexIsScanning:(id)scanning completed:(long long)completed remaining:(long long)remaining;
- (void)scanIndexDidFinishScanning:(id)scanning;
- (void)_initCopiedHeaders;
- (id)makeRelativeIfInsideBuildProductsFolder:(id)folder;
- (id)effectivePathForHeader:(id)header;
- (id)indexableForCopiedHeader:(id)header;
- (id)queryProviderForFile:(id)file highPriority:(BOOL)priority;
- (id)queryProviderForFileNoFallback:(id)fallback highPriority:(BOOL)priority;
- (id)queryProviderForFileNoBuildSettings:(id)settings;
- (void)registerHotFile:(id)file;
- (id)queryProviderForLocation:(id)location highPriority:(BOOL)priority;
- (id)databaseQueryProvider;
- (BOOL)isPreferredTarget:(id)target;
- (BOOL)isPreferredTarget:(id)target isBuiltForRun:(BOOL *)run isImplicitDependency:(BOOL *)dependency;
- (BOOL)isTargetMatchingActiveDestinationPlatform:(id)platform;
- (void)_clearAllCachedBuildSettings;
- (void)activeRunDestinationDidChange;
- (void)_resetQueryProviderStateForDocumentsWithClearCachedBuildSettings:(BOOL)settings;
- (void)indexableChangedLinkedIndexables:(id)indexables linkedIndexableIds:(id)ids;
- (void)_buildSettingsDidChange:(id)change;
- (void)_buildOperationDidStop:(id)stop;
- (id)mainFilesForFile:(id)file crossLanguage:(BOOL)language;
- (id)targetIdentifiersForFile:(id)file;
- (BOOL)filesContainingWord:(id)word handler:(id /* block */)handler;
- (void)cancelFindFiles:(long long)files;
- (void)_filesContainingWordUpdate:(long long)update results:(id)results isFinished:(BOOL)finished;
@end

#endif /* IDEIndex_h */
