//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22028.0.0.0.0
//
#ifndef IDEIndexQPManager_h
#define IDEIndexQPManager_h
#import <Foundation/Foundation.h>

#include "IDEIndex.h"

@class NSMutableArray, NSTimer;
@protocol OS_dispatch_queue;

@interface IDEIndexQPManager : NSObject {
  /* instance variables */
  NSObject<OS_dispatch_queue> *_qp_queue;
  NSMutableArray *_masterBlocks;
  NSMutableArray *_recentQueryProviders;
  NSTimer *_purgeTimer;
}

@property (readonly, nonatomic) IDEIndex *index;

/* class methods */
+ (void)initialize;

/* instance methods */
- (id)initWithIndex:(id)index;
- (void)dealloc;
- (id)queryProviderForFileNoBuildSettings:(id)settings;
- (void)findBestIndexableForFile:(id)file outIndexable:(id *)indexable outMainFile:(id *)file outHadToSettle:(BOOL *)settle;
- (id)queryProviderForFile:(id)file highPriority:(BOOL)priority;
- (void)purgeAllQPs;
- (void)settingsReceivedForMainFile:(id)file indexable:(id)indexable settings:(id)settings;
- (void)buildDependenciesPreparedForIndexable:(id)indexable updateTime:(id)time;
- (void)_addQueryProviderToRecents:(id)recents highPriority:(BOOL)priority;
- (void)_scheduleQPPurge;
- (void)_purgeTimeout:(id)timeout;
- (void)_cancelPurgeTimer;
- (void)_logRecents;
@end

#endif /* IDEIndexQPManager_h */
