//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
//

#include "Shared.h"

#import "DVTInvalidation-Protocol.h"
#import "IDETestableDataSource_Index-Protocol.h"

@class DVTStackBacktrace, IDEIndexBuildManager, NSString;

@interface IDEIndex : NSObject <IDETestableDataSource_Index, DVTInvalidation>
{
    BOOL _valid;
    BOOL _isQuiescent;
    IDEIndexBuildManager *_indexBuildManager;
}

+ (BOOL)languageSupportsSymbolColoring:(id)arg1;
// - (void).cxx_destruct;
@property(readonly) BOOL isQuiescent; // @synthesize isQuiescent=_isQuiescent;
@property(readonly) IDEIndexBuildManager *indexBuildManager; // @synthesize indexBuildManager=_indexBuildManager;
@property(readonly, nonatomic, getter=isValid) BOOL valid; // @synthesize valid=_valid;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;

@end

