//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDELogStoreObservable_Protocol_h
#define IDELogStoreObservable_Protocol_h
#import <Foundation/Foundation.h>

@protocol IDELogStoreObservable <NSObject>

@property (readonly) BOOL isRecording;
@property (readonly) unsigned long long totalNumberOfTestFailures;
@property (readonly) unsigned long long totalNumberOfErrors;
@property (readonly) unsigned long long totalNumberOfWarnings;
@property (readonly) unsigned long long totalNumberOfAnalyzerResults;
@property (readonly) NSNumber *totalCodeCoveragePercentage;

@end

#endif /* IDELogStoreObservable_Protocol_h */
