//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDELocationScenario_h
#define IDELocationScenario_h
#import <Foundation/Foundation.h>

@class DVTFilePath, NSArray, NSError, NSString;

@interface IDELocationScenario : NSObject {
  /* instance variables */
  BOOL _hasLoadedContent;
  BOOL _isCurrentLocation;
}

@property (retain) NSError *gpxError;
@property (readonly) NSString *identifier;
@property (readonly) DVTFilePath *filePath;
@property (readonly) NSString *name;
@property (readonly) NSArray *locations;
@property (readonly) BOOL autorepeat;
@property (readonly) BOOL isCurrentLocationScenario;
@property (readonly) BOOL defaultScenario;

/* class methods */
+ (void)initialize;
+ (id)currentLocationScenario;
+ (id)defaultScenarios;
+ (id)builtInScenarioWithIdentifier:(id)identifier;

/* instance methods */
- (id)initWithIdentifier:(id)identifier locations:(id)locations;
- (id)initWithIdentifier:(id)identifier locations:(id)locations autorepeat:(BOOL)autorepeat;
- (id)initWithIdentifier:(id)identifier referencingFilePath:(id)path;
- (id)initWithWorkspace:(id)workspace referencingFilePath:(id)path;
- (id)_gpxFileErrorWithCode:(long long)code reason:(id)reason;
- (id)_locationsFromReferencedGPXFileWithError:(id *)error;
- (id)_processedLocationsFromGPXLocations:(id)gpxlocations;
- (void)_loadLocationsIfNeeded;
- (BOOL)isValidWithError:(id *)error;
- (id)description;
- (BOOL)isDefaultScenario;
@end

#endif /* IDELocationScenario_h */
