//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEMediaResourceVariantContext_h
#define IDEMediaResourceVariantContext_h
#import <Foundation/Foundation.h>

#include "DVTInvalidation-Protocol.h"
#include "IDEMediaResourceFoldingStrategy.h"

@class DVTStackBacktrace, NSMapTable, NSMutableDictionary, NSMutableSet, NSSet, NSString;

@interface IDEMediaResourceVariantContext : NSObject<DVTInvalidation> {
  /* instance variables */
  NSMapTable *_repositoriesToMediaTypesToNamesToVariantSets;
  NSMapTable *_repositoriesToObservationTokens;
  NSMutableDictionary *_mediaTypesToVariantSets;
  NSSet *_repositories;
  NSMutableDictionary *_observers;
}

@property (readonly) NSSet *variantSets;
@property (readonly) IDEMediaResourceFoldingStrategy *foldingStrategy;
@property (readonly, nonatomic) BOOL valid;
@property (readonly) DVTStackBacktrace *invalidationBacktrace;
@property (retain) DVTStackBacktrace *creationBacktrace;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)initialize;

/* instance methods */
- (id)initWithFoldingStratgey:(id)stratgey andMediaRepositories:(id)repositories;
- (void)primitiveInvalidate;
- (id)resourceNamesToVariantSetsForMediaType:(id)type;
- (id)variantSetsWithNames:(id)names andMediaType:(id)type;
- (id)variantSetsWithName:(id)name andMediaType:(id)type;
- (id)variantSetsOfMediaType:(id)type;
- (id)registerVariantContextObserverWithOptions:(unsigned long long)options block:(id /* block */)block;
- (void)notifyObserversOfAddsAndModifies:(id)modifies andDeletes:(id)deletes;
- (void)repository:(id)repository didAddOrUpdateResources:(id)resources andRemoveResources:(id)resources;
@end

#endif /* IDEMediaResourceVariantContext_h */
