//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDENavigatorGroup_h
#define IDENavigatorGroup_h
#import <Foundation/Foundation.h>

@class DVTExtension, NSArray, NSImage, NSString;

@interface IDENavigatorGroup : NSObject { // (Swift)
  /* instance variables */
   void *bundle;
   void *displayOrderedEntries;
}

@property (nonatomic, readonly) NSString *identifier;
@property (nonatomic, readonly) BOOL enabledInPlaygrounds;
@property (nonatomic, readonly) double preferredPosition;
@property (nonatomic, readonly) NSString *menuCommandIdentifier;
@property (nonatomic, readonly) NSString *imageName;
@property (nonatomic, readonly) NSString *selectedImageName;
@property (nonatomic, readonly) NSString *title;
@property (nonatomic, readonly) NSString *toolTip;
@property (nonatomic, readonly) DVTExtension *singleTopLevelAlternatePairPrimary;
@property (nonatomic, readonly) DVTExtension *singleTopLevelAlternatePairAlternative;
@property (nonatomic, readonly) NSArray *primaryNavigators;
@property (nonatomic, readonly) NSArray *allNavigators;
@property (nonatomic, readonly) BOOL hasSingleTopLevelAlternate;
@property (nonatomic, readonly) NSImage *image;
@property (nonatomic, readonly) NSImage *selectedImage;
@property (nonatomic, readonly) DVTExtension *initialNavigator;

/* class methods */
+ (BOOL)allowNavigatorVariants;
+ (id)displayOrderedWorkspaceGroups;
+ (id)displayOrderedPlaygroundGroups;

/* instance methods */
- (id)initWithExtension:(id)extension;
- (id)navigatorWithIdentifier:(id)identifier;
- (id)init;
@end

#endif /* IDENavigatorGroup_h */
