//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDENICFilterProxy_h
#define IDENICFilterProxy_h
#import <Foundation/Foundation.h>

#include "IDENavigableItem.h"

@class NSHashTable;

@interface IDENICFilterProxy : IDENavigableItem

@property (readonly) NSHashTable *rootItems;

/* instance methods */
- (id)initWithRepresentedObject:(id)object;
- (void)_setItems:(id)items;
- (id)description;
- (BOOL)isLeaf;
- (id)childItems;
- (id)_childItems;
- (BOOL)_alwaysBypassFilter;
@end

#endif /* IDENICFilterProxy_h */
