//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDENavigatorChooserView_h
#define IDENavigatorChooserView_h
#import <Foundation/Foundation.h>

#include "DVTStructuredLayoutView.h"
#include "IDENavigatorChoice.h"

@protocol IDEKit_IDENavigatorChooserViewDelegate;
@class NSArray;

@interface IDENavigatorChooserView : DVTStructuredLayoutView { // (Swift)
  /* instance variables */
   void *buttons;
   void *stackView;
}

@property (nonatomic, weak) NSObject<IDEKit_IDENavigatorChooserViewDelegate> *delegate;
@property (nonatomic, copy) NSArray *choices;
@property (nonatomic, retain) IDENavigatorChoice *selectedChoice;

/* instance methods */
- (void)dvt_configureSubviewsBeforeSubviewLayout;
- (void)dvt_positionSubviewsAndSizeSelfAfterSubviewLayout;
- (void)clickedButton:(id)button;
- (id)choiceWithRepresentedObject:(id)object;
- (id)initWithFrame:(struct CGRect)frame;
- (id)initWithCoder:(id)coder;
@end

#endif /* IDENavigatorChooserView_h */
