//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDENavigableItemAsyncFilteringCoordinator_h
#define IDENavigableItemAsyncFilteringCoordinator_h
#import <Foundation/Foundation.h>

#include "IDENavigableItemFilteringCoordinator.h"

@class DVTTimeSlicedMainThreadWorkQueue, NSMutableDictionary;

@interface IDENavigableItemAsyncFilteringCoordinator : IDENavigableItemFilteringCoordinator {
  /* instance variables */
  int _currentFilteringGeneration;
  NSMutableDictionary *_filteringProxiesByKey;
}

@property (readonly) DVTTimeSlicedMainThreadWorkQueue *itemsToFilterQueue;
@property (readonly) DVTTimeSlicedMainThreadWorkQueue *itemsToInvalidateChildArrangedItemsQueue;

/* class methods */
+ (id)keyPathsForValuesAffectingPerformingFiltering;

/* instance methods */
- (id)_filteringProxiesByKey;
- (id)_filteredItemProxyForItems:(id)items;
- (void)_setFilteredItemProxy:(id)proxy forKey:(id)key;
- (id)_filteredItemProxyForKey:(id)key;
- (id)init;
- (void)primitiveInvalidate;
- (void)suspendFiltering;
- (void)resumeFiltering;
- (void)_stopAllWork;
- (void)_filterDidChange;
- (int)_filterCurrentGeneration;
- (BOOL)performingFiltering;
- (void)_beginFilteringFrom:(id)from;
- (void)_performFilterEvaluationOfItem:(id)item;
- (void)_performFilterEvaluationOfRepresentedObject:(id)object;
- (id)_arrangeItems:(id)items ofItem:(id)item;
- (void)_itemInvalidateMatchState:(id)state;
- (void)_invalidateArrangedChildrenOfFilterProxies;
- (void)_markItem:(id)item matches:(BOOL)matches;
- (void)_invalidateParentsChildrenOf:(id)of;
- (void)_handleItemsPropertiesDidChange:(id)change;
- (void)_handleObjectGraphDidChange:(id)change;
@end

#endif /* IDENavigableItemAsyncFilteringCoordinator_h */
