//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEOverridingBuildProperties_h
#define IDEOverridingBuildProperties_h
#import <Foundation/Foundation.h>

@class DVTFilePath, DVTMacroDefinitionTable, NSArray, NSMutableDictionary;

@interface IDEOverridingBuildProperties : NSObject {
  /* instance variables */
  NSMutableDictionary *_macros;
  NSMutableDictionary *_paths;
  NSArray *_arrayRepresentation;
  unsigned long long _hash;
}

@property (readonly, copy) DVTMacroDefinitionTable *synthesizedMacros;
@property (readonly, copy) DVTMacroDefinitionTable *macrosFromCommandLine;
@property (readonly, copy) DVTMacroDefinitionTable *macrosFromCommandLineXcconfigFile;
@property (readonly, copy) DVTMacroDefinitionTable *macrosFromEnvironmentXcconfigFile;
@property (readonly, copy) DVTFilePath *commandLineXcconfigFilePath;
@property (readonly, copy) DVTFilePath *environmentXcconfigFilePath;
@property (readonly) NSArray *macroDefinitionTables;

/* instance methods */
- (id)init;
- (id)initWithMacroDefinitionTable:(id)table;
- (id)copyWithSynthesizedMacros:(id)macros;
- (id)_copyUsingOverridingPropertiesClass:(Class)class synthesizedMacros:(id)macros;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)mutableCopyWithZone:(struct _NSZone *)zone;
- (id)macroDefinitionTableForLevel:(int)level;
- (void)_setMacroDefinitionTable:(id)table forLevel:(int)level;
- (id)xcconfigFilePathForLevel:(int)level;
- (void)_setXcconfigFilePath:(id)path forLevel:(int)level;
- (BOOL)isEmpty;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)description;
- (id)dvt_detailedDebugDescription;
@end

#endif /* IDEOverridingBuildProperties_h */
