//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEProvisioningErrorProvider_Protocol_h
#define IDEProvisioningErrorProvider_Protocol_h
#import <Foundation/Foundation.h>

@protocol IDEProvisioningErrorProvider 

@property (readonly, nonatomic) long long environment;
@property (readonly, nonatomic) long long task;
@property (readonly, nonatomic) long long repairMode;

/* instance methods */
- (id)userActionError:(id)error;
- (id)accountLogInFailureError:(id)error;
- (id)provisionableUnknownProvisioningFailureError:(id)error;
- (id)provisionableMissingBundleIdentifierError:(id)error;
- (id)provisionableMissingTeamSelectionError:(id)error;
- (id)provisionableMissingTeamSelectionForProfileSpecifierError:(id)error profileSpecifier:(id)specifier;
- (id)provisionableMissingTeamOrProfileSelectionError:(id)error;
- (id)noProfileTypeErrorForPlatform:(id)platform purpose:(id)purpose;
- (id)provisionableHasProfileSpecifiedInAutomaticError:(id)error profileName:(id)name;
- (id)provisionableHasExplicitSigningIdentitySpecifiedInAutomaticError:(id)error signingIdentity:(id)identity automaticSelector:(id)selector;
- (id)provisionableProfileTypeDoesntMatchIdentitySelectorError:(id)error signingIdentity:(id)identity automaticSelector:(id)selector;
- (id)provisionableNoProfileSpecifiedError:(id)error requiredFeatureNames:(id)names;
- (id)provisionableProfileSpecifiedButUnsupportedError:(id)error profileName:(id)name;
- (id)provisionableUnknownPlatformError:(id)error;
- (id)provisionableEntitlementsFileNotFoundError:(id)error entitlementsFilePath:(id)path;
- (id)provisionableHasConflictingAutomaticSigningSettingsError:(id)error conflictingFeatures:(id)features;
- (id)provisionableEntitlementsRequireSigningError:(id)error;
- (id)provisionableEntitlementsRequireProfileError:(id)error;
- (id)provisionableEntitlementsRequireDevelopmentSigning:(id)signing certificateIdentifier:(id)identifier sdk:(id)sdk;
- (id)provisionablePlatformMismatchForAssetError:(id)error assetType:(id)type platformName:(id)name;
- (id)provisionableUnableToRepairEntitlementsError:(id)error entitlements:(id)entitlements;
- (id)noAccountsError;
@end

#endif /* IDEProvisioningErrorProvider_Protocol_h */
