//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEProvisioningRepairStepGenerator_h
#define IDEProvisioningRepairStepGenerator_h
#import <Foundation/Foundation.h>

@interface IDEProvisioningRepairStepGenerator : NSObject

@property BOOL runningInIDE;

/* class methods */
+ (id)generatorForProvisioningStyle:(long long)style runningInIDE:(BOOL)ide;
+ (id)generatorForProvisioningStyle:(long long)style;

/* instance methods */
- (id)initForProvisioningStyle:(long long)style;
- (id)stepsWithSession:(id)session context:(id)context userAction:(id *)action error:(id *)error;
@end

#endif /* IDEProvisioningRepairStepGenerator_h */
