//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEProvisioningMechanicContext_h
#define IDEProvisioningMechanicContext_h
#import <Foundation/Foundation.h>

#include "DVTInvalidation-Protocol.h"
#include "IDEProvisioningMechanic.h"
#include "IDEProvisioningMechanicContextProvider-Protocol.h"
#include "IDEProvisioningTeamAccountPairProvider-Protocol.h"

@class DVTStackBacktrace, NSString, IDEProvisioningMechanic;

@interface IDEProvisioningMechanicContext : NSObject<DVTInvalidation>

@property (retain, nonatomic) IDEProvisioningMechanic *mechanic;
@property (retain, nonatomic) NSObject<IDEProvisioningMechanicContextProvider> *provisioningManager;
@property (retain, nonatomic) NSObject<IDEProvisioningTeamAccountPairProvider> *teamAccountPairProvider;
@property (nonatomic) BOOL runningInIDE;
@property (readonly, nonatomic) BOOL allowMutatingPortalAppIDs;
@property (readonly, nonatomic) BOOL valid;
@property (readonly) DVTStackBacktrace *invalidationBacktrace;
@property (retain) DVTStackBacktrace *creationBacktrace;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)initialize;

/* instance methods */
- (id)initWithAllowMutatingPortalAppIDs:(BOOL)ids;
- (void)primitiveInvalidate;
- (id)makeRepairForRepairable:(id)repairable;
@end

#endif /* IDEProvisioningMechanicContext_h */
