//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEProgressSearchField_h
#define IDEProgressSearchField_h
#import <Foundation/Foundation.h>

#include "DVTFindPatternSearchField.h"
#include "DVTInvalidation-Protocol.h"
#include "IDEProgressSearchSuggestionItem.h"

@class DVTStackBacktrace, NSArray, NSString, NSTableColumn, NSTableView, NSWindow, _IDEProgressSearchFieldCell;
@protocol IDEProgressSearchFieldCommandDelegate, IDEProgressSearchFieldDelegate;

@interface IDEProgressSearchField : DVTFindPatternSearchField<DVTInvalidation> {
  /* instance variables */
  NSString *_sanitizedSuggestionString;
  NSTableView *_suggestionTableView;
  NSTableColumn *_suggestionTitleColumn;
  NSWindow *_suggestionWindow;
}

@property (readonly) NSArray *allVisibleSuggestions;
@property (readonly) _IDEProgressSearchFieldCell *cell;
@property (copy, nonatomic) NSArray *suggestionItems;
@property (readonly) BOOL suggestionsVisible;
@property (retain) IDEProgressSearchSuggestionItem *selectedSuggestionItem;
@property (retain) NSObject<IDEProgressSearchFieldCommandDelegate> *commandDelegate;
@property (retain) NSObject<IDEProgressSearchFieldDelegate> *searchFieldDelegate;
@property (readonly, nonatomic) BOOL valid;
@property (readonly) DVTStackBacktrace *invalidationBacktrace;
@property (retain) DVTStackBacktrace *creationBacktrace;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)initialize;
+ (Class)cellClass;

/* instance methods */
- (id)initWithCoder:(id)coder;
- (id)initWithFrame:(struct CGRect)frame;
- (void)primitiveInvalidate;
- (void)ide_progressSearchField_setup;
- (void)observeValueForKeyPath:(id)path ofObject:(id)object change:(id)change context:(void *)context;
- (void)showSuggestions;
- (void)hideSuggestions;
- (void)controlTextDidEndEditing:(id)editing;
- (void)controlTextDidChange:(id)change;
- (BOOL)textView:(id)view doCommandBySelector:(SEL)selector;
- (void)_refreshTable;
- (void)_generateMenuWindow;
- (void)_updateMenu;
- (void)_controlTextDidChange:(id)change;
- (void)_selectionMade:(id)made;
- (long long)numberOfRowsInTableView:(id)view;
- (BOOL)tableView:(id)view shouldSelectRow:(long long)row;
- (id)tableView:(id)view objectValueForTableColumn:(id)column row:(long long)row;
- (void)tableView:(id)view willDisplayCell:(id)cell forTableColumn:(id)column row:(long long)row;
- (id)tableView:(id)view dataCellForTableColumn:(id)column row:(long long)row;
@end

#endif /* IDEProgressSearchField_h */
