//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEProvisioningLedger_h
#define IDEProvisioningLedger_h
#import <Foundation/Foundation.h>

#include "IDEProvisioningLedgerDelegate-Protocol.h"

@class NSMutableArray;

@interface IDEProvisioningLedger : NSObject {
  /* instance variables */
  NSMutableArray *_entries;
}

@property (weak, nonatomic) NSObject<IDEProvisioningLedgerDelegate> *delegate;

/* instance methods */
- (id)init;
- (id)openLedgerEntryForRepresentedObject:(id)object logAspect:(id)aspect;
- (void)provisioningLedgerEntry:(id)entry didOpenSubentry:(id)subentry;
- (void)provisioningLedgerEntry:(id)entry didCloseSubentry:(id)subentry withError:(id)error;
- (void)provisioningLedgerEntry:(id)entry didRecordDetails:(id)details;
- (void)provisioningLedgerEntryDidClose:(id)close withError:(id)error;
@end

#endif /* IDEProvisioningLedger_h */
