//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDERunOperationWorker_h
#define IDERunOperationWorker_h
#import <Foundation/Foundation.h>

@class DVTDispatchLock, DVTObservingToken, DVTStackBacktrace, NSString, IDEExecutionRunnableTracker, IDERunOperationWorkerGroup, IDELaunchSessionLogSection;

@interface IDERunOperationWorker : NSObject<DVTInvalidation> {
  /* instance variables */
  IDERunOperationWorkerGroup *_workerGroup;
  DVTObservingToken *_runnablePIDOberverToken;
  double _preflightAttemptInterval;
  BOOL _hasPerformedWorkerAction;
  DVTDispatchLock *_hasPerformedWorkerActionLock;
  unsigned long long _startTimeMonotonicNS;
}

@property (retain) IDELaunchSession *launchSession;
@property (readonly) NSString *extensionIdentifier;
@property (retain, nonatomic) IDEExecutionRunnableTracker *runnableTracker;
@property BOOL isLongTerm;
@property (nonatomic) unsigned long long preflightRetryAttempts;
@property (retain, nonatomic) IDELaunchSessionLogSection *logSection;
@property (readonly, nonatomic) BOOL valid;
@property (readonly) DVTStackBacktrace *invalidationBacktrace;
@property (retain) DVTStackBacktrace *creationBacktrace;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)initialize;

/* instance methods */
- (id)init;
- (id)initWithExtensionIdentifier:(id)identifier launchSession:(id)session;
- (id)workerGroup;
- (void)setWorkerGroup:(id)group;
- (void)startNextWorkerFromCompletedWorker:(id)worker error:(id)error;
- (BOOL)preflightWithError:(id *)error recoverable:(BOOL *)recoverable shouldRetry:(BOOL *)retry;
- (void)performWorkerAction;
- (void)performPostLaunchActions;
- (void)_startWithRetrying:(BOOL *)retrying;
- (void)start;
- (void)recoveredFromPreflightError;
- (void)rerunPreflight;
- (id)reportCompletionToAnalyticsWithError:(id)error;
- (void)finishRunnableTrackingWithAnalyticsAndError:(id)error;
- (void)finishedWithError:(id)error;
- (id)notFinishedReasonWithDepth:(unsigned long long)depth;
- (void)terminate;
- (void)createLogSection;
- (id)logSectionTitle;
- (id)logSectionDetails;
- (id)formattedLaunchParameters;
- (void)logUsingExistingApplicationInstance;
- (void)logLaunchingApplication;
- (void)logLaunchApplicationFinishedWithError:(id)error;
- (void)logInstallingApplication;
- (void)logInstallApplicationFinishedWithError:(id)error;
- (void)logInstallingWatchApplication;
- (void)logInstallWatchApplicationFinishedWithError:(id)error;
- (void)primitiveInvalidate;
@end

#include "DVTInvalidation-Protocol.h"
#include "IDEExecutionRunnableTracker.h"
#include "IDELaunchSession.h"
#include "IDELaunchSessionLogSection.h"
#include "IDERunOperationWorkerGroup.h"

#endif /* IDERunOperationWorker_h */
