//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDERunDestinationScheme_Protocol_h
#define IDERunDestinationScheme_Protocol_h
#import <Foundation/Foundation.h>

@protocol IDERunDestinationScheme 

@property (readonly) NSString *name;
@property (readonly) BOOL isTransient;
@property (readonly) BOOL schemeRunnableIsForWatch;
@property (readonly) BOOL schemeRunnableIsForWatchInternal;

/* instance methods */
- (BOOL)schemeRunnableRequiresPairedProxyForDevice:(id)device;
- (id)runnableForSchemeCommand:(id)command;
- (id)buildConfigurationForSchemeCommand:(id)command;
- (id)buildablesForSchemeCommand:(id)command includingDependencies:(BOOL)dependencies;
- (id)primaryBuildablesForSchemeCommand:(id)command;
@end

#endif /* IDERunDestinationScheme_Protocol_h */
