//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDERunContextManager_h
#define IDERunContextManager_h
#import <Foundation/Foundation.h>

#include "DVTCancellable-Protocol.h"
#include "DVTInvalidation-Protocol.h"
#include "IDERunDestination.h"
#include "IDEScheme.h"
#include "IDEWorkspace.h"

@class DVTObservingToken, DVTStackBacktrace, NSArray, NSCountedSet, NSMapTable, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString;

@interface IDERunContextManager : NSObject<DVTInvalidation> {
  /* instance variables */
  NSMutableSet *_customDataStores;
  NSMapTable *_storeToSpecifierMap;
  NSMapTable *_storeToUserDataMap;
  NSMutableArray *_ignoredChangesDevices;
  BOOL _isSchemeForcedSwitchEvent;
  BOOL _bulkChangingBlueprints;
  BOOL _blueprintChangedDuringBulkChanges;
  BOOL _suppressingAutocreation;
  DVTObservingToken *_customDataStoresObserver;
  DVTObservingToken *_availableDevicesObserver;
  NSObject<DVTInvalidation> *_blueprintDidChangeObserver;
  NSObject<DVTCancellable> *_installablePlatformObserver;
  NSMutableDictionary *_placeholderDevicesToWatchFor;
}

@property (retain) DVTObservingToken *workspaceReferenceContainersObservingToken;
@property (readonly) NSCountedSet *schemeNameCounts;
@property (readonly) IDEWorkspace *workspace;
@property (readonly) NSArray *runContexts;
@property (readonly) NSArray *nonTransientRunContexts;
@property (retain, nonatomic) IDEScheme *activeRunContext;
@property (retain, nonatomic) IDERunDestination *activeRunDestination;
@property (nonatomic) unsigned long long rosettaDestinationVisibility;
@property (readonly) NSArray *missingPlatformsForActiveBuildConfiguration;
@property (readonly, nonatomic) BOOL valid;
@property (readonly) DVTStackBacktrace *invalidationBacktrace;
@property (retain) DVTStackBacktrace *creationBacktrace;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (unsigned long long)assertionBehaviorForKeyValueObservationsAtEndOfEvent;
+ (void)initialize;
+ (id)keyPathsForValuesAffectingNonTransientRunContexts;
+ (BOOL)automaticallyNotifiesObserversOfActiveRunContext;
+ (BOOL)automaticallyNotifiesObserversOfActiveRunDestination;
+ (id)observeAllBlueprintChangesOnQueue:(id)queue withBlock:(id /* block */)block;
+ (id)observeAllBlueprintChangesOnQueue:(id)queue withTarget:(id)target selector:(SEL)selector;
+ (void)postBlueprintsDidChange:(id)change;
+ (void)postBlueprintsDidChangeWithBlueprintSet:(id)set;

/* instance methods */
- (id)init;
- (id)initWithWorkspace:(id)workspace;
- (void)primitiveInvalidate;
- (void)_addScheme:(id)scheme;
- (void)_updateMap:(id)map contextForCustomDataStore:(id)store specifier:(id)specifier;
- (void)_restoreActiveRunContextIfPossible;
- (void)_restoreActiveRunDestinationIfPossibleForScheme:(id)scheme;
- (void)_ensureActiveRunContext;
- (void)_startUpdatingRunContexts;
- (void)_finishUpdatingRunContexts;
- (void)_customDataStoresDidUpdate;
- (id)_schemesInvolvingBuildables:(id)buildables excludingContexts:(id)contexts;
- (void)suppressAutocreationForBuildables:(id)buildables;
- (void)allowAutocreationForBuildables:(id)buildables;
- (void)_setAutocreationSuppressed:(BOOL)suppressed forBuildables:(id)buildables;
- (void)_setAutocreationSuppressed:(BOOL)suppressed forBuildables:(id)buildables returningStoresNeedingSave:(id *)save;
- (id)_uniqueSpecifierForSpecifier:(id)specifier inMap:(id)map;
- (void)_addContext:(id)context specifierToRunContextMap:(id)map;
- (id)_newSchemeWithCustomDataStore:(id)store customDataSpecifier:(id)specifier orderHint:(unsigned long long)hint allowSavingState:(BOOL)state schemeCreationBlock:(id /* block */)block;
- (id)newSchemeWithCustomDataStore:(id)store customDataSpecifier:(id)specifier orderHint:(unsigned long long)hint;
- (id)newTransientSchemeWithCustomDataStore:(id)store customDataSpecifier:(id)specifier orderHint:(unsigned long long)hint;
- (id)duplicateRunContext:(id)context withCustomDataSpecifier:(id)specifier completionQueue:(id)queue completionBlock:(id /* block */)block;
- (id)importRunContextAtURL:(id)url withCustomDataStore:(id)store customDataSpecifier:(id)specifier orderHint:(unsigned long long)hint completionQueue:(id)queue completionBlock:(id /* block */)block;
- (void)deleteRunContexts:(id)contexts completionQueue:(id)queue completionBlock:(id /* block */)block;
- (void)moveRunContext:(id)context toCustomDataStore:(id)store customDataSpecifier:(id)specifier completionQueue:(id)queue completionBlock:(id /* block */)block;
- (id)_contextUserStateKeyForSpecifier:(id)specifier;
- (id)_contextUserStateDictForCustomDataStore:(id)store createIfNeeded:(BOOL)needed;
- (id)_contextUserStateForCustomDataStore:(id)store specifier:(id)specifier createIfNeeded:(BOOL)needed;
- (void)_lookupIsShown:(BOOL *)shown orderHint:(unsigned long long *)hint forCustomDataStore:(id)store specifier:(id)specifier;
- (void)saveRunContextManagementDictionaryForStore:(id)store;
- (id)runContextManagementDictionaryForStore:(id)store;
- (void)_updateIsShown:(BOOL)shown forRunContext:(id)context;
- (void)_updateOrderHint:(unsigned long long)hint forRunContext:(id)context allowSavingState:(BOOL)state;
- (BOOL)_rosettaVisibilityShowAllOverrideIsEnabled;
- (void)shouldIgnoreDeviceChangesWillBegin:(id)begin;
- (void)shouldIgnoreDeviceChangesDidEnd:(id)end;
- (void)_invalidateActiveRunDestination;
- (void)_invalidateActiveRunDestinationDueToDeviceAvailable:(id)available;
- (BOOL)_switchToRunDestinationWithDeviceIdentifier:(id)identifier inRunDestinations:(id)destinations;
- (void)_invalidateAvailableRunDestinationsForSchemes:(id)schemes;
- (void)_invalidateAvailableRunDestinations;
- (id)_preferredDestinationForRunDestination:(id)destination inDestinations:(id)destinations;
- (void)deviceUsabilityDidChange:(id)change;
- (void)blueprintsDidChange:(id)change;
- (void)blueprintsWillBulkChange:(id)change;
- (void)blueprintsDidBulkChange:(id)change;
- (void)setActiveRunContext:(id)context andRunDestination:(id)destination;
- (void)switchToRunDestinationOnceAvailableMatchingDeviceIdentifier:(id)identifier forSuggestion:(id)suggestion;
- (id)recentSchemes;
- (void)clearRecentSchemes;
- (id)recentRunDestinationsForScheme:(id)scheme;
- (void)clearRecentRunDestinations;
@end

#endif /* IDERunContextManager_h */
