//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDERuntimeProfileInfo_h
#define IDERuntimeProfileInfo_h
#import <Foundation/Foundation.h>

@class NSMapTable;
@protocol OS_dispatch_queue;

@interface IDERuntimeProfileInfo : NSObject

@property (retain) NSObject<OS_dispatch_queue> *queue;
@property (readonly) NSMapTable *pathsForRunnableInfosByDevice;

/* instance methods */
- (id)init;
- (void)trackPath:(id)path forBundleID:(id)id runnableLocation:(id)location onDevice:(id)device;
@end

#endif /* IDERuntimeProfileInfo_h */
