//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDERunContextRecents_h
#define IDERunContextRecents_h
#import <Foundation/Foundation.h>

@class NSMutableDictionary;

@interface IDERunContextRecents : NSObject

@property (retain) NSMutableDictionary *recentSchemeTimes;
@property (retain) NSMutableDictionary *recentRunDestinationTimes;
@property (retain) NSMutableDictionary *lastUsedRunDestination;

/* instance methods */
- (id)init;
- (void)_validateUnarchivedRecents;
- (void)_purgeItemsOlderThanThreshold:(double)threshold;
- (double)_defaultThreshold;
- (id)initWithPlistRepresentation:(id)representation;
- (id)plistRepresentation;
- (id)orderedRecentSchemesForRunContextManager:(id)manager;
- (void)setCurrentScheme:(id)scheme;
- (void)schemeDidChangeNameFromOldName:(id)name toNewName:(id)name;
- (void)clearRecentSchemes;
- (void)clearSchemeHistory:(id)history;
- (void)setCurrentRunDestination:(id)destination activeScheme:(id)scheme;
- (id)orderedRecentRunDestinationsForScheme:(id)scheme;
- (id)lastUsedRunDestinationIfAvailableForScheme:(id)scheme;
- (void)clearRecentRunDestinations;
@end

#endif /* IDERunContextRecents_h */
