//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDESchemeActionPlatformRecord_h
#define IDESchemeActionPlatformRecord_h
#import <Foundation/Foundation.h>

@class NSDictionary, NSString;

@interface IDESchemeActionPlatformRecord : NSObject

@property (readonly, copy) NSDictionary *dictionaryRepresentation;
@property (readonly, copy) NSString *userDescription;
@property (readonly, copy) NSString *identifier;

/* instance methods */
- (id)initWithUserDescription:(id)description identifier:(id)identifier;
@end

#endif /* IDESchemeActionPlatformRecord_h */
