//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDESchemeActionDeviceRecord_h
#define IDESchemeActionDeviceRecord_h
#import <Foundation/Foundation.h>

#include "IDESchemeActionAnalytics-Protocol.h"
#include "IDESchemeActionPlatformRecord.h"

@class NSDictionary, NSString;

@interface IDESchemeActionDeviceRecord : NSObject<IDESchemeActionAnalytics>

@property (readonly, copy) NSDictionary *dictionaryRepresentation;
@property (readonly, copy) NSString *name;
@property (readonly) BOOL concreteDevice;
@property (readonly, copy) NSString *operatingSystemVersion;
@property (readonly, copy, nonatomic) NSString *operatingSystemVersionWithBuildNumber;
@property (readonly, copy, nonatomic) NSString *operatingSystemBuildNumber;
@property (readonly, copy) NSString *nativeArchitecture;
@property (readonly, copy, nonatomic) NSString *modelName;
@property (readonly, copy, nonatomic) NSString *modelCode;
@property (readonly, copy, nonatomic) NSString *modelUTI;
@property (readonly, copy) NSString *identifier;
@property (readonly) BOOL isWireless;
@property (readonly) BOOL isCloudDevice;
@property (readonly) BOOL isCoreDevice;
@property (copy) NSString *cpuKind;
@property unsigned long long cpuCount;
@property unsigned long long cpuSpeedInMHz;
@property unsigned long long busSpeedInMHz;
@property unsigned long long ramSizeInMegabytes;
@property unsigned long long physicalCPUCoresPerPackage;
@property unsigned long long logicalCPUCoresPerPackage;
@property (readonly, nonatomic) IDESchemeActionPlatformRecord *platformRecord;
@property (readonly) NSDictionary *analyticsDictionary;

/* instance methods */
- (id)initWithDeviceName:(id)name isConcreteDevice:(BOOL)device nativeArchitecture:(id)architecture operatingSystemVersion:(id)version operatingSystemVersionWithBuildNumber:(id)number modelName:(id)name modelCode:(id)code modelUTI:(id)uti identifier:(id)identifier isWireless:(BOOL)wireless isCloudDevice:(BOOL)device isCoreDevice:(BOOL)device cpuKind:(id)kind cpuCount:(unsigned long long)count cpuSpeedInMHz:(unsigned long long)mhz busSpeedInMHz:(unsigned long long)mhz ramSizeInMegabytes:(unsigned long long)megabytes physicalCPUCoresPerPackage:(unsigned long long)package logicalCPUCoresPerPackage:(unsigned long long)package platformRecord:(id)record;
- (id)initWithDeviceName:(id)name isConcreteDevice:(BOOL)device nativeArchitecture:(id)architecture operatingSystemVersion:(id)version operatingSystemVersionWithBuildNumber:(id)number modelName:(id)name modelCode:(id)code modelUTI:(id)uti identifier:(id)identifier isWireless:(BOOL)wireless cpuKind:(id)kind cpuCount:(unsigned long long)count cpuSpeedInMHz:(unsigned long long)mhz busSpeedInMHz:(unsigned long long)mhz ramSizeInMegabytes:(unsigned long long)megabytes physicalCPUCoresPerPackage:(unsigned long long)package logicalCPUCoresPerPackage:(unsigned long long)package platformRecord:(id)record;
- (id)initWithDevice:(id)device;
- (BOOL)isConcreteDevice;
@end

#endif /* IDESchemeActionDeviceRecord_h */
