//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDESwiftMigrationAssistantContext_h
#define IDESwiftMigrationAssistantContext_h
#import <Foundation/Foundation.h>

#include "IDEMigrationAssistantContext.h"

@class DVTFilePath, NSArray, NSMutableArray, NSURL;

@interface IDESwiftMigrationAssistantContext : IDEMigrationAssistantContext {
  /* instance variables */
  long long _numIncompatibilityErrors;
}

@property (readonly, copy) NSArray *targets;
@property BOOL remindMe;
@property (copy) NSArray *selectedTargets;
@property (readonly, copy) NSMutableArray *mutableSelectedTargets;
@property (readonly) DVTFilePath *migrationBuildFolder;
@property long long numberOfIncompatibilityErrors;
@property unsigned long long currentConversionStage;
@property (retain) NSURL *savedPlaygroundURL;
@property (copy) NSArray *migrationBuildOptions;

/* class methods */
+ (void)initialize;
+ (Class)migrationContextClass;

/* instance methods */
- (id)init;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)setWorkspaceTabController:(id)controller;
- (void)reopenPlaygroundIfNecessary;
- (void)beginPerformingContextTask;
- (void)endPerformingContextTask;
@end

#endif /* IDESwiftMigrationAssistantContext_h */
