//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDESearchFilterControlBar_h
#define IDESearchFilterControlBar_h
#import <Foundation/Foundation.h>

#include "DVTFilterControlBar.h"

@class DVTSearchField, NSMenu;

@interface IDESearchFilterControlBar : DVTFilterControlBar

@property (readonly) DVTSearchField *filterControlField;
@property (copy) NSMenu *searchMenuTemplate;

/* instance methods */
- (void)_updateCellForSearchField:(id)field;
- (id)_filterControlFieldWithFrame:(struct CGRect)frame;
@end

#endif /* IDESearchFilterControlBar_h */
