//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDESourceControlManager_h
#define IDESourceControlManager_h
#import <Foundation/Foundation.h>

#include "_TtC13IDEFoundation30IDESourceControlAccountManager.h"
#include "_TtC13IDEFoundation34IDESourceControlFingerprintManager.h"

@class NSArray, NSMutableArray, NSNumber, NSOperationQueue, NSString;
@protocol OS_dispatch_queue;

@interface IDESourceControlManager : NSObject {
  /* instance variables */
  NSMutableArray *_registeredWorkspaces;
  NSObject<OS_dispatch_queue> *_registeredWorkspacesDispatchQueue;
  NSOperationQueue *_operationQueue;
  long long _maxConcurrentOperationCount;
  NSObject<OS_dispatch_queue> *_legacyWorkingTreesDispatchQueue;
}

@property BOOL waitingForAuthentication;
@property (retain) NSNumber *enableSourceControlOverride;
@property (readonly) BOOL shouldLoadAccounts;
@property (readonly) NSArray *legacyWorkingTrees;
@property (readonly) IDEFoundation_IDESourceControlAccountManager *accountManager;
@property (readonly) IDEFoundation_IDESourceControlFingerprintManager *fingerprintManager;
@property BOOL enableSourceControl;
@property BOOL showChangeBar;
@property BOOL showUpstreamChangesInChangeBar;
@property BOOL localStatusCheckingEnabled;
@property BOOL remoteStatusCheckingEnabled;
@property BOOL automaticallyAddNewFiles;
@property BOOL preselectCommitSheetFiles;
@property BOOL showMergeCommits;
@property (readonly) NSString *initialBranchName;
@property (readonly) NSArray *workingCopies;
@property (readonly) double minimumLocalStatusRequestDelay;

/* class methods */
+ (id)sharedSourceControlManager;
+ (id)sharedSourceControlManagerInstantiatingIfNeeded:(BOOL)needed;
+ (id)sourceControlLogAspect;
+ (id)sourceControlFileStatusLogAspect;
+ (id)sourceControlReachabilityLogAspect;
+ (id)sourceControlFileScanningLogAspect;
+ (id)sourceControlAuthenticationLogAspect;
+ (id)sourceControlProfilingLogAspect;
+ (BOOL)enableLoadingAccounts;
+ (void)setEnableLoadingAccounts:(BOOL)accounts;
+ (BOOL)disableLoadingAccounts;
+ (void)setDisableLoadingAccounts:(BOOL)accounts;
+ (BOOL)isSourceControlEnabled;
+ (id)keyPathsForValuesAffectingRepositories;

/* instance methods */
- (id)initWithSavedAccounts:(BOOL)accounts;
- (id)initWithSavedAccounts:(BOOL)accounts credentialsManager:(id)manager userDefaults:(id)defaults;
- (id)_blacklistedDirectories;
- (void)addLegacyWorkingTree:(id)tree;
- (void)asyncPerformBlockOnWorkingTreeQueue:(id /* block */)queue;
- (id)workingCopyForFilePath:(id)path;
- (void)registerWorkspace:(id)workspace;
- (void)unregisterWorkspace:(id)workspace;
- (id)workingTreeForFilePath:(id)path;
- (id)workingTreeAtFilePath:(id)path;
- (void)workingTreeForFilePath:(id)path completionBlock:(id /* block */)block;
@end

#endif /* IDESourceControlManager_h */
