//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22526.0.0.0.0
//
#ifndef IDEStructureEditing_Protocol_h
#define IDEStructureEditing_Protocol_h
#import <Foundation/Foundation.h>

@protocol IDEStructureEditing 
/* instance methods */
- (BOOL)allowUserModificationOfSubitems;
- (BOOL)canStructureEditInsertSubitems:(id)subitems atIndex:(unsigned long long)index;
- (id)structureEditInsertSubitems:(id)subitems atIndex:(unsigned long long)index;
- (BOOL)canStructureEditInsertFileURLs:(id)urls atIndex:(unsigned long long)index;
- (id)structureEditInsertFileURLs:(id)urls atIndex:(unsigned long long)index createGroupsForFolders:(BOOL)folders;
- (BOOL)canStructureEditSortSubitemsAtIndexes:(id)indexes sortStyle:(unsigned long long)style;
- (BOOL)structureEditSortSubitemsAtIndexes:(id)indexes sortStyle:(unsigned long long)style;
- (BOOL)canStructureEditRemoveSubitemsAtIndexes:(id)indexes;
- (BOOL)structureEditRemoveSubitemsAtIndexes:(id)indexes error:(id *)error;
- (BOOL)canStructureEditName;
- (BOOL)structureEditName:(id)name inContext:(id)context completionBlock:(id /* block */)block;
- (BOOL)allowRemovingContainerGroup;
- (BOOL)structureEditSetName:(id)name inContext:(id)context;
@optional
/* instance methods */
- (id)allowedFileTypesOfChildItems;
@end

#endif /* IDEStructureEditing_Protocol_h */
