//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
//


@class IDESelection, IDEWorkspaceTabController;

@protocol IDESelectionSource <NSObject>
@property(readonly, nonatomic) IDEWorkspaceTabController *workspaceTabController;
@property(readonly, copy) IDESelection *contextMenuSelection;
@property(readonly, copy) IDESelection *outputSelection;
@end

