//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDETextFragmentIndexRecordStorage_h
#define IDETextFragmentIndexRecordStorage_h
#import <Foundation/Foundation.h>

@interface IDETextFragmentIndexRecordStorage : NSObject {
  /* instance variables */
  id const * _locks[32];
  NSMutableDictionary * _entriesByFilePath[32];
}

/* instance methods */
- (id)init;
- (void)withAcessToStorageForFilePath:(id)path storage:(id /* block */)storage;
- (id)entryForFilePath:(id)path;
- (void)addEntry:(id)entry;
- (void)removeEntryForFilePath:(id)path;
- (void)withAllLocksBeginingAt:(long long)at invoke:(id /* block */)invoke;
- (void)withAllLocks:(id /* block */)locks;
- (void)removeAllEntriesWithAllLocksAlreadyHeld;
- (void)removeAllEntries;
- (void)resetToEntries:(id)entries;
- (id)snapshotOfEntries;
- (void)trimToEntriesForFilePaths:(id)paths;
@end

#endif /* IDETextFragmentIndexRecordStorage_h */
