//
//     Generated by class-dump 3.5-0.1.1 (64 bit) (forked by @manicmaniac).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
//

#include "Shared.h"


@class NSString;

@interface IDETabbedWindow : NSWindow <NSKeyedArchiverDelegate>
{
}

- (id)archiver:(id)arg1 willEncodeObject:(id)arg2;
- (id)dataByEncodingRestorableState;
- (void)restoreStateWithData:(id)arg1;
- (void)restoreStateWithCoder:(id)arg1;
- (void)closeOtherWindowTabs:(id)arg1;
- (id)currentlySelectedTabbedWindow;
@property(setter=setTabBarIsVisible:) BOOL tabBarIsVisible;
- (BOOL)validateMenuItem:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

