//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDETestRunSessionEvents_Protocol_h
#define IDETestRunSessionEvents_Protocol_h
#import <Foundation/Foundation.h>

@protocol IDETestRunSessionEvents <NSObject>
/* instance methods */
- (void)testRunSessionDidFinish:(id)finish withCancellation:(BOOL)cancellation;
- (void)testTargetRunnerDidStart:(id)start;
- (void)testTargetRunner:(id)runner didEndWithError:(id)error wasCanceled:(BOOL)canceled;
- (void)worker:(id)worker testTargetRunner:(id)runner didLaunchWithDiagnosticLogPath:(id)path;
- (void)worker:(id)worker testTargetRunner:(id)runner willFinishWithSuccess:(BOOL)success withError:(id)error;
- (void)worker:(id)worker testTargetRunner:(id)runner testSuiteWithIdentifier:(id)identifier didStartAt:(id)at rawOutput:(id)output;
- (void)worker:(id)worker testTargetRunner:(id)runner testSuiteWithIdentifier:(id)identifier willFinishAt:(id)at rawOutput:(id)output;
- (void)worker:(id)worker testTargetRunner:(id)runner testSuiteDidFinishWithRunCount:(unsigned long long)count skipCount:(unsigned long long)count failureCount:(unsigned long long)count expectedFailureCount:(unsigned long long)count uncaughtExceptionCount:(unsigned long long)count testDuration:(double)duration totalDuration:(double)duration rawOutput:(id)output;
- (void)worker:(id)worker testTargetRunner:(id)runner didStartTestWithIdentifier:(id)identifier withRawOutput:(id)output;
- (void)worker:(id)worker testTargetRunner:(id)runner testWithIdentifier:(id)identifier didMeasurePerformanceMetric:(id)metric rawOutput:(id)output;
- (void)worker:(id)worker testTargetRunner:(id)runner testWithIdentifier:(id)identifier willStartActivity:(id)activity;
- (void)worker:(id)worker testTargetRunner:(id)runner testWithIdentifier:(id)identifier didFinishActivity:(id)activity;
- (void)worker:(id)worker testTargetRunner:(id)runner testCaseWithIdentifier:(id)identifier didRecordIssue:(id)issue rawOutput:(id)output;
- (void)worker:(id)worker testTargetRunner:(id)runner testCaseWithIdentifier:(id)identifier didRecordExpectedFailure:(id)failure rawOutput:(id)output;
- (void)worker:(id)worker testTargetRunner:(id)runner didSkipTestWithIdentifier:(id)identifier withTestResultMessage:(id)message rawOutput:(id)output;
- (void)worker:(id)worker testTargetRunner:(id)runner didFinishTestWithIdentifier:(id)identifier withTestResult:(id)result rawOutput:(id)output;
- (void)worker:(id)worker testTargetRunner:(id)runner didUpdateAttachment:(id)attachment;
@end

#endif /* IDETestRunSessionEvents_Protocol_h */
