//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22517.0.0.0.0
//
#ifndef IDETestsInTestableObserver_Protocol_h
#define IDETestsInTestableObserver_Protocol_h
#import <Foundation/Foundation.h>

@protocol IDETestObserver;

@protocol IDETestsInTestableObserver <IDETestObserver>
/* instance methods */
- (void)testablesChanged:(id)changed;
@optional
/* instance methods */
- (void)testableChangedWithDifference:(id)difference;
- (void)testableChangedWithDifference:(id)difference;
@end

#endif /* IDETestsInTestableObserver_Protocol_h */
