//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22522.0.0.0.0
//
#ifndef IDEVariablesViewQuickLookProvider_Protocol_h
#define IDEVariablesViewQuickLookProvider_Protocol_h
#import <Foundation/Foundation.h>

@protocol IDEVariablesViewQuickLookProvider <NSObject>

@property (readonly) int loadedState;
@property (readonly) NSView *quickLookView;
@property (readonly) NSURL *existingURLToOpen;
@property (readonly) NSString *extensionForTemporaryFile;

/* instance methods */
- (id)initWithDataValue:(id)value options:(id)options;
- (void)cancelLoading;
@optional
/* instance methods */
- (id)dataRepresentation;
@end

#endif /* IDEVariablesViewQuickLookProvider_Protocol_h */
