//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEVariableViewRootNode_h
#define IDEVariableViewRootNode_h
#import <Foundation/Foundation.h>

#include "IDEVariablesViewNode.h"

@interface IDEVariableViewRootNode : IDEVariablesViewNode
/* instance methods */
- (id)initWithChildren:(id)children;
- (void)addChildNode:(id)node;
- (void)removeChildnode:(id)childnode;
- (id)name;
- (BOOL)hasChildren;
- (BOOL)childValuesCountValid;
@end

#endif /* IDEVariableViewRootNode_h */
