//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEVariablesViewQuickLookPopover_h
#define IDEVariablesViewQuickLookPopover_h
#import <Foundation/Foundation.h>

#include "IDEVariablesViewQuickLookProvider-Protocol.h"

@class DVTObservingToken, NSButton, NSImageView, NSLayoutConstraint, NSPopover, NSProgressIndicator, NSString, NSTextField, NSView, NSViewController;
@protocol IDEDataValue;

@interface IDEVariablesViewQuickLookPopover : NSViewController<NSPopoverDelegate> {
  /* instance variables */
  NSObject<IDEVariablesViewQuickLookProvider> *_quickLookProvider;
  DVTObservingToken *_quickLookProviderIsReadyObserver;
  BOOL _popoverIsAnimatingIn;
  BOOL _quickLookProviderDidFinishLoadingWasDeferred;
  int _openWithExternalEditorSupport;
}

@property (retain) NSObject<IDEDataValue> *dataValue;
@property (retain) NSView *defaultQuickLookView;
@property (retain) NSImageView *defaultQuickLookIcon;
@property (retain) NSViewController *quickLookProviderViewController;
@property (retain) NSImageView *quickLookViewIcon;
@property (retain) NSTextField *quickLookViewTitle;
@property (retain) NSButton *quickLookOpenWithEditorButton;
@property (retain) NSView *quickLookViewContainer;
@property (retain) NSView *quickLookTitleView;
@property (retain) NSProgressIndicator *progressIndicator;
@property (retain) NSLayoutConstraint *quickLookViewContainerDefaultWidth;
@property (retain) NSLayoutConstraint *quickLookViewContainerDefaultHeight;
@property (retain) NSLayoutConstraint *quickLookContainerViewTopSpaceConstraint;
@property (retain) NSView *errorView;
@property (retain) NSImageView *errorViewWarningIcon;
@property (retain) NSImageView *errorViewVariableTypeIcon;
@property (retain) NSTextField *errorViewVariableName;
@property (retain) NSTextField *errorMessageLabel;
@property (retain) NSPopover *popover;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (void)dealloc;
- (void)loadView;
- (void)useQuickLookProvider:(id)provider forDataValue:(id)value usingIcon:(id)icon;
- (void)_useQuickLookProvider:(id)provider forDataValue:(id)value usingIcon:(id)icon showTitleView:(BOOL)view;
- (void)_quickLookProviderDidFinishLoading;
- (struct CGRect)_maxContentSizeForQuickLookProvider;
- (void)_setupOpenWithExternalEditorButton;
- (id)_externalApplicationURL;
- (void)useDefaultQuickLookForDataValue:(id)value usingIcon:(id)icon;
- (void)useMessageFromError:(id)error forDataValueNamed:(id)named usingIcon:(id)icon;
- (void)_useErrorMessage:(id)message forDataValueNamed:(id)named usingIcon:(id)icon;
- (void)openWithEditor:(id)editor;
- (void)_writeToTemporaryURLThenOpenIt;
- (void)_openURLInExternalEditor:(id)editor;
- (id)_createNonExistentFilePath;
- (void)_cancelLoadingOfCurrentQuickLookProviderIfNecessary;
- (void)popoverWillShow:(id)show;
- (void)popoverDidShow:(id)show;
- (BOOL)popoverShouldClose:(id)close;
- (void)popoverDidClose:(id)close;
@end

#endif /* IDEVariablesViewQuickLookPopover_h */
