//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEWorkspaceNoticeSubsystem_h
#define IDEWorkspaceNoticeSubsystem_h
#import <Foundation/Foundation.h>

#include "_IDEWorkspaceBaseNoticeSubsystem.h"
#include "_TtP13IDEFoundation35IDENoticeExplorationContextProvider_-Protocol.h"

@interface IDEWorkspaceNoticeSubsystem : _IDEWorkspaceBaseNoticeSubsystem<IDEFoundation_IDENoticeExplorationContextProvider> { // (Swift)
  /* instance variables */
   void *collator;
   void *domainMembershipOrganizer;
   void *buildProvider;
   void *workspaceIntegrityProvider;
   void *runtimeNoticeProvider;
   void *anonymousProviders;
   void *debugRuntimeNoticeProviders;
   void *launchSessionIconsByProcessInfo;
   void *workspaceNoticeProviders;
   void *workspace;
   void *_documentProviderManager;
}

@property (nonatomic, readonly) BOOL areAnyNoticesPublished;

/* instance methods */
- (void)clearAllIssues;
- (void)clearAllBuildIssues;
- (id)observeIssuesChangedForPrimaryURLAndSecondaryURL:(id)url observeInitial:(BOOL)initial changeHandler:(id /* block */)handler;
- (void)setLaunchSessionRunnableIcon:(id)icon forLaunchSession:(id)session;
- (void)makeAllBuildProviderIssuesStaleForFilePath:(id)path;
- (void)makeAllIssuesStaleForFilePath:(id)path;
- (id)explorationContextFor:(id)forNot;
- (id)initWithWorkspace:(id)workspace;
- (void)registerProviders;
- (void)primitiveInvalidate;
- (id)init;
@end

#endif /* IDEWorkspaceNoticeSubsystem_h */
