//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEWorkspaceDesignAreaSplitViewController_h
#define IDEWorkspaceDesignAreaSplitViewController_h
#import <Foundation/Foundation.h>

#include "IDEWorkspaceTabController.h"

@interface IDEWorkspaceDesignAreaSplitViewController : NSSplitViewController

@property (weak, nonatomic) IDEWorkspaceTabController *workspaceTabController;

/* class methods */
+ (float)defaultSidebarHoldingPriority;
+ (float)resizingSidebarHoldingPriority;

/* instance methods */
- (void)setSplitView:(id)view;
- (void)insertSplitViewItem:(id)item atIndex:(long long)index;
- (void)splitViewWillBeginSplitResize:(id)resize;
- (void)splitViewDidEndSplitResize:(id)resize;
- (double)splitView:(id)view constrainSplitPosition:(double)position ofSubviewAt:(long long)at;
- (void)splitViewItem:(id)item didChangeCollapsed:(BOOL)collapsed animated:(BOOL)animated;
@end

#endif /* IDEWorkspaceDesignAreaSplitViewController_h */
