//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22551.0.0.0.0
//
#ifndef IDEWorkspace_h
#define IDEWorkspace_h
#import <Foundation/Foundation.h>

#include "IDEXMLPackageContainer.h"
#include "DVTInvalidation-Protocol.h"
#include "IDEActivityLogMessage.h"
#include "IDEActivityLogSection.h"
#include "IDEBlueprintProvider-Protocol.h"
#include "IDEBreakpointManager.h"
#include "IDEBuildNoticeLogRecord-Protocol.h"
#include "IDEBuildNoticeWorkspace-Protocol.h"
#include "IDEBuildParameters.h"
#include "IDEBuildSystemService-Protocol.h"
#include "IDEClientTracking-Protocol.h"
#include "IDEConcreteClientTracker.h"
#include "IDEContainerQuery.h"
#include "IDEDeviceInstallWorkspaceMonitor.h"
#include "IDEDynamicContentRootGroup.h"
#include "IDEExecutionEnvironment.h"
#include "IDEIndex.h"
#include "IDEIssueLogDataSource-Protocol.h"
#include "IDELaunchSessionLogReporter.h"
#include "IDELocalizationManager.h"
#include "IDELocalizationWorkspaceMonitor.h"
#include "IDELogManager.h"
#include "IDEProvisionableProvider-Protocol.h"
#include "IDEProvisioningManager.h"
#include "IDEProvisioningWorkspaceMonitor.h"
#include "IDEResultBundleURLRedirector.h"
#include "IDERunContextManager.h"
#include "IDESourceControlWorkspaceMonitor.h"
#include "IDETestManager.h"
#include "IDETestableDataSource_Index-Protocol.h"
#include "IDETestableDataSource_IndexProvider-Protocol.h"
#include "IDETextFragmentIndex.h"
#include "IDEWorkspace.h"
#include "IDEWorkspaceArena.h"
#include "IDEWorkspaceDelegate-Protocol.h"
#include "IDEWorkspaceNoticeSubsystem.h"
#include "IDEWorkspaceSharedSettings.h"
#include "IDEWorkspaceUpgradeTasksController.h"
#include "IDEWorkspaceUserSettings.h"
#include "_TtP13IDEFoundation32IDESchemeFileReference_Workspace_-Protocol.h"

@class DVTFilePath, DVTNotificationToken, DVTObservingToken, DVTStackBacktrace, IDERefactoring, NSArray, NSDictionary, NSHashTable, NSMapTable, NSMutableArray, NSMutableDictionary, NSMutableOrderedSet, NSMutableSet, NSNumber, NSSet, NSString, _TtC16DVTDocumentation23DVTDocumentationManager, DVTDocumentation_DVTDocumentationManager;
@protocol IDEActiveRunContextStoring, IDECustomDataStoring, IDEPackageManagerWorkspace;

@interface IDEWorkspace : IDEXMLPackageContainer<IDEFoundation_IDESchemeFileReference_Workspace, IDEBuildNoticeWorkspace, IDETestableDataSource_IndexProvider, IDEClientTracking, IDEProvisionableProvider, IDEIssueLogDataSource> {
  /* instance variables */
  NSString *_untitledName;
  DVTFilePath *_headerMapFilePath;
  IDEContainerQuery *_containerQuery;
  DVTObservingToken *_containerQueryObservingToken;
  NSHashTable *_fileRefsWithContainerLoadingIssues;
  NSObject<DVTInvalidation> *_analyzeContainerIntegrityToken;
  NSMapTable *_blueprintProviderObserverMap;
  NSMapTable *_blueprintProviderEditedObserverMap;
  IDEContainerQuery *_indexableSourceQuery;
  DVTObservingToken *_indexableSourceQueryObservingToken;
  NSMapTable *_observedIndexableSourcesToObservingTokensTable;
  NSMutableDictionary *_identifiersToIndexablesPendingRegistration;
  DVTNotificationToken *_buildSystemSettingsNotificationToken;
  DVTFilePath *_overridingBuildSystemDevDir;
  IDEContainer<IDECustomDataStoring> *_wrappedContainer;
  DVTObservingToken *_wrappedContainerValidObservingToken;
  DVTObservingToken *_newWrappedContainerObservingToken;
  NSHashTable *_pendingReferencedFileReferences;
  NSHashTable *_pendingReferencedContainers;
  NSHashTable *_fileReferencesForProblem8727051;
  DVTObservingToken *_finishedLoadingObservingToken;
  NSDictionary *_Problem9887530_preferredStructurePaths;
  id _openingPerformanceMetricIdentifier;
  DVTStackBacktrace *_finishedLoadingBacktrace;
  NSMutableOrderedSet *_initialOrderedReferencedBlueprintProviders;
  BOOL _hasPostedIndexingRegistrationBatchNotification;
  BOOL _didFinishLoadingFirstStage;
  BOOL _willInvalidate;
  NSMutableArray *_blocksToRunWhenFinishedLoading;
  BOOL _didProcessFileReferencesForProblem8727051;
  BOOL _indexingAndRefactoringRestartScheduled;
  BOOL _indexCreationInFlight;
  BOOL _didFinishBuildingInitialBlueprintProviderOrderedSet;
  NSMutableDictionary *_attachedObjects;
  NSMapTable *_pendingExecutionNotificationTokens;
  DVTObservingToken *_additionalRootGroupsObservingToken;
}

@property (readonly) NSObject<IDETestableDataSource_Index> *index;
@property (readonly) NSString *name;
@property (readonly, nonatomic) BOOL valid;
@property (readonly) DVTStackBacktrace *invalidationBacktrace;
@property (retain) DVTStackBacktrace *creationBacktrace;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain) NSArray *namedBatchFindScopes;
@property (readonly) BOOL finishedLoading;
@property (readonly) IDEWorkspaceNoticeSubsystem *noticeSubsystem;
@property (readonly) NSObject<IDEBlueprintProvider> *noticeWorkspaceWrappedContainer;
@property (readonly) NSObject<IDEBuildNoticeLogRecord> *latestBuildLogRecordForBuildNoticeProvider;
@property (readonly) IDELocalizationManager *localizationManager;
@property (nonatomic, readonly) NSArray *sortedWorkspaceContentProviders;
@property (retain, nonatomic) IDEWorkspaceArena *workspaceArena;
@property (retain) IDEDynamicContentRootGroup *dynamicContentRootGroup;
@property (retain) NSDictionary *workspaceContentProvidersByIdentifier;
@property (retain) NSArray *additionalRootGroups;
@property (retain) IDEDeviceInstallWorkspaceMonitor *deviceInstallWorkspaceMonitor;
@property (retain) IDEProvisioningWorkspaceMonitor *provisioningWorkspaceMonitor;
@property (retain) IDESourceControlWorkspaceMonitor *sourceControlWorkspaceMonitor;
@property (retain) IDELocalizationWorkspaceMonitor *localizationWorkspaceMonitor;
@property BOOL initialContainerScanComplete;
@property (nonatomic) BOOL pendingFileReferencesAndContainers;
@property (readonly) IDEConcreteClientTracker *clientTracker;
@property (retain) IDERunContextManager *runContextManager;
@property (retain) IDEExecutionEnvironment *executionEnvironment;
@property (retain) IDEBreakpointManager *breakpointManager;
@property (retain, nonatomic) IDEWorkspaceUserSettings *userSettings;
@property (retain, nonatomic) IDEWorkspaceSharedSettings *sharedSettings;
@property (retain) IDETestManager *testManager;
@property (retain, nonatomic) IDEProvisioningManager *provisioningManager;
@property (retain) DVTDocumentation_DVTDocumentationManager *documentationManager;
@property (retain) IDEWorkspaceUpgradeTasksController *deferredUpgradeTasksController;
@property BOOL hostsOnlyXcode3Project;
@property BOOL hostsOnlyPackages;
@property BOOL hostsOnlyPlaygroundProject;
@property BOOL hostsOnlyPlayground;
@property (readonly) BOOL shouldShowSwiftDeprecationWarning;
@property BOOL hostsOnlyWrappedContainer;
@property (nonatomic) BOOL isPotentiallyClosing;
@property (retain) NSObject<IDEWorkspaceDelegate> *workspaceDelegate;
@property (retain) NSObject<IDEActiveRunContextStoring> *activeRunContextStore;
@property (readonly, nonatomic) DVTFilePath *buildSystemDeveloperDirectory;
@property (retain, nonatomic) IDEActivityLogSection *issueLog;
@property (readonly) NSSet *referencedContainers;
@property (readonly) NSSet *referencedBlueprintProviders;
@property (readonly) NSSet *localizableReferencedBlueprintProviders;
@property (readonly) NSSet *referencedBlueprints;
@property (readonly) NSSet *localizableReferencedBlueprints;
@property (retain) NSDictionary *uniqueIdentifiersToReferencedBlueprints;
@property (readonly) NSSet *referencedSourcePackages;
@property (readonly) NSSet *referencedRemoteSourcePackages;
@property BOOL isWaitingForSourcePackages;
@property (copy, nonatomic) NSArray *sourcePackageLoadingErrors;
@property (copy) IDEActivityLogSection *sourcePackageResolutionIssueLog;
@property (readonly) NSSet *customDataStores;
@property (readonly) NSArray *notificationPayloadFileReferences;
@property (retain) NSObject<IDEPackageManagerWorkspace> *packageManager;
@property (readonly) IDELogManager *logManager;
@property (readonly) IDETextFragmentIndex *textFragmentIndex;
@property (readonly) IDERefactoring *refactoring;
@property (readonly) NSObject<IDEBuildSystemService> *buildSystemServiceProvider;
@property (readonly) NSObject<IDEBuildSystemService> *buildSystemService;
@property (nonatomic) BOOL wasLoadedForUIContext;
@property (retain, nonatomic) NSNumber *shouldUseLegacyBuildSystem;
@property (readonly) BOOL usesModernBuildSystem;
@property (readonly) BOOL wantsModernBuildSystem;
@property (readonly) BOOL supportsSourcePackages;
@property (readonly) NSSet *referencedRunnableBuildableProducts;
@property (nonatomic) BOOL finishedInitialPackageResolution;
@property (readonly, nonatomic) BOOL postLoadingPerformanceMetricsAllowed;
@property (readonly) DVTFilePath *wrappedContainerPath;
@property (readonly) BOOL simpleFilesFocused;
@property (readonly) NSString *representingTitle;
@property (readonly) DVTFilePath *representingFilePath;
@property (readonly) IDEContainer<IDECustomDataStoring> *representingCustomDataStore;
@property (readonly) IDEActivityLogMessage *swiftDeprecationLogMessage;
@property (readonly, nonatomic) BOOL hasLocalizations;
@property (readonly) DVTFilePath *containingDirectory;
@property (readonly) IDELaunchSessionLogReporter *launchLogReporter;
@property (readonly) IDEWorkspace *workspace;
@property (readonly, nonatomic) IDEResultBundleURLRedirector *resultBundleURLRedirector;
@property (readonly) BOOL isCancelling;
@property (readonly, nonatomic) NSSet *provisionables;
@property (readonly, nonatomic) NSSet *provisionableDestinations;
@property (readonly, nonatomic) IDEBuildParameters *activeBuildParameters;
@property (readonly) BOOL workspaceIntegrityProviderShouldNotProcessIssueLog;

/* class methods */
+ (id)injectTestableWorkspaceContentProviderClass:(Class)class;
+ (id)blueprintsByActivityLogSectionSignature:(id)signature;
+ (id)createGlobalScopeStore;
+ (id)globalScopeStore;
+ (void)initialize;
+ (unsigned long long)assertionBehaviorForKeyValueObservationsAtEndOfEvent;
+ (unsigned long long)assertionBehaviorAfterEndOfEventForSelector:(SEL)selector;
+ (BOOL)automaticallyNotifiesObserversOfFileRefsWithContainerLoadingIssues;
+ (id)rootElementName;
+ (id)xmlArchiveFileName;
+ (id)containerFileDataType;
+ (id)containerTypeDisplayName;
+ (id)_workspaceFileExtension;
+ (id)keyPathsForValuesAffectingContainsPackageReferences;
+ (id)keyPathsForValuesAffectingReferencedSourcePackages;
+ (id)keyPathsForValuesAffectingReferencedRemoteSourcePackages;
+ (id)keyPathsForValuesAffectingName;
+ (id)keyPathsForValuesAffectingRepresentingFilePath;
+ (id)keyPathsForValuesAffectingRepresentingTitle;
+ (id)keyPathsForValuesAffectingHostsOnlyXcode3Project;
+ (id)keyPathsForValuesAffectingHostsOnlyPlayground;
+ (id)keyPathsForValuesAffectingRepresentingCustomDataStore;
+ (BOOL)_shouldTrackReadOnlyStatus;
+ (id)keyPathsForValuesAffectingProvisionables;
+ (id)keyPathsForValuesAffectingProvisionableDevices;
+ (id)keyPathsForValuesAffectingProvisionableDestinations;
+ (id)keyPathsForValuesAffectingActiveBuildParameters;

/* instance methods */
- (void)issueLogDataSourceChangedIssueLog:(id)log oldIssueLog:(id)log;
- (void)issueLogDataSourceRequiresIntegrityAnalysis;
- (void)issueLogDataSourceRequiresIntegrityAnalysisForWorkspace:(id)workspace;
- (void)issueLogDataSourceRequiresIntegrityAnalysisForBlueprint:(id)blueprint;
- (void)issueLogDataSourceRequiresIntegrityAnalysisForBlueprintProvider:(id)provider;
- (void)issueLogDataSourceRequiresIntegrityAnalysisForUntypedDataSource:(id)source;
- (id)makeAdditionalRootGroups;
- (void)loadContentProvidersIntoWorkspace;
- (id)loadWorkspaceContentProvidersByIdentifier;
- (void)setUpBuildSystemDeveloperDirChangeProviderWith:(id /* block */)with;
- (void)_updateUniqueIdentifiersToReferencedBlueprints;
- (id)ideIndex_buildParametersForIndexingBlueprint:(id)blueprint synthesizedMacroOverrides:(id)overrides;
- (id)ideIndex_bestSchemeForBlueprint:(id)blueprint;
- (id)ideIndex_runDestinationForIndexingWithScheme:(id)scheme;
- (id)ideIndex_configurationNameForIndexingBlueprint:(id)blueprint scheme:(id)scheme;
- (id)ideModelObjectTypeIdentifier;
- (id)observeLatestBuildLogIdentityDidChange:(id /* block */)change;
- (id)activeNoticeDomains;
- (id)makeLogStoreForNoticeLogs;
- (id)observeActiveNoticeDomains:(id /* block */)domains;
- (id)observeActiveSchemeDidChange:(id /* block */)change;
- (id)observeBuildImplicitDependenciesDidChange:(id /* block */)change;
- (id)observeActiveRunDestinationDidChange:(id /* block */)change;
- (id)observeCurrentBuildOperationDidChange:(id /* block */)change;
- (id)localScopeStore;
- (id)collectLinkedTargetIndexableIdsForIndexableIds:(id)ids;
- (id)testableDataSourceForTestingSystemWithIdentifier:(id)identifier;
- (id)newScriptingObjectOfClass:(Class)class forValueForKey:(id)key withContentsValue:(id)value properties:(id)properties;
- (id)sdefSupport_schemesForDocument:(id)document;
- (id)sdefSupport_activeSchemeForDocument:(id)document;
- (void)setSdefSupport_activeScheme:(id)scheme;
- (id)_disambiguatedRunDestinations;
- (id)sdefSupport_runDestinationsForDocument:(id)document;
- (id)sdefSupport_activeRunDestinationForDocument:(id)document;
- (void)setSdefSupport_activeRunDestination:(id)destination;
- (void)dvt_encodeAttributesWithXMLArchiver:(id)xmlarchiver version:(id)version;
- (void)dvt_encodeRelationshipsWithXMLArchiver:(id)xmlarchiver version:(id)version;
- (id)_openingPerformanceMetricIdentifier;
- (void)_addPendingReferencedFileReference:(id)reference;
- (void)_removePendingReferencedFileReference:(id)reference;
- (void)_addPendingReferencedContainerPath:(id)path;
- (void)_removePendingReferencedContainerPath:(id)path;
- (void)_clearPendingFileReferencesAndContainerLoadingTokens;
- (void)_handleContainerResolutionFailureForFileReference:(id)reference;
- (void)_setFileRefsWithContainerLoadingIssues:(id)issues;
- (void)analyzeModelForIssues;
- (BOOL)_shouldLoadUISubsystems;
- (void)_setupWorkspaceArenaIfNeeded;
- (void)_finishLoadingAsynchronously:(BOOL)asynchronously shouldUpgradeFromSimpleFilesFocused:(BOOL)focused;
- (void)_checkIfHasFinishedLoading;
- (void)_containerDidLoad;
- (void)_buildProductsLocationDidChange;
- (id)initWithFilePath:(id)path extension:(id)extension workspace:(id)workspace options:(id)options error:(id *)error;
- (void)_setWrappedContainerPath:(id)path;
- (id)_wrappedContainer;
- (id)_wrappedPlaygroundContainer;
- (id)_wrappingContainerPath;
- (BOOL)_configureWrappedWorkspaceWithError:(id *)error;
- (void)_changeContainerFilePath:(id)path inContext:(id)context;
- (void)_changeContainerFilePath:(id)path inContext:(id)context upgradeToWorkspace:(BOOL)workspace;
- (BOOL)_setContainerFilePath:(id)path upgradeToWorkspace:(BOOL)workspace error:(id *)error;
- (BOOL)setContainerFilePath:(id)path error:(id *)error;
- (BOOL)saveRecursivelyWithError:(id *)error;
- (void)_setupBuildCompletedNotificationForExecutionEnvironment:(id)environment completionBlock:(id /* block */)block;
- (BOOL)_cancelOngoingBuildWithCompletionBlockIfNeeded:(id /* block */)needed;
- (id)registerClientWithName:(id)name promptForCancellation:(BOOL)cancellation terminationSignpost:(id /* block */)signpost cancellationBlock:(id /* block */)block;
- (id)registerUncancellableClientWithName:(id)name terminationSignpost:(id /* block */)signpost;
- (id)clientsRequiringCancellationPrompt;
- (id)clientsNotSupportingCancellation;
- (void)cancelTrackedClients;
- (void)_setFileRefsForProblem8727051:(id)problem8727051;
- (void)_processFileReferencesForProblem8727051;
- (id)_Problem9887530_wrappedContainerFileReferences:(id)references forPath:(id)path;
- (id)_Problem9887530_preferredStructurePathsForContainerToContainerFileReferences:(id)references;
- (id)_Problem9887530_preferredStructurePaths;
- (id)_Problem9887530_preferredStructurePathForContainerAtPath:(id)path;
- (void)_addBlueprintProviderToOrderedSet:(id)set;
- (void)_setupContainerQueries;
- (void)_setupHeaderMapPath;
- (id)buildableProductsForProductName:(id)name;
- (id)buildableProductsForProductWithModuleName:(id)name;
- (void)_referencedBlueprintsDidUpdate;
- (void)_referencedBlueprintProvidersDidEdit;
- (void)invokeChangingValueForKey:(id)key fromSet:(id)set toSet:(id)set block:(id /* block */)block;
- (void)_referencedContainersDidUpdate;
- (id)containerGraphOrderForAllReferencedBlueprintProviders;
- (id)containerGraphOrderForBlueprintProviders:(id)providers;
- (BOOL)containsSwiftPackages;
- (BOOL)fileIsMemberOfRemoteSourcePackage:(id)package;
- (id)referencedSourcePackageForURL:(id)url;
- (id)referencedSourcePackageForPackageIdentity:(id)identity;
- (id)likelyAttachToTargetRunnableBuildableNames;
- (id)blueprintsContainingFilePaths:(id)paths;
- (void)_setupLogManagerIfNeeded;
- (void)_setupIssueManagerIfNeeded;
- (void)_invalidateBuildSystemService;
- (id)allLocalizations;
- (id)displayName;
- (float)archiveVersion;
- (float)maxSupportedArchiveVersion;
- (id)_subitemsForUnarchivedSubitems:(id)subitems;
- (void)_setupExecutionEnvironment;
- (void)_setHostsOnlyPlayground:(BOOL)playground;
- (void)_primitiveSetSimpleFilesFocused:(BOOL)focused;
- (void)_setSimpleFilesFocused:(BOOL)focused;
- (BOOL)isSimpleFilesFocused;
- (void)runBlockWhenFinishedLoading:(id /* block */)loading;
- (void)_setWrappedContainer:(id)container;
- (void)_updateWrappedContainer;
- (id)attachedObjectForIdentifier:(id)identifier;
- (void)setAttachedObject:(id)object forIdentifier:(id)identifier;
- (id)attachedObjectForIdentifier:(id)identifier creatingIfNecessaryUsingBlock:(id /* block */)block;
- (void)_invalidateAndClearWorkspaceAttachedObjects;
- (void)primitiveInvalidate;
- (void)_handleIndexableSourcesChange:(id)change;
- (void)_scheduleIndexingAndRefactoringRestart;
- (void)_restartIndexingAndRefactoring;
- (void)tearDownIndexAndRefactoring;
- (void)_setupDeviceInstallWorkspaceMonitor;
- (void)_setupProvisioningWorkspaceMonitor;
- (void)_setupLocalizationWorkspaceMonitor;
- (void)_initializeSourceControlWorkspaceMonitor;
- (void)_setupSourceControlWorkspaceMonitorIfNeeded;
- (void)_setupWorkspaceUpgradeTasksController;
- (void)_setupLaunchLogWorkspaceReporter;
- (void)_scheduleWorkspaceUpgradeTasksController:(id)controller;
- (void)initializeIndexAndRefactoring;
- (void)didCreateIndex:(id)index;
- (void)_enqueueRegistrationFromPendingIndexables;
- (void)_handleIndexablesChange:(id)change;
- (id)buildableProductsForBaseName:(id)name;
- (void)notifyBuildSystemServiceThatBlueprintProviderDidChange:(id)change;
@end

#endif /* IDEWorkspace_h */
