//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22526.0.0.0.0
//
#ifndef PBXBuildPhase_h
#define PBXBuildPhase_h
#import <Foundation/Foundation.h>

#include "PBXProjectItem.h"
#include "PBXTarget.h"
#include "XCCompatibilityChecking-Protocol.h"

@class NSArray, NSMutableArray, NSString, PBXTarget;

@interface PBXBuildPhase : PBXProjectItem<XCCompatibilityChecking> {
  /* instance variables */
  NSString *_name;
  PBXTarget *_target;
  NSMutableArray *_customBuildRules;
  unsigned long long _buildActionMask;
  BOOL _runOnlyForDeploymentPostprocessing;
}

@property (readonly) NSArray *buildFiles;

/* class methods */
+ (id)identifier;
+ (id)defaultName;
+ (id)buildPhase;
+ (id)buildPhaseFromTemplateDictionary:(id)dictionary;
+ (id)allowedFileTypes;
+ (id)archivableAttributes;
+ (id)archivableRelationships;
+ (id)archiveNameForKey:(id)key;

/* instance methods */
- (void)appendUserSettingsDictionariesTo:(id)to defaultSettingsDictionariesTo:(id)to forBuildConfigurationNamed:(id)named;
- (void)appendUserSettingsDictionariesTo:(id)to defaultSettingsDictionariesTo:(id)to;
- (id)stringByExpandingString:(id)string forBuildConfigurationNamed:(id)named;
- (id)stringByExpandingString:(id)string;
- (id)stringByMakingExpandedPathAbsolute:(id)absolute;
- (id)initFromTemplateDictionary:(id)dictionary;
- (id)initWithName:(id)name;
- (id)init;
- (void)dealloc;
- (id)name;
- (void)setName:(id)name;
- (BOOL)canRename;
- (id)target;
- (void)_setTarget:(id)target;
- (id)container;
- (void)setContainer:(id)container;
- (void)_setBuildActionMask:(unsigned long long)mask;
- (BOOL)runOnlyForDeploymentPostprocessing;
- (void)setRunOnlyForDeploymentPostprocessing:(BOOL)postprocessing;
- (id)customBuildRules;
- (void)setCustomBuildRules:(id)rules;
- (void)insertObject:(id)object inCustomBuildRulesAtIndex:(unsigned long long)index;
- (void)removeObjectFromCustomBuildRulesAtIndex:(unsigned long long)index;
- (void)replaceObjectInCustomBuildRulesAtIndex:(unsigned long long)index withObject:(id)object;
- (BOOL)insertBuildFiles:(id)files atIndex:(unsigned long long)index;
- (BOOL)insertBuildFile:(id)file atIndex:(unsigned long long)index;
- (BOOL)addBuildFile:(id)file;
- (void)_removeBuildFileFromChildrenOnly:(id)only;
- (void)removeBuildFile:(id)file;
- (BOOL)addReference:(id)reference;
- (BOOL)removeReference:(id)reference;
- (id)buildFileForReference:(id)reference;
- (id)buildFileForReferenceIdenticalTo:(id)to;
- (id)buildFileForResolvedAbsolutePath:(id)path;
- (id)buildFileForAbsolutePath:(id)path;
- (BOOL)containsFileReferenceIdenticalTo:(id)to;
- (id)buildFileForProductReference:(id)reference;
- (void)_setBuildFiles:(id)files;
- (BOOL)acceptsVariantGroups;
- (BOOL)_isReferenceReallyInProject:(id)project;
- (BOOL)acceptsReference:(id)reference checkFileType:(BOOL)type;
- (BOOL)acceptsReference:(id)reference;
- (BOOL)isDeletable;
- (void)setDefaultAttributesForNewBuildFile:(id)file;
- (unsigned long long)countBuildFilesWithExtensionInSet:(id)set;
- (id)inputFileNames;
- (id)outputFileNames;
- (id)allowedFileTypes;
- (BOOL)allowsFileType:(id)type;
- (id)gidCommentForArchive;
- (void)findFeaturesInUseAndAddToSet:(id)set usingPathPrefix:(id)prefix;
- (void)willChange;
- (void)referenceWillChange:(id)change;
- (void)referenceWillBeRemoved:(id)removed;
- (void)buildFileWasAdded:(id)added;
- (void)buildFileWillBeRemoved:(id)removed;
- (void)buildFileDidReorder:(id)reorder oldIndex:(long long)index newIndex:(long long)index;
- (id)primaryAttributeForBuildFile:(id)file;
- (id)linkedJavaClassArchivePathsUsingFrameworkJavaSubpaths:(id)subpaths;
- (BOOL)phaseContainsJavaFiles;
- (BOOL)phaseContainsNonJavaFiles;
- (void)_upgradeAfterAwakingFromUnarchiver:(id)unarchiver;
- (void)enumerateBuildRulesWithMacroExpansionScope:(id)scope usingBlock:(id /* block */)block;
- (void)addRelevantBuildPropertySpecificationsForFileTypes:(id)types withMacroExpansionScope:(id)scope toOrderedSet:(id)set;
- (Class)dependencyGraphSnapshotClass;
- (id)createDependencyGraphSnapshotForTargetSnapshot:(id)snapshot withResolver:(id)resolver;
- (id)createDependencyGraphSnapshotsForTargetSnapshot:(id)snapshot withResolver:(id)resolver;
@end

#endif /* PBXBuildPhase_h */
