//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22028.0.0.0.0
//
#ifndef SKIndexableDelegate_Protocol_h
#define SKIndexableDelegate_Protocol_h
#import <Foundation/Foundation.h>

@protocol SKIndexableDelegate <NSObject>
@optional
/* instance methods */
- (void)buildSettings:(id)settings forIndexable:(id)indexable;
- (void)indexableFileAdded:(id)added forIndexable:(id)indexable;
- (void)indexableFileRemoved:(id)removed forIndexable:(id)indexable;
- (void)indexableFileRenamedFrom:(id)from to:(id)to forIndexable:(id)indexable;
- (void)linkedIndexablesChanged:(id)changed forIndexable:(id)indexable;
@end

#endif /* SKIndexableDelegate_Protocol_h */
