//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22028.0.0.0.0
//
#ifndef SKIndexedUnitTestsRepo_h
#define SKIndexedUnitTestsRepo_h
#import <Foundation/Foundation.h>

#include "IDECoalescingInvocation.h"
#include "IDEIndex.h"
#include "SKIndexableDelegate-Protocol.h"
#include "SKIndexedUnitTestsDelegate-Protocol.h"

@class DVTNotificationToken, NSMutableDictionary, NSMutableOrderedSet, NSMutableSet, NSString;

@interface SKIndexedUnitTestsRepo : NSObject<SKIndexableDelegate> {
  /* instance variables */
  IDEIndex *_index;
  void * _stateMtx;
  NSMutableDictionary *_testDataByTestable;
  NSObject<OS_dispatch_queue> *_indexQueryQueue;
  NSMutableSet *_monitoredIndexables;
  NSMutableOrderedSet *_indexablesForSettingsResolving;
  NSMutableDictionary *_pendingFutureByIndexable;
  NSObject<OS_dispatch_queue> *_indexableSettingsQueryQueue;
  DVTNotificationToken *_prebuildNotificationToken;
  IDECoalescingInvocation *_delayedResolvedSettingsInvocation;
  void * _pendingStoreProcessedUnits;
  void * _outputPathsWithTestSymbols;
  void * _indexableByOutputPath;
  NSMutableDictionary *_infoByIndexable;
}

@property BOOL shouldWaitForPrebuild;
@property (weak) NSObject<SKIndexedUnitTestsDelegate> *delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithIndex:(id)index;
- (void)registerIndexable:(id)indexable;
- (void)unregisterIndexable:(id)indexable;
- (void)_stopMonitoringIndexable:(id)indexable;
- (void)_queryIndexBuildSettingsForPendingIndexables;
- (void)_queryIndexBuildSettingsForIndexable:(id)indexable;
- (void)_enqueueSettingsQueryForIndexable:(id)indexable;
- (void)_resolveSettingsForQueuedTestables;
- (void)buildSettings:(id)settings forIndexable:(id)indexable;
- (void)_handleOutputPaths:(id)paths forIndexable:(id)indexable;
- (void)linkedIndexablesChanged:(id)changed forIndexable:(id)indexable;
- (void)indexableFileAdded:(id)added forIndexable:(id)indexable;
- (void)indexableFileRemoved:(id)removed forIndexable:(id)indexable;
- (void)indexableFileRenamedFrom:(id)from to:(id)to forIndexable:(id)indexable;
- (BOOL)removeIndexableFile:(id)file indexable:(id)indexable;
- (BOOL)renameIndexableFile:(id)file newFile:(id)file indexable:(id)indexable;
- (BOOL)removeTestableFile:(id)file testable:(id)testable;
- (BOOL)renameTestableFile:(id)file newFile:(id)file testable:(id)testable;
- (void)_handleProcessedUnits:(void *)units;
- (void)_lookupIndexedUnitTestsForTestableAsync:(id)async;
- (void)_lookupIndexedUnitTestsForTestable:(id)testable;
- (void)storeProcessedUnitOutputPath:(id)path hasTestSymbols:(BOOL)symbols;
- (void)storeCompletedProcessingUnits;
- (void)indexPausedStateChangedTo:(BOOL)to;
- (id)_allTestables;
- (BOOL)_isUnitTestOrLinkedFromUnitTest:(id)test;
- (id)_testablesForIndexable:(id)indexable;
- (id)unitTestsForTestable:(id)testable;
- (void)invalidate;
@end

#endif /* SKIndexedUnitTestsRepo_h */
