//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22028.0.0.0.0
//
#ifndef SKScannedUnitTestsRepo_h
#define SKScannedUnitTestsRepo_h
#import <Foundation/Foundation.h>

#include "IDEIndex.h"
#include "SKIndexableDelegate-Protocol.h"
#include "SKScanIndex.h"
#include "SKScannedFilesDelegate-Protocol.h"
#include "SKScannedUnitTestsDelegate-Protocol.h"

@class NSMutableDictionary, NSMutableSet, NSString;

@interface SKScannedUnitTestsRepo : NSObject<SKScannedFilesDelegate, SKIndexableDelegate> {
  /* instance variables */
  IDEIndex *_index;
  SKScanIndex *_scanIndex;
  void * _stateMtx;
  NSMutableDictionary *_targetsByFilePath;
  NSMutableDictionary *_unitTestScanDataByFilePath;
  NSMutableSet *_monitoredIndexables;
}

@property (weak) NSObject<SKScannedUnitTestsDelegate> *delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithIndex:(id)index toolchainResolver:(id)resolver;
- (void)setScanIndexDelegate:(id)delegate;
- (void)registerIndexable:(id)indexable;
- (void)unregisterIndexable:(id)indexable;
- (void)indexableFileAdded:(id)added forIndexable:(id)indexable;
- (void)indexableFileRemoved:(id)removed forIndexable:(id)indexable;
- (void)indexableFileRenamedFrom:(id)from to:(id)to forIndexable:(id)indexable;
- (void)linkedIndexablesChanged:(id)changed forIndexable:(id)indexable;
- (BOOL)addNewTestableFiles:(id)files testable:(id)testable;
- (BOOL)removeTestableFiles:(id)files testable:(id)testable;
- (BOOL)renameTestableFile:(id)file newFile:(id)file testable:(id)testable;
- (id)unitTestsForTestable:(id)testable;
- (void)scannedSymbols:(id)symbols scanIndex:(id)index;
- (void)_onSymbolsChangedInIndexables:(id)indexables;
- (id)indexablesForFile:(id)file;
- (id)_allTestables;
- (BOOL)_isUnitTestOrLinkedFromUnitTest:(id)test;
- (id)_testablesForIndexable:(id)indexable;
- (void)invalidate;
@end

#endif /* SKScannedUnitTestsRepo_h */
