//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22526.0.0.0.0
//
#ifndef XCBuildFileRefDGSnapshot_h
#define XCBuildFileRefDGSnapshot_h
#import <Foundation/Foundation.h>

#include "PBXFileType.h"
#include "PBXObjectID.h"
#include "XCBuildInfo.h"

@class NSDictionary, NSSet, NSString;
@protocol DVTMacroExpansion;

@interface XCBuildFileRefDGSnapshot : NSObject {
  /* instance variables */
  PBXObjectID *_referenceGlobalID;
  PBXObjectID *_groupGlobalID;
  NSString *_path;
  PBXFileType *_fileType;
  NSDictionary *_fileProperties;
  XCBuildInfo *_buildInfo;
  NSString *_buildFilePrimaryAttrString;
  NSArray<DVTMacroExpansion> *_addlCompilerArgs;
  BOOL _isInVariantGroup;
  BOOL _linkUsingSearchPath;
  NSString *_regionVariantName;
  NSSet *_attributes;
  NSSet *_assetTags;
  NSSet *_internalAssetTagSets;
  NSSet *_platformFilters;
}

@property (readonly) NSString *fileTextEncodingName;

/* instance methods */
- (void)enumerateUsingBlock:(id /* block */)block macroExpansionScope:(id)scope;
- (id)initWithInformationFromBuildFile:(id)file fileReference:(id)reference groupReference:(id)reference forTargetSnapshot:(id)snapshot withResolver:(id)resolver;
- (id)initWithDependencyNode:(id)node fileType:(id)type buildSettings:(id)settings;
- (id)initWithPath:(id)path fileType:(id)type regionVariantName:(id)name;
- (id)init;
- (void)printForDebugging;
- (id)buildInfo;
- (id)stringValueForPrimaryAttribute;
- (id)referenceGlobalID;
- (id)groupGlobalID;
- (id)path;
- (id)fileType;
- (id)fileProperties;
- (BOOL)isInVariantGroup;
- (BOOL)isLocalizable;
- (id)regionVariantName;
- (id)subpathForWrapperPart:(long long)part;
- (id)pathForWrapperPart:(long long)part;
- (BOOL)boolValueOfAttributeNamed:(id)named;
- (id)attributes;
- (BOOL)hasAssetTags;
- (id)assetTags;
- (id)internalAssetTagSets;
- (id)additionalCompilerArguments;
- (BOOL)linkUsingSearchPath;
- (id)description;
- (id)platformFilters;
@end

#endif /* XCBuildFileRefDGSnapshot_h */
