//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22526.0.0.0.0
//
#ifndef XCBuildPhaseDGSnapshot_h
#define XCBuildPhaseDGSnapshot_h
#import <Foundation/Foundation.h>

#include "XCBuildPhaseSpecification.h"

@class DVTMacroDefinitionTable, DVTRegularExpression, NSArray, NSMutableArray, NSMutableDictionary, NSSet, NSString;

@interface XCBuildPhaseDGSnapshot : NSObject {
  /* instance variables */
  XCBuildPhaseSpecification *_type;
  NSString *_name;
  DVTMacroDefinitionTable *_buildSettings;
  NSArray *_allBuildRules;
  NSArray *_buildFileRefs;
  NSMutableArray *_effectiveBuildFileRefs;
  NSMutableDictionary *_inputFileBucketsByName;
  DVTRegularExpression *_hiDpiRegex;
  NSSet *_hiDpiImageLowercaseSuffixes;
  BOOL _runOnlyForDeploymentPostprocessing;
}

/* class methods */
+ (id)defaultName;

/* instance methods */
- (id)buildRuleForDependencyNode:(id)node ofType:(id)type architecture:(id)architecture withMacroExpansionScope:(id)scope;
- (id)buildRuleForReference:(id)reference architecture:(id)architecture withMacroExpansionScope:(id)scope;
- (BOOL)shouldResolveBuildRulesForFileReferences;
- (id)filteredBuildFileReferencesWithMacroExpansionScope:(id)scope;
- (id)groupDependencyNode:(id)node ifNecessaryForLaterProcessingWithMacroExpansionScope:(id)scope;
- (void)computeDependenciesForBuildFileReference:(id)reference withMacroExpansionScope:(id)scope;
- (void)computeDependenciesForAllBuildFileReferencesWithMacroExpansionScope:(id)scope;
- (void)computeDependenciesWithMacroExpansionScope:(id)scope;
- (id)initWithInformationFromBuildPhase:(id)phase forTargetSnapshot:(id)snapshot withResolver:(id)resolver;
- (id)initWithTargetSnapshot:(id)snapshot;
- (id)init;
- (void)printForDebugging;
- (id)type;
- (id)name;
- (id)buildSettings;
- (id)customBuildRules;
- (id)buildFileRefs;
- (id)allBuildRules;
- (BOOL)runOnlyForDeploymentPostprocessing;
- (id)buildFilesToCountBaseNames;
@end

#endif /* XCBuildPhaseDGSnapshot_h */
