//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22526.0.0.0.0
//
#ifndef XCDependencyNode_h
#define XCDependencyNode_h
#import <Foundation/Foundation.h>

#include "DVTFileSystemRepresentationProviding-Protocol.h"
#include "DVTMacroExpansion-Protocol.h"
#include "XCBuildInfo.h"
#include "XCDepGraphNodeState.h"
#include "XCDependencyGraph.h"
#include "XCDependencyNode.h"

@class NSMutableArray, NSMutableSet, NSString;

@interface XCDependencyNode : NSObject<DVTMacroExpansion, DVTFileSystemRepresentationProviding> {
  /* instance variables */
  NSString *_name;
  NSString *_path;
  NSMutableArray *_producerCommands;
  NSMutableArray *_includedNodes;
  NSMutableSet *_consumerCommands;
  NSMutableArray *_includingNodes;
  XCBuildInfo *_buildInfo;
  XCDependencyGraph *_depGraph;
  XCDependencyNode *_supernode;
  NSMutableArray *_subnodes;
  XCDepGraphNodeState *_currentState;
  void * _subnodeLock;
  unsigned int _nodeNumber;
  unsigned int _alwaysOutOfDate :1 ;
  unsigned int _dontCareIfExists :1 ;
  unsigned int _anyDescendantHasProducerCommands :1 ;
  unsigned int _isVirtual :1 ;
  unsigned char _suffixLen;
  unsigned short _pathLen;
  unsigned short _nameLen;
  char _nameCStr[0];
}

@property BOOL shouldBeProcessed;
@property BOOL performDeepScanForModificationTimes;
@property (nonatomic) BOOL isAuxiliaryOutput;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)newNodeWithNumber:(unsigned int)number nameCStr:(const char *)cstr length:(unsigned long long)length supernode:(id)supernode isVirtual:(BOOL)virtual inDependencyGraph:(id)graph;

/* instance methods */
- (id)initWithNumber:(unsigned int)number nameCStr:(const char *)cstr length:(unsigned long long)length supernode:(id)supernode isVirtual:(BOOL)virtual inDependencyGraph:(id)graph;
- (id)init;
- (id)supernode;
- (BOOL)isVirtual;
- (id)subnodes;
- (void)_enumerateNodeTreeRecursivelyWithStop:(BOOL *)stop usingBlock:(id /* block */)block;
- (void)enumerateNodeTreeRecursivelyUsingBlock:(id /* block */)block;
- (unsigned long long)pathLength;
- (long long)getPathCStr:(char *)cstr bufferSize:(unsigned long long)size fromAncestorNode:(id)node;
- (long long)getPathCStr:(char *)cstr bufferSize:(unsigned long long)size;
- (id)subnodeWithSubpathCStr:(const char *)cstr createIfNeeded:(BOOL)needed;
- (id)subnodeWithSubpath:(id)subpath createIfNeeded:(BOOL)needed;
- (id)subnodeWithSubpath:(id)subpath;
- (id)objectForKeyedSubscript:(id)subscript;
- (BOOL)isDescendantOfNode:(id)node;
- (id)ancestorSharedWithNode:(id)node;
- (id)subpathFromAncestorNode:(id)node;
- (id)subpathFromNode:(id)node;
- (unsigned long long)nameLength;
- (const char *)nameCStr;
- (unsigned long long)suffixLength;
- (const char *)suffixCStr;
- (id)buildContext;
- (id)currentNodeStateWithOptions:(unsigned long long)options ignoringCache:(BOOL)cache withPreviousNodeState:(id)state;
- (id)currentNodeStateWithOptions:(unsigned long long)options ignoringCache:(BOOL)cache;
- (id)currentNodeState;
- (void)discardCurrentNodeState;
- (unsigned int)nodeNumber;
- (id)identifier;
- (id)path;
- (id)displayName;
- (id)displayPath;
- (id)producerCommands;
- (id)includedNodes;
- (id)consumerCommands;
- (id)includingNodes;
- (id)producerCommand;
- (id)buildInfo;
- (void)setBuildInfo:(id)info;
- (void)visitUpstreamCommandsUsingPreorderBlock:(id /* block */)block postorderBlock:(id /* block */)block;
- (void)visitDownstreamCommandsUsingPreorderBlock:(id /* block */)block postorderBlock:(id /* block */)block;
- (void)_addProducerCommand:(id)command;
- (void)_addConsumerCommand:(id)command;
- (BOOL)isAlwaysOutOfDate;
- (void)setAlwaysOutOfDate:(BOOL)date;
- (BOOL)dontCareIfExists;
- (void)setDontCareIfExists:(BOOL)exists;
- (BOOL)hasProducerCommandsConsideringDescendants:(BOOL)descendants;
- (void)prepareForUpdatingDependencyGraph;
- (id)shortNameForDebugging;
- (id)copyWithZone:(struct _NSZone *)zone;
- (BOOL)dvt_isLiteral;
- (id)dvt_stringForm;
- (id)dvt_evaluateAsStringInScope:(id)scope withState:(const struct DVTNestedMacroExpansionState *)state;
- (id)dvt_evaluateAsStringListInScope:(id)scope withState:(const struct DVTNestedMacroExpansionState *)state;
- (void)dvt_assertInternalConsistency;
- (id)dvt_debugDescription;
- (id)dependencyGraph;
- (void)invalidate;
- (BOOL)isValid;
- (BOOL)createDirectoryRecursively;
- (BOOL)removeRecursively;
- (void)dvt_provideFileSystemRepresentationToBlock:(id /* block */)block;
@end

#endif /* XCDependencyNode_h */
