//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22526.0.0.0.0
//
#ifndef XCMacroExpansionScope_h
#define XCMacroExpansionScope_h
#import <Foundation/Foundation.h>

#include "DVTMacroExpansionScope.h"
#include "PBXTargetBuildContext.h"
#include "XCDependencyGraphCreationContext.h"
#include "XCSDKPackage.h"

@interface XCMacroExpansionScope : DVTMacroExpansionScope {
  /* instance variables */
  XCSDKPackage *_cachedSdk;
}

@property (readonly) XCDependencyGraphCreationContext *dependencyGraphCreationContext;
@property (readonly, weak) PBXTargetBuildContext *buildContext;
@property (readonly) XCSDKPackage *sdk;

/* class methods */
+ (long long)numberOfDefinitionLevels;
+ (BOOL)isUserDefinedDefinitionLevel:(unsigned long long)level;
+ (id)stringForDefinitionLevel:(long long)level;
+ (id)newWithParentScope:(id)scope macroDefinitionTable:(id)table definitionLevel:(unsigned long long)level definitionLevelsToClear:(id)clear conditionParameterValues:(id)values conditionParameterFallbackValues:(id)values expansionOptions:(unsigned long long)options;
+ (id)newWithParentScope:(id)scope macroDefinitionTable:(id)table definitionLevel:(unsigned long long)level;

/* instance methods */
- (id)initWithParentScope:(id)scope macroDefinitionTable:(id)table definitionLevel:(unsigned long long)level dataSource:(id)source definitionLevelsToClear:(id)clear conditionParameterValues:(id)values conditionParameterFallbackValues:(id)values expansionOptions:(unsigned long long)options;
- (id)initWithParentScope:(id)scope dependencyGraphCreationContext:(id)context;
- (id)initWithDataSource:(id)source dependencyGraphCreationContext:(id)context;
- (void)appendAdditionalContentToStringBuilder:(void *)builder indent:(unsigned long long)indent;
@end

#endif /* XCMacroExpansionScope_h */
