//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22526.0.0.0.0
//
#ifndef Xcode3TargetConsolidatedCapabilitiesContextSource_h
#define Xcode3TargetConsolidatedCapabilitiesContextSource_h
#import <Foundation/Foundation.h>

#include "IDEConsolidatedCapabilitiesContextSource-Protocol.h"
#include "Xcode3Target.h"

@class DVTNotificationToken, DVTStackBacktrace, NSDictionary, NSMutableDictionary, NSString;
@protocol IDEConsolidatedCapabilitiesContextSourceDelegate;

@interface Xcode3TargetConsolidatedCapabilitiesContextSource : NSObject<IDEConsolidatedCapabilitiesContextSource>

@property (retain, nonatomic) Xcode3Target *target;
@property (retain, nonatomic) DVTNotificationToken *configurationNamesNotificationObservation;
@property (retain, nonatomic) NSMutableDictionary *mutableConfigurationToContextDidChangeSubscription;
@property (retain, nonatomic) NSMutableDictionary *mutableConfigurationToContext;
@property (weak, nonatomic) NSObject<IDEConsolidatedCapabilitiesContextSourceDelegate> *delegate;
@property (readonly, nonatomic) NSDictionary *configurationToContext;
@property (readonly, nonatomic) BOOL valid;
@property (readonly) DVTStackBacktrace *invalidationBacktrace;
@property (retain) DVTStackBacktrace *creationBacktrace;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)initialize;

/* instance methods */
- (id)initWithTarget:(id)target;
- (void)setUpObservations;
- (void)updateConfigurationToContextNotifyingDelegate:(BOOL)delegate;
- (void)primitiveInvalidate;
@end

#endif /* Xcode3TargetConsolidatedCapabilitiesContextSource_h */
