//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22526.0.0.0.0
//
#ifndef Xcode3Project_h
#define Xcode3Project_h
#import <Foundation/Foundation.h>

#include "IDEContainer.h"
#include "DVTInvalidation-Protocol.h"
#include "IDEAvailableSwiftVersionsProvider-Protocol.h"
#include "IDEBlueprintProvider-Protocol.h"
#include "IDEBuildSettingConfigurable-Protocol.h"
#include "IDECustomDataStoring-Protocol.h"
#include "IDEIndexableProvider-Protocol.h"
#include "IDEIssueLogDataSource-Protocol.h"
#include "IDELocalizedContainer-Protocol.h"
#include "IDETestStateChangeEmitter-Protocol.h"
#include "IDETestableProvider-Protocol.h"
#include "IDEWorkspaceWrappingContainer-Protocol.h"
#include "PBXProject.h"
#include "PBXReference.h"
#include "Xcode3ProjectVersion.h"
#include "Xcode3SourceListItemEditing-Protocol.h"

@class DVTFilePath, DVTLocale, DVTModelObjectGraph, DVTObservingToken, DVTStackBacktrace, IDEActivityLogSection, IDEDirectoryBasedCustomDataStore, IDETestStateChangeRegistry, IDEWorkspace, NSArray, NSMapTable, NSMutableArray, NSMutableDictionary, NSSet, NSString;

@interface Xcode3Project : IDEContainer<IDEAvailableSwiftVersionsProvider, IDEBlueprintProvider, IDEIndexableProvider, IDETestableProvider, Xcode3SourceListItemEditing, IDECustomDataStoring, IDEWorkspaceWrappingContainer, IDELocalizedContainer, IDEIssueLogDataSource, IDEBuildSettingConfigurable, IDETestStateChangeEmitter> {
  /* instance variables */
  NSArray *_customUpgradeTasks;
  NSMutableDictionary *_deferredCustomUpgradeRegistrations;
  id _activeSchemeObservation;
  NSObject<DVTInvalidation> *_projectSettingsDidChangeBroadcastToken;
  IDETestStateChangeRegistry *_stateChangeRegistry;
  PBXProject *_project;
  PBXReference *_projectReference;
  long long _saveErrorCode;
  NSArray *_targets;
  NSMapTable *_pbxTargetsToXc3Targets;
  NSMapTable *_xc3TargetsToTestables;
  BOOL _isBaseLocalized;
  BOOL _integrityCheckingBlockQueued;
  DVTObservingToken *_projectObservation_targets;
  DVTObservingToken *_needsArchiveObservingToken;
  NSArray *_sortedLocalizationsIncludingBase;
  NSArray *_sortedLocalizationsWithoutBase;
}

@property (retain) IDEDirectoryBasedCustomDataStore *customDataStore;
@property (nonatomic) BOOL pbxProjectEdited;
@property (readonly) BOOL shouldLogUpgradeCheck;
@property BOOL hasRunUpgradeCheck;
@property (readonly) NSString *cachedLastUpgradeVersion;
@property (retain) PBXProject *pbxProject;
@property (readonly, copy) NSString *name;
@property (retain, nonatomic) Xcode3ProjectVersion *preferredProjectVersion;
@property (readonly, copy, nonatomic) NSArray *availableProjectVersions;
@property (readonly) NSArray *targetProxies;
@property (readonly) NSArray *configurationNames;
@property (readonly) NSString *defaultConfigurationName;
@property (readonly, copy) NSArray *localizations;
@property (readonly) BOOL baseLocalized;
@property (readonly, copy) NSSet *variantGroups;
@property (copy) DVTLocale *developmentRegion;
@property (copy) NSString *organizationName;
@property (copy) NSString *classPrefix;
@property (readonly) NSString *lastUpgradeVersion;
@property (readonly, copy) NSArray *blueprints;
@property (readonly) NSObject<IDETestableProvider> *testableProvider;
@property (readonly) DVTFilePath *filePath;
@property (readonly) IDEWorkspace *workspace;
@property (readonly) NSString *uniqueIdentifier;
@property int buildSystemType;
@property (readonly) NSArray *sourcePackageReferences;
@property (readonly) BOOL supportsSourceFolders;
@property (readonly, nonatomic) BOOL valid;
@property (readonly) DVTStackBacktrace *invalidationBacktrace;
@property (retain) DVTStackBacktrace *creationBacktrace;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) IDEActivityLogSection *issueLog;
@property (readonly) BOOL workspaceIntegrityProviderShouldNotProcessIssueLog;
@property (readonly, copy) NSArray *indexables;
@property (readonly, copy) NSArray *testables;
@property (readonly) NSString *displayName;
@property (readonly) BOOL isLocalizable;
@property (readonly, nonatomic) DVTModelObjectGraph *objectGraph;

/* class methods */
+ (id)latestAvailableSwiftLanguageVersionAndReturnError:(id *)error;
+ (void)initialize;
+ (unsigned long long)assertionBehaviorForKeyValueObservationsAtEndOfEvent;
+ (id)containerFileDataType;
+ (id)containerTypeDisplayName;
+ (id)currentProjectFileExtension;
+ (id)allowedProjectArchiveVersions;
+ (long long)obsoleteProjectVersion;
+ (void)setXcode3ProjectCreationErrorHandler:(Class)handler;
+ (id)xcode3ProjectCreationErrorHandler;
+ (id)availableSwiftVersions;
+ (id)swiftCompilerSpecification;
+ (id)keyPathsForValuesAffectingName;
+ (id)keyPathsForValuesAffectingPreferredProjectVersion;
+ (id)keyPathsForValuesAffectingAvailableProjectVersions;
+ (id)keyPathsForValuesAffectingAvailableProjectVersionDisplayNames;
+ (BOOL)supportsFilePersistence;
+ (BOOL)_shouldTrackReadOnlyStatus;
+ (id)containerDataFilePathsForFilePath:(id)path;
+ (id)keyPathsForValuesAffectingBlueprints;
+ (id)keyPathsForValuesAffectingSourcePackageReferences;
+ (id)keyPathsForValuesAffectingBaseLocalized;
+ (id)keyPathsForValuesAffectingIndexables;
+ (id)pasteboardDataType;
+ (id)deserializedSourceListItem:(id)item;
+ (id)keyPathsForValuesAffectingTestables;

/* instance methods */
- (id)supportedSourceListItemEditorClasses;
- (id)availableProjectVersionDisplayNames;
- (id)ideModelObjectTypeIdentifier;
- (id)localizedDescription;
- (BOOL)hasValueSetForBuildSetting:(id)setting;
- (void)syncTargetProxiesWithProjectTargets;
- (id)xcode3TargetForPBXTarget:(id)pbxtarget;
- (id)initWithFilePath:(id)path extension:(id)extension workspace:(id)workspace options:(id)options error:(id *)error;
- (void)_willInvalidateContainerToDiscardInMemoryRepresentation;
- (void)becomeWorkspaceWrappingContainer;
- (BOOL)containerEdited;
- (void)setContainerEdited:(BOOL)edited;
- (void)_setContainerEdited;
- (void)primitiveInvalidate;
- (id)createRootGroup;
- (id)_itemBaseFilePathForFilePath:(id)path;
- (void)_containerDidLoad;
- (void)holdOnDiskFilesForICloudDriveIfNecessary;
- (BOOL)supportsOnDemandResources;
- (BOOL)writeToFilePath:(id)path forceWrite:(BOOL)write error:(id *)error;
- (id)containerDataFilePathsForFilePath:(id)path;
- (void)_projectNeedsRevert:(id)revert;
- (void)_projectDidSave:(id)save;
- (void)_projectWillChange:(id)change;
- (void)_projectDidChange:(id)change;
- (void)_projectBuildSettingsDidChange:(id)change;
- (void)_projectDidAddTarget:(id)target;
- (void)_projectWillRemoveTarget:(id)target;
- (void)_packageReferenceWillChange:(id)change;
- (void)_packageReferenceDidChange:(id)change;
- (void)_developmentRegionDidChange:(id)change;
- (id)sourcePackageReferenceFromXCSwiftPackageReference:(id)reference;
- (void)addSourcePackageReference:(id)reference;
- (id)blueprintForName:(id)name;
- (id)blueprintForIdentifier:(id)identifier;
- (id)blueprintForPBXTarget:(id)pbxtarget;
- (BOOL)hasConfigurationNamed:(id)named;
- (id)sortedLocalizationsIncludingBase:(BOOL)base;
- (void)_invalidateSortedLocalizations;
- (BOOL)isBaseLocalized;
- (void)addLocalization:(id)localization;
- (void)copyLocalizationVariantGroups:(id)groups toLocalization:(id)localization completionBlock:(id /* block */)block;
- (void)moveLocalizationVariantGroups:(id)groups toLocalization:(id)localization completionBlock:(id /* block */)block;
- (void)moveBaseLocalizationToLocalization:(id)localization completionBlock:(id /* block */)block;
- (void)removeLocalization:(id)localization deleteFiles:(BOOL)files completionBlock:(id /* block */)block;
- (void)_updateDevelopmentLocalizationInInfoPlist;
- (void)_changePBXProjectDevelopmentRegion:(id)region project:(id)project withNestedProjects:(BOOL)projects;
- (void)_swapProjectLprojRecursive:(id)recursive project:(id)project completionBlock:(id /* block */)block;
- (void)_addFileReferenceAfterSwapForVariantGroupVariant:(id)variant variant:(id)variant group:(id)group completionBlock:(id /* block */)block;
- (void)_swapProjectLproj:(id)lproj project:(id)project withNestedProjects:(BOOL)projects completionBlock:(id /* block */)block;
- (void)_invalidateDefaultReferencesAndSortedLocalizations;
- (void)changeDevelopmentLanguage:(id)language swapLocalizations:(BOOL)localizations includeNestedProjects:(BOOL)projects completionBlock:(id /* block */)block;
- (BOOL)containsVariantInLocalization:(id)localization;
- (void)enableAnalyzerLocalizabilityCheckIfNeeded;
- (void)enableStringCatalogGenerationAtExportTimeIfNeeded;
- (void)_enableSettingIfNotAlreadyCustomized:(id)customized;
- (BOOL)setBaseSDKPlatform:(id)sdkplatform forConfiguration:(id)configuration;
- (BOOL)setBuildSettingsFromDictionary:(id)dictionary forConfigurationsNamed:(id)named error:(id *)error;
- (void)_runUpgradeChecksIfNecessary;
- (void)enumerateUpgradeTasksWithBlock:(id /* block */)block;
- (id)_registerDeferredCustomUpgradeTask:(id)task handler:(id)handler;
- (id)_deferredCustomUpgradeTaskForUUID:(id)uuid;
- (id)_deferredCustomUpgradeHandlerForUUID:(id)uuid;
- (void)_unregisterDeferredCustomUpgradeTask:(id)task handler:(id)handler;
- (void)analyzeModelForIssues;
- (BOOL)installSourcesToPath:(id)path;
- (id)serializedSourceListItem;
- (void)updateLastUpgradeVersionToCurrent;
- (void)_updateCachedLastUpgradeVersionToCurrent;
- (id)customDataSpecifiersForGrouping:(id)grouping ownership:(id)ownership;
- (id)customDataOwnershipsForGrouping:(id)grouping;
- (id)readCustomDataWithSpecifier:(id)specifier error:(id *)error;
- (void)writeCustomData:(id)data withSpecifier:(id)specifier forceOverwrite:(BOOL)overwrite completionQueue:(id)queue completionBlock:(id /* block */)block;
- (void)removeCustomDataWithSpecifier:(id)specifier completionQueue:(id)queue completionBlock:(id /* block */)block;
- (void)moveCustomDataWithSpecifier:(id)specifier toSpecifier:(id)specifier completionQueue:(id)queue completionBlock:(id /* block */)block;
- (BOOL)supportsCustomDataForOwnership:(id)ownership;
- (void)customDataStoreContainerClosing:(id)closing;
- (void)scmStatusForSpecifier:(id)specifier completionBlock:(id /* block */)block;
- (void)addSpecifier:(id)specifier inWorkspace:(id)workspace toSCMWithCompletionBlock:(id /* block */)block;
- (id)testableForBlueprint:(id)blueprint;
- (void)_updateTestablesForTargetProxies:(id)proxies;
- (void)clearTestablesCache;
- (id)cachedMacroExpansionScopeForBuildParameters:(id)parameters;
- (id)allBuildSettingNamesWithBuildParameters:(id)parameters;
- (id)evaluatedStringValueForBuildSetting:(id)setting withBuildParameters:(id)parameters;
- (id)evaluatedStringListValueForBuildSetting:(id)setting withBuildParameters:(id)parameters;
- (id)stringByEvaluatingBuildSettingExpressionString:(id)string withBuildParameters:(id)parameters;
- (id)absolutePathByEvaluatingBuildSettingExpressionString:(id)string withBuildParameters:(id)parameters;
- (int)buildSystemTypeFromString:(id)string;
- (void)registerObserver:(id)observer forStateChange:(id)change invokeImmediately:(BOOL)immediately withHandler:(id /* block */)handler;
- (void)unregisterObserver:(id)observer forStateChange:(id)change;
- (void)notifyObserversOfStateChange:(id)change withPreviousValue:(id)value;
@end

#endif /* Xcode3Project_h */
