//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22526.0.0.0.0
//
#ifndef Xcode3ProjectVersion_h
#define Xcode3ProjectVersion_h
#import <Foundation/Foundation.h>

#include "XCArchiveFormat.h"

@class NSString;

@interface Xcode3ProjectVersion : NSObject

@property (readonly, nonatomic) XCArchiveFormat *xcArchiveFormat;
@property (readonly, nonatomic) unsigned long long archiverVersion;
@property (readonly, copy, nonatomic) NSString *displayName;

/* class methods */
+ (id)supportedProjectVersions;
+ (id)closestMatchingProjectVersionForString:(id)string;

/* instance methods */
- (id)initWithArchiveFormat:(id)format;
- (BOOL)isEqualToProjectVersion:(id)version;
- (BOOL)isEqual:(id)equal;
- (unsigned long long)hash;
@end

#endif /* Xcode3ProjectVersion_h */
