//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22526.0.0.0.0
//
#ifndef XCRoots_h
#define XCRoots_h
#import <Foundation/Foundation.h>

#include "PBXProject.h"

@class NSMutableArray;

@interface XCRoots : NSObject {
  /* instance variables */
  PBXProject *_project;
  NSMutableArray *_roots;
}

/* instance methods */
- (id)initWithArray:(id)array project:(id)project;
- (id)roots;
- (void)setRoots:(id)roots;
- (id)description;
- (id)absolutePathForRoot:(id)root;
@end

#endif /* XCRoots_h */
