//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22526.0.0.0.0
//
#ifndef XCSpecification_h
#define XCSpecification_h
#import <Foundation/Foundation.h>

#include "DVTRegistrable-Protocol.h"
#include "XCSpecification.h"

@class DVTVersion, NSArray, NSBundle, NSDictionary, NSString, TSPropertyListDictionary;

@interface XCSpecification : NSObject<DVTRegistrable> {
  /* instance variables */
  XCSpecification *_superSpecification;
  NSDictionary *_properties;
  TSPropertyListDictionary *_tsProperties;
  NSDictionary *_localizationDictionary;
  NSBundle *_bundle;
  NSString *_domain;
}

@property (readonly) NSString *identifier;
@property (readonly) NSArray *aliases;
@property (readonly) DVTVersion *version;
@property (readonly) NSString *displayName;
@property (readonly) NSString *displayDescription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (Class)specificationTypeBaseClass;
+ (id)specificationType;
+ (id)localizedSpecificationTypeName;
+ (id)specificationTypePathExtensions;
+ (id)specificationRegistryName;
+ (void)_recursivelyEnumerateSpecificationsInStartDomain:(id)domain currentDomain:(id)domain registryNameOrNil:(id)nilNot specificationIdentifierOrNil:(id)nilNot alreadyEnumeratedDomains:(id)domains alreadyEnumeratedIdentifiers:(id)identifiers stopPtr:(BOOL *)ptr usingBlock:(id /* block */)block;
+ (void)_enumerateAllSpecificationsInDomain:(id)domain registryNameOrNil:(id)nilNot specificationIdentifierOrNil:(id)nilNot includingDefault:(BOOL)defaultNot usingBlock:(id /* block */)block;
+ (void)enumerateAllSpecificationsInDomain:(id)domain includingDefault:(BOOL)defaultNot usingBlock:(id /* block */)block;
+ (void)enumerateSpecificationsInDomain:(id)domain includingDefault:(BOOL)defaultNot usingBlock:(id /* block */)block;
+ (id)specificationRegistryForDomain:(id)domain;
+ (id)_typesToSpecTypeBaseClassesRegistry;
+ (id)_pathExtensionsToTypesRegistry;
+ (void)registerSpecificationTypeBaseClass:(Class)class;
+ (void)registerSpecificationOrProxy:(id)proxy;
+ (id)registerSpecificationProxyFromPropertyList:(id)list inDomain:(id)domain outSpecificationOrProxy:(id *)proxy;
+ (id)registerSpecificationProxyFromPropertyList:(id)list;
+ (id)_registerSpecificationProxiesOfType:(id)type fromDictionaryOrArray:(id)array inDirectory:(id)directory bundle:(id)bundle sourceDescription:(id)description inDomain:(id)domain;
+ (void)_tryRegisterLocalizationDictionaryForSpecification:(id)specification bundle:(id)bundle;
+ (BOOL)_shouldRecurseIntoDirectoryNamed:(id)named ofType:(id)type;
+ (id)registerSpecificationProxiesFromPropertyListsInDirectory:(id)directory recursively:(BOOL)recursively inDomain:(id)domain inBundle:(id)bundle;
+ (id)registerSpecificationProxiesFromPropertyListsInDirectory:(id)directory recursively:(BOOL)recursively inDomain:(id)domain;
+ (id)registerSpecificationProxiesFromPropertyListsInDirectory:(id)directory recursively:(BOOL)recursively;
+ (void)registerSpecificationsFromDVTPlugInsForDomains:(id)domains skippingDomains:(id)domains;
+ (void)_getDomain:(id *)domain identifier:(id *)identifier fromDomainPrefixedIdentifier:(id)identifier;
+ (id)specificationForIdentifier:(id)identifier inDomain:(id)domain;
+ (id)specificationForIdentifier:(id)identifier;
+ (id)specificationsForIdentifiers:(id)identifiers inDomain:(id)domain;
+ (id)specificationsForIdentifiers:(id)identifiers;
+ (id)registeredSpecificationsInDomain:(id)domain;
+ (id)registeredSpecifications;
+ (id)_subSpecificationsOfSpecification:(id)specification inDomain:(id)domain;
+ (id)registeredBaseSpecificationsInDomain:(id)domain;
+ (id)registeredBaseSpecifications;
+ (id)allRegisteredSpecifications;
+ (id)specificationTypeForPathExtension:(id)extension;
+ (Class)specificationBaseClassForType:(id)type;
+ (BOOL)_booleanValueForValue:(id)value;

/* instance methods */
- (id)initWithPropertyListDictionary:(id)dictionary inDomain:(id)domain;
- (id)initWithPropertyListDictionary:(id)dictionary;
- (id)initAsMissingSpecificationProxyWithIdentifier:(id)identifier name:(id)name description:(id)description inDomain:(id)domain;
- (id)init;
- (void)awakeAfterInitialization;
- (id)superSpecification;
- (id)subSpecificationsInDomain:(id)domain;
- (id)subSpecifications;
- (id)kindOfSpecificationDistance:(id)distance;
- (BOOL)isKindOfSpecification:(id)specification;
- (BOOL)isAbstract;
- (BOOL)showOnlySelfDefinedPropertiesInBuildSettingsGUI;
- (BOOL)isNotYetLoadedSpecificationProxy;
- (id)loadedSpecification;
- (BOOL)isMissingSpecificationProxy;
- (id)type;
- (id)properties;
- (id)tsProperties;
- (id)localizationDictionary;
- (id)bundle;
- (id)domain;
- (id)name;
- (id)localizedDescription;
- (long long)identifierCompare:(id)compare;
- (long long)nameCompare:(id)compare;
- (id)_objectForKeyIgnoringInheritance:(id)inheritance;
- (id)objectForKey:(id)key;
- (id)stringForKey:(id)key;
- (id)arrayForKey:(id)key;
- (id)dictionaryForKey:(id)key;
- (id)dataForKey:(id)key;
- (long long)integerForKey:(id)key;
- (long long)longLongForKey:(id)key;
- (float)floatForKey:(id)key;
- (double)doubleForKey:(id)key;
- (BOOL)boolForKey:(id)key;
- (BOOL)boolForKeyFromProxy:(id)proxy;
- (id)arrayOrStringForKey:(id)key;
- (id)valueForUndefinedKey:(id)key;
@end

#endif /* XCSpecification_h */
