//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.442, BuildTime: 2023-12-27T19:00:48Z)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.0, SDK: 14.0, Tool: ld (1022.1)
//    - LC_SOURCE_VERSION: 22516.0.0.0.0
//
#ifndef XCTHLaunchSession_Protocol_h
#define XCTHLaunchSession_Protocol_h
#import <Foundation/Foundation.h>

@class XCTestConfiguration;

@protocol XCTHLaunchSession <NSObject>

@property (nonatomic, copy) NSError *alertError;
@property (nonatomic) long long state;
@property (nonatomic) int runnablePID;
@property (nonatomic, readonly) NSSet *consoleAdaptors;
@property (nonatomic, retain) XCTestConfiguration *testConfiguration;
@property (nonatomic, retain) NSObject<XCTHDebugSession> *currentDebugSession;
@property (nonatomic, copy) NSString *runnableDisplayName;
@property (nonatomic) BOOL hasExitCode;
@property (nonatomic) long long exitCode;
@property (nonatomic) BOOL hasCrashed;
@property (nonatomic, retain) NSNumber *terminatingSignal;
@property (nonatomic, readonly) NSObject<XCTHRunDestination> *runDestination;

@end

#endif /* XCTHLaunchSession_Protocol_h */
